### ISSUE TITLE
Cocoapods 1.0.0

### ISSUE THREAD

**Issue by bbrflores** [usabilla/usabilla-u4a-ios-swift-sdk#1]
We started integration of Usabilla on our project last week and we are following the deployment of the swift sdk. This week after updating cocoapods gem to 1.0.0 I started getting the following error, that I think is related to the Podspec file missing requirements (for the latest cocoapods release).

```
[!] The "UsabillaFeedbackForm" pod failed to validate due to 1 error:
- WARN  | attributes: Missing required attribute "license".
- ERROR | attributes: Missing required attribute "source".
- WARN  | license: Missing license type.
```

Let me know if could even help test out the new release.

**Comment by gPinato** [comment]
The source configuration line was indeed missing in the podspec. I've added it in the latest release and I can successfully validate the pod, could you try now?

It is still going to warn you about a missing license file, on which we are currently working on.
You can ignore them using `pod spec lint UsabillaFeedbackForm.podspec --allow-warnings`

**Comment by bbrflores** [comment]
Great! I already updated my pods and I don't see the error anymore. Thanks!
