### ISSUE TITLE
Readme forgets setting yourself as the delegate. ;) + use a block please

### ISSUE THREAD

**Issue by Daij-Djan** [usabilla/usabilla-u4a-ios-swift-sdk#10]
UsabillaFeedbackForm.delegate = self

//

+ use a block please

**Comment by gPinato** [comment]
I will update the ReadMe with the new instruction alongside the new release. Thanks for pointing that out.

Could you be a little more specific regarding the "use a block" ?

**Comment by Daij-Djan** [comment]
hehe sure :)

I meant: dont use a delegate for the async initializing but use a callback block like you guys did with the objective c api ... these delegates are kinda pointless IMO since they are one shot.

**Comment by gPinato** [comment]
Readme has been updated. I'll probably move to a block with the next release, when I have more time to test it properly.    

 Thanks for the suggestion
