### ISSUE TITLE
Support for Xcode 10 / iOS 12 / Swift 4.2

### ISSUE THREAD

**Issue by datishans** [usabilla/usabilla-u4a-ios-swift-sdk#100]
When do you guys plan on releasing a  Xcode 10 / iOS 12 / Swift 4.2-compatible library?

Really need this!

**Comment by Rifinio** [comment]
Hello @datishans,
There is an [issue](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/98) already opened regarding this same matter ! We are working on it and we'll update you as soon as it's done.

**Comment by Rifinio** [comment]
Hello @datishans,
We have published a new release built with Xcode 10 beta. Thank you for your patience!
Please let us know if this works for you!
