### ISSUE TITLE
Usabilla SDK causes memory leaks

### ISSUE THREAD

**Issue by cosminstirbu** [usabilla/usabilla-u4a-ios-swift-sdk#101]
Hello,

I've attached a sample project where you can see that each Usabilla.FormViewController and Usabilla.PageViewController is kept alive after each time you present the form.

Also other Usabilla related objects are kept alive as well.

You can use the Allocations instruments and you'll see that the memory keeps increasing each time you present the form, and it never decreases after you dismiss the form.

Please have a look into this as it is quite harmful for the integrating apps.

Regards,
Cosmin
[Usabilla Memory Leaks.zip](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/files/2114990/Usabilla.Memory.Leaks.zip)

**Comment by Rifinio** [comment]
Hello @cosminstirbu, 
Thank you for pointing this out. I will take an in-depth look at this!

Best,
Adil.

**Comment by Rifinio** [comment]
Hello @cosminstirbu,
So we just had a look at the project and this is a screenshot of the Instruments leak tool. and it shows all green when interacting with Usabilla forms and that there are no Leaks?
<img width="891" alt="leak-screenshot-1" src="https://user-images.githubusercontent.com/917876/45222805-c6dd0b80-b2b5-11e8-9d08-16fd0be3963c.png">

**Comment by torkvell** [comment]
Hi all,

This ticket will now be closed as the enhancement feature has been added to our backlog for possible future product updates. Thanks for reporting and please keep on coming with your valuable feedback!
