### ISSUE TITLE
Usabilla form initilization call back

### ISSUE THREAD

**Issue by akrant06** [usabilla/usabilla-u4a-ios-swift-sdk#102]
Hi, 
I am initializing Usabilla in app delegate methods as below

` Usabilla.initialize(appID: "xxx-xxx-xxxxx-xxx") {
                print("Usabilla initiliaztion completed")
            }`
I am not getting call back on specific device but works well on simulator. 

What are the other parameter for initilization to fail? 

Xcode Version - 9.4.1
Device Version - iPad pro 10.5 (iOS version - 11.4)
Usabilla version - 4.1.2

**Comment by Rifinio** [comment]
Hello @akrant06,
you can do `Usabilla.debugEnabled = true` to enable debugging. This will log if there are any problems in the network!

**Comment by gPinato** [comment]
Hello @akrant06 ,

have you set the `Usabilla.delegate` to the object you expect to receive the callback?

**Comment by torkvell** [comment]
Hi @akrant06, 

I'm from Usabilla support. Please let us know if this is still an issue at your end so we can give you the needed support on this. 

Looking forward to your reply.
