### ISSUE TITLE
Support latest Xcode 10 build

### ISSUE THREAD

**Issue by daveanderson** [usabilla/usabilla-u4a-ios-swift-sdk#104]
As we attempt to keep our codebase prepared for the GM release of Xcode, we have been obligated to remove Usabilla because you do not have binary compatibility with Xcode 10b4 or later.

Please provide binary compatibility with the latest pre-release Xcode or provide complete source code so that we can build it ourselves.

**Comment by Goseong** [comment]
Hi @daveanderson, please use the following tag for the latest Xcode support, v5.0.2-Xcode-10-beta5

Currently, we are not in a position in which we can facilitate a release for every beta version of Xcode. However, you will always be able to expect a compatible version for a GM release as quickly as we can.
