### ISSUE TITLE
Xcode 10 - Carthage - no shared framework schemes

### ISSUE THREAD

**Issue by leobarrospereira** [usabilla/usabilla-u4a-ios-swift-sdk#105]
Hey guys,

I'm trying to use the version from tag v5.0.2-Xcode-10-beta5 but when I run: 
```
carthage update usabilla-u4a-ios-swift-sdk --platform iOS
```

In the end I get this warning:
```
*** Checking out usabilla-u4a-ios-swift-sdk at "v5.0.2-Xcode-10-beta5"
*** xcodebuild output can be found in /var/folders/9d/tlndnr0s115blnfgxlc4k74c0000gp/T/carthage-xcodebuild.AfPMat.log
*** Skipped building usabilla-u4a-ios-swift-sdk due to the error:
Dependency "usabilla-u4a-ios-swift-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/new
```

And when I try to build the project I get an error on the Carthage build phase that copies Carthage frameworks:
![screen shot 2018-08-07 at 12 27 20](https://user-images.githubusercontent.com/6533999/43770718-72b701b8-9a3d-11e8-9c25-be4eb7003fdf.png)

I'm using Xcode 10 beta 5 and Carthage 0.30.1

Do you have any clue how can I solve this?

Thanks!

**Comment by gPinato** [comment]
Hi @leobarrospereira ,

the carthage file was missing.
Could you try again now and let me know if everything works well?

**Comment by gPinato** [comment]
Fantastic. No problem.
