### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'unexpected start state'

### ISSUE THREAD

**Issue by iCarambaa** [usabilla/usabilla-u4a-ios-swift-sdk#106]
Hi,

we see frequent crashes like the one attached originating from Usabilla. Seems like a problem with HTML parsing.

Sven
[2317acdab5081d4e847c4ef15ddd3860.log](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/files/2266743/2317acdab5081d4e847c4ef15ddd3860.log)

**Comment by Goseong** [comment]
Hi @iCarambaa, could you share your account name and form or campaign id with support@usabilla.com, then we can have a look at your configuration. Thanks.

**Comment by iCarambaa** [comment]
We're using Usabilla 5.0.2, about 30 crashes in the last 14 days. Devices range from iPhone SE to iPhone 8, but no iPhone X. OS Versions from 10.3.3 to 11.4.1.

**Comment by Goseong** [comment]
Hi Sven,

Thanks for getting back so quickly. That is certainly not as expected. 

The deep link to Apple's e-mail client works fine for me both with and without the client installed. Also not able to reproduce the problem in our own configuration nor the Eurowings production app.

Will keep you up to date here.

**Comment by torkvell** [comment]
Hi @iCarambaa, 

I'm from Usabilla support. I'm wondering if this is still an issue at your end or if you still need our support on this matter?

Looking forward to your reply.
