### ISSUE TITLE
`Xcode10-beta6` branch, please?

### ISSUE THREAD

**Issue by Nonnus** [usabilla/usabilla-u4a-ios-swift-sdk#107]
hi
can we get an update to the `Xcode10-beta5` branch for beta6, please?
thanks a lot!

**Comment by Goseong** [comment]
Hi @Nonnus,

You can expect a release next week due to holidays. Let me know if this obstructs your development. 

Regards,

Tjerk

**Comment by Nonnus** [comment]
hi @Goseong, thanks a lot for your quick reply

thats a little unfortunate, as next week we might have even have a new beta available :)

it really is too long for us not being able to use xcdode beta6 but i suppose we can temporarily remove usabilla to be able to compile our app while developing new ios 12 features

**Comment by Goseong** [comment]
Yes, I can imagine that this is holding you back in your new development. 

Sorry for the inconvenience, next week the most of the team is back from holiday.

**Comment by Nonnus** [comment]
thanks!
i also understand the team needs some well deserved holidays
it is just a side effect of the prebuilt nature of the sdk you distribute, if it was compiled on demand we might be able to rebuilt with new toolchain without any issues

in any case, i already removed usabilla temporaly from our app so we can proceed with development,
will add it back as soon as you provide a new build (just need to revert a commit so no biggie ;) )

ps: i assume that after next week with team around we wont have this issue again with upcoming betas until gm is released?

**Comment by Nonnus** [comment]
hi @Goseong 
any news about this topic?

**Comment by Rifinio** [comment]
Hello guys!

A new release has been published for the [Xcode 10 beta 6](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v5.0.2-Xcode-10-beta6).

Thank you for your patience!
