### ISSUE TITLE
Xcode 10 - Warns About Missing Architecture After Build

### ISSUE THREAD

**Issue by geoffclifton** [usabilla/usabilla-u4a-ios-swift-sdk#108]
Hello,
I've testing my application on iOS 10 and have run into a strange warning. After building in Xcode 10 for run on a simulator, I'm shown the following warning which appears Usabilla related from Cocoapods.

warning: [CP] Vendored binary '/Users/User/Library/Developer/Xcode/DerivedData/AppName-axdnikzwyszcoebsuwkbukbpzdar/Build/Intermediates.noindex/AppName.build/Debug-iphonesimulator/AppName.build/DerivedSources/Usabilla.framework.dSYM/Contents/Resources/DWARF/Usabilla' contains architectures (armv7 arm64) none of which match the current build architectures (x86_64).

Stripping of the unneeded architectures from the framework occurs without issue but it seems to complain when handling the dSYM.
The mentioned issue also does not occur when building for an actual device.

Any suggestions as to what could be causing this warning?

Thanks.

**Comment by geoffclifton** [comment]
**[Update]** I've determined that the error is shown because of a difference in architectures included in the dSYM content

When running against 5.0.2:

> lipo -info Usabilla.framework.dSYM/Contents/Resources/DWARF/Usabilla
> Architectures in the fat file: Usabilla are: i386 x86_64 armv7 armv7s arm64 

When running against the branch Xcode 10 branch (v5.0.2-Xcode-10-beta5):

> lipo -info Usabilla.framework.dSYM/Contents/Resources/DWARF/Usabilla 
> Architectures in the fat file: Usabilla are: armv7 arm64 

Usabilla team, can this pleas be corrected?

**Comment by geoffclifton** [comment]
Hello,
Any update on this issue from the Usabilla team? @Goseong ?

**Comment by geoffclifton** [comment]
Hi @Rifinio - sorry for the delay in response. 
Yes, I have updated to the new beta 6 branch but the issue is still occurring.

**Comment by lukecharman** [comment]
Yes, its still there in beta 6. Also is there a release date for when the Xcode 10 release will be merged?

**Comment by plezervi** [comment]
I have the same problem, using v5.0.2-Xcode10-GM

```
-= Output =-
Undefined symbols for architecture armv7:
"___llvm_profile_runtime", referenced from:
__hidden#452_ in 001.o
__hidden#452_ in 002.o
__hidden#452_ in 003.o
__hidden#452_ in 004.o
__hidden#452_ in 005.o
__hidden#452_ in 006.o
__hidden#452_ in 007.o
...
ld: symbol(s) not found for architecture armv7
Exited with 1


error: Failed to compile bundle: /var/folders/vq/j6j2lh1s3cz7cbpw7shc9149fy4t4_/T/UsabillavOZMeH/Usabilla.armv7.xar
```

Usabilla currently blocking our release. When we can expect a new release?

**Comment by pnotel** [comment]
For me, this error only occurs when exporting an ipa with bitcode enabled (so for appstore release). 
My release is currently blocked by Usabilla...

**Comment by lukecharman** [comment]
Just a heads-up, that this issue has not been fixed with the 5.1.0 update :(

**Comment by tzengerink** [comment]
@geoffclifton Can you confirm that the release of [v5.1.2](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v5.1.2) fixes the issue of missing architecture?

**Comment by geoffclifton** [comment]
@tzengerink Confirmed that v5.1.2 resolves the missing architecture warning.
Thanks.
