### ISSUE TITLE
2 Unable to simultaneously satisfy constraints errors in the usabilla VC

### ISSUE THREAD

**Issue by Daij-Djan** [usabilla/usabilla-u4a-ios-swift-sdk#11]
Looks ugly in the console ;)

**Comment by gPinato** [comment]
I will remove the warning in the next release.

**Comment by monk4june** [comment]
There is also a noticeable delay in form being created and presented.It could also be a result of these constraint exceptions.

**Comment by gPinato** [comment]
Just to make sure there are no broken constraint that I'm missing because of the form I'm testing with, can you show me a copy of the logs you're getting?

**Comment by Daij-Djan** [comment]
sorry it took ages:

2016-09-21 20:19:01.900 Customer[40042:607984] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fe8f5341de0 H:|-(8)-[UILabel:0x7fe8f5341620'How satisfied were you wi...']   (Names: '|':UITableViewCellContentView:0x7fe8f5340b60 )>",
    "<NSLayoutConstraint:0x7fe8f18fbbd0 UILabel:0x7fe8f5341620'How satisfied were you wi...'.leading == UITableViewCellContentView:0x7fe8f5340b60.leadingMargin>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fe8f18fbbd0 UILabel:0x7fe8f5341620'How satisfied were you wi...'.leading == UITableViewCellContentView:0x7fe8f5340b60.leadingMargin>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-21 20:19:01.900 Customer[40042:607984] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fe8f1c781c0 H:|-(8)-[UILabel:0x7fe8f1c77a00'How satisfied were you wi...']   (Names: '|':UITableViewCellContentView:0x7fe8f1c76300 )>",
    "<NSLayoutConstraint:0x7fe8f1c7c8d0 UILabel:0x7fe8f1c77a00'How satisfied were you wi...'.leading == UITableViewCellContentView:0x7fe8f1c76300.leadingMargin>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fe8f1c7c8d0 UILabel:0x7fe8f1c77a00'How satisfied were you wi...'.leading == UITableViewCellContentView:0x7fe8f1c76300.leadingMargin>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by gPinato** [comment]
Ok, that log is not super helpful tho. Can I have the form ID that causes you those trouble? That way I can just open your form on my device and debug it from there.

**Comment by Daij-Djan** [comment]
I am not posting that id here. sorry
You can contact me via email from your official usabilla account and I will check if I can send it to you there

**Comment by Daij-Djan** [comment]
2.1 fixed it for me

**Comment by TouseefSarwar** [comment]
how you fixed this issue @Daij-Djan
