### ISSUE TITLE
Usabilla form does not presents a page if not loaded from inside of a View controller

### ISSUE THREAD

**Issue by k28gupta** [usabilla/usabilla-u4a-ios-swift-sdk#112]
Usabilla creates it's own `UINavigationController`, so it can be presented on top of any view controller.
So, I have this presenter where I set usabilla delegate and try to load a valid form - It never calls the following method `func formDidLoad(form: UINavigationController)` 

Raw Presenter is as follows: 

```
final class ApplicationSurveyPresenter: ApplicationSurveyPresenterProtocol {
    
    var presentingViewController: UIViewController?
    var formId: String?
    
    func present() {
        guard let formId = formId else { return }
        Usabilla.delegate = self
        Usabilla.loadFeedbackForm(formId)
    }
    
    func formDidLoad(form: UINavigationController) {
        // This is not called
        guard let presentingVc = presentingViewController else { return }
        presentingVc.present(form, animated: false) {
            
        }
  
     func formDidFailLoading(error: UBError) {
        // This is not called either
    }
}

protocol ApplicationSurveyPresenterProtocol: UsabillaDelegate {
    
    var formId: String? { get set }
    
}
```
Whereas, when I do the exact same thing in a view controller it works. So may be the delegate has some special conditions that are not defined.

**Comment by Rifinio** [comment]
Hi @k28gupta,
you are assigning `self` to `Usabilla.delegate` which in this case you should be assigning the `presentingViewController` as delegate.

**Comment by torkvell** [comment]
Hi @k28gupta, 

I'm reaching out to you from Usabilla support. I would like to ask you if this is still an issue on your end?

Have you made sure that you initialize our SDK? Ideally, this should be done in the `applicationDidFinishLaunching`. Without initializing our SDK correctly, none of the reported functions will be called. 

Looking forward to your reply.
