### ISSUE TITLE
Usabilla framework binary [Xcode10-GM branch] contains instrumentation code

### ISSUE THREAD

**Issue by itoxa** [usabilla/usabilla-u4a-ios-swift-sdk#116]
If you try to submit an app with Usabilla framework from Xcode10-GM branch your app will be marked as "binary is invalid" in appstoreconnect. The reason is described in https://developer.apple.com/library/archive/qa/qa1964/_index.html.

You could check it in Terminal:
`otool -l -arch all <PATH_TO_USABILLA_BINARY> | grep __llvm_prf`

**Comment by Rifinio** [comment]
@itoxa  Please use the latest SDK release [v5.1.2 ](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v5.1.2). This issue is already fixed there!
