### ISSUE TITLE
Is it possible to modify the questions in runtime to include custom information for each customer?

### ISSUE THREAD

**Issue by hasanalbukhari** [usabilla/usabilla-u4a-ios-swift-sdk#117]
For example, If I want the customer to rate his chat conversation with one of our customer support people. I would like to modify the question to have the customer support guy.

"Was your conversation with Alex helpful?"

**Comment by keshcreations** [comment]
Hi @hasanalbukhari,

Currently, it is not possible to dynamically fill in the questions in the Usabilla forms or Campaigns. What is set up in the Usabilla back-end, will be displayed to your users.

However, while I’m afraid I can’t make any promises, I am going to share your thoughts with our team here for consideration in future developments.

If there is anything else I can help with, please don’t hesitate to get back in touch.
