### ISSUE TITLE
Unable to Change StatusBarStyle When Presenting Form Modally in .fullScreen

### ISSUE THREAD

**Issue by geoffclifton** [usabilla/usabilla-u4a-ios-swift-sdk#118]
In Swift 4.2/iOS 12, setting the status bar style via UIApplication.shared.statusBarStyle is now deprecated.

In order to set the statusBarStyle, you must now edit your plist to include "View controller-based status bar appearance" to YES and override preferredStatusBarStyle in your view controllers.

Usabilla's provided method of Usabilla.theme.statusBarStyle no longer works and should be updated to support iOS 12.

**Comment by geoffclifton** [comment]
Any updates on this issue?

**Comment by tzengerink** [comment]
@geoffclifton We've put it on our backlog. We're currently focussing on other features, but hope to be able to put this into the next release. Right now we can't promise anything regarding dates.

**Comment by andlie** [comment]
Latest version 6.0.1, also supports  iOS 11+ statusBarStyle
