### ISSUE TITLE
5.1.3 release contains LLVM instrumentation, causing AppStore Connect to invalidate the build

### ISSUE THREAD

**Issue by BBdyezhov** [usabilla/usabilla-u4a-ios-swift-sdk#119]
Hello,

The latest release, 5.1.3 contains LLVM instrumentation.  This is causing AppStore Connect to invalidate any build that has this version of Usabilla. 

`| => otool -l -arch all /Users/dyezhov/Library/Developer/Xcode/Archives/2018-10-24/nutrition-ios\ 2018-10-24\ 23.52.38.xcarchive/Products/Applications/nutrition-ios.app/Frameworks/Usabilla.framework/Usabilla | grep llvm`
`sectname __llvm_prf_cnts`
`sectname __llvm_prf_data`
`sectname __llvm_prf_names`
`sectname __llvm_prf_vnds`
`sectname __llvm_covmap`

Here is the error message from AppStore Connect:
`Dear Developer,

We identified one or more issues with a recent delivery for your app, "Beachbody Nutrition+". Please correct the following issues, then upload again.

Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.`

Version 5.1.2 does NOT have LLVM instrumentation.

**Comment by tzengerink** [comment]
Thanks @BBdyezhov for letting us know. We'll look into it and hope to come up with a solution soon.

**Comment by mthormann-dhi** [comment]
This is the exact same issue as [#113](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/113) that was fixed finally with 5.1.2.

**Comment by tzengerink** [comment]
@BBdyezhov @mthormann-dhi We've release [v5.1.4](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases) that should no longer have this LLVM issue.
