### ISSUE TITLE
Xcode 8 Final

### ISSUE THREAD

**Issue by ushafiq** [usabilla/usabilla-u4a-ios-swift-sdk#12]
Hi,

Xcode 8 final has released. My app which uses cocoa pods with third party frameworks. Most of them are already upgraded to xcode 8 so I cannot use xcode 7.3 anymore because of incompatibility.

So now my app is stuck because of Usabilla framework, as it is compiled with an old incompatible version of compiler.

Can I please have ETA for fixing this issue?

**Comment by gPinato** [comment]
Duplicate of #8
