### ISSUE TITLE
Cant build v5.1.3 'Module 'Usabilla' has no member named 'sendEvent''

### ISSUE THREAD

**Issue by puredaycent** [usabilla/usabilla-u4a-ios-swift-sdk#120]
The latest build is not building for me. Getting a 
`Module 'Usabilla' has no member named 'sendEvent'`
If using the previous version, 5.1.2, it build fine however.

**Comment by michel-moreau** [comment]
Same issue here when building in Release mode with 5.1.4

**Comment by torkvell** [comment]
Hi @michel-moreau and @puredaycent. In our next release, we will support 32-bit modules which should solve this issue. It will be released within the next week. If there is anything else, please let me know.

**Comment by albertodebortoli-je** [comment]
We hit these errors when trying to publish a pod on Swift 4.2 with Usabilla 5.1.4 or 6.0.0 as a dependency:

```
- ERROR | [iOS] xcodebuild:  /Users/[...].swift:221:21: error: module 'Usabilla' has no member named 'customVariables'
    - ERROR | [iOS] xcodebuild:  /Users/[...].swift:227:25: error: module 'Usabilla' has no member named 'sendEvent'
    - ERROR | [iOS] xcodebuild:  /Users/[...].swift:524:21: error: module 'Usabilla' has no member named 'customVariables'
    - ERROR | [iOS] xcodebuild:  /Users/[...].swift:530:25: error: module 'Usabilla' has no member named 'sendEvent'
```

**Comment by jijojjp** [comment]
We hit the same error in xcode 10 by changing the simulator device type to `Generic iOS Device` to reproduce it in version 5.1.4 & 6.0.0.

`Module 'Usabilla' has no member named 'theme'`
`Module 'Usabilla' has no member named 'canDisplayCampaigns'`
`Module 'Usabilla' has no member named 'resetCampaignData'`

**Comment by albertodebortoli-je** [comment]
@torkvell it would be easy for your team to reproduce the issue. Just create a brand new project, install Usabilla 6.0.0 via Cocoapods and try building for release.

**Comment by albertodebortoli-je** [comment]
Version 6.0.1 solved the issue! Thanks team for the quick turnaround!

**Comment by jijojjp** [comment]
Thanks, Version 6.0.1 solves the issue and works like a charm!
