### ISSUE TITLE
Usabilla 5.1.4 fails on release build

### ISSUE THREAD

**Issue by koenpunt** [usabilla/usabilla-u4a-ios-swift-sdk#121]
While building my project for release, the build fails with the following output;

```
The following build commands failed:

CompileSwift normal armv7 /Users/Shared/Jenkins/Home/workspace/ios-app/UW/SwiftCompatibility/UsabillaBridge.swift

CompileSwift normal armv7 /Users/Shared/Jenkins/Home/workspace/ios-app/UW/Shared/Navigation/UWViewController+UsabillaDelegate.swift

CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
```

**Comment by edwinveger** [comment]
@andlie Is anyone looking into this?

**Comment by sudhyk** [comment]
Seeing the same, any updates on this ?

**Comment by diederikh** [comment]
Same problem here.

**Comment by michel-moreau** [comment]
Same issue here.

**Comment by JuLink** [comment]
Same

**Comment by ANGOmarcello** [comment]
5.1.2 is the last known stable version for us

**Comment by diederikh** [comment]
@torkvell Apple requiring supporting 64bit does not mean removing support for older arm versions. iPhone 5/5c (iOS 10+) are still on arm7 (see http://iossupportmatrix.com).

**Comment by ANGOmarcello** [comment]
As we use Usabilla in a huge corporate project that still supports iOS 9 I really have to agree with @diederikh. Theres no problem with supporting all these architectures at once.

**Comment by koenpunt** [comment]
@diederikh that's quite an unthoughtful decision. I will have someone reach out to the customer success manager, because this is not acceptable.

**Comment by torkvell** [comment]
Hi all,

First off, we would like to offer you our apologies for the lack of clarity about our latest release. We can only agree that we could have communicated this better.

Regarding our decision to not include 32-bit in version 5.1.4: as said, Apple deciding to shift their focus from 32-bit to 64-bit was and is an important factor for us. However, we appreciate your feedback. We have brought this up with our Product Team and they've confirmed they will make sure the build of our next major version will support 32-bit as well.

To avoid any misunderstandings: version 5.1.2. is still a stable version and does support 32-bit. You can still use this version in the meantime without any difficulties.

**Comment by JuLink** [comment]
Hi @torkvell, 

I'm glad that you are reconsidering the 32-bit drop for your futur release.

But the situation right now is that **we can't use Xcode 10.1 because Usabilla is blocking us** if we want to support iOS 10. To support iOS 10 we have to be able to build for iPhone 5/5C and iPad 4th Gen and to achieve this, we need a 32bit framework of Usabilla.

As you mention, the release that is 32bit compliant is the 5.1.2 but this release is built with Xcode 10.0 and Swift 4.2. Xcode 10.1 is shipped with Swift 4.2.1. This makes the binary of Usabilla incompatible.

So we have to either stay with Xcode 10.0 and the release 5.1.2, use Xcode 10.1 and drop iOS 10 support and use 5.1.4...

**Comment by koenpunt** [comment]
> As you mention, the release that is 32bit compliant is the 5.1.2 but this release is built with Xcode 10.0 and Swift 4.2. Xcode 10.1 is shipped with Swift 4.2.1. This makes the binary of Usabilla incompatible.

We were able to use 5.1.2 with Xcode 10.1..

**Comment by koenpunt** [comment]
> @koenpunt with Carthage?

Nope, cocoapods

**Comment by VValiente** [comment]
We do manual integration for 3rd party frameworks and I just did it for Usabilla. I added the `Usabilla.framework` 5.1.4 into our project. It builds but crashes at launch (both on simulators and device). 

Are we also supposed to integrate the `.dSYM` or just the `.framework`? Either way, it still crashes at start up. Please advise. Thanks.

**Comment by VValiente** [comment]
@torkvell we wanted to integrated Usabilla into our iOS app, but we also encountered an issue with the SDK, both 5.1.4 and 5.1.2.

We use Xcode 10.1, and support `arm64, arm64e, armv7, armv7s`.

We tried manually adding it, then when it did not work, we went for cocoapods. The project builds after adding the framework but crashes at startup: 

![screenshot 2018-12-11 at 13 07 10](https://user-images.githubusercontent.com/6738234/49799844-427fa600-fd46-11e8-9c30-7e538b8f97da.png)
![screenshot 2018-12-11 at 13 07 20](https://user-images.githubusercontent.com/6738234/49799843-427fa600-fd46-11e8-81cb-41bb0116c4b0.png)

**Comment by VValiente** [comment]
Was actually just about to update my message here. We tried it via Carthage and that process worked. So we went back with the manual integration and realized that we only linked it, but failed to embed it. It doesn't crash now. 🎉

**Comment by VValiente** [comment]
@torkvell when archiving the app, it fails because of the framework. Do we need some extra configuration for release? Debug works and we can run the app on the device and simulator. But we didn't manage to make an archive.

**Comment by torkvell** [comment]
Hi @VValiente Thanks for reaching out. We will release our new version within the next week, which will support the 32-bit modules. Please let me know if anything else.

**Comment by PtitChevreuil** [comment]
Good news @torkvell! We actually got the same issue and had to move back to Xcode 10.0 which is not a viable solution as Apple just started to communicate: 

> Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.

**Comment by albertodebortoli-je** [comment]
We are blocked by this too :-(

**Comment by albertodebortoli-je** [comment]
Unfortunately, this is still an issue with version 6.0.0 :(

**Comment by torkvell** [comment]
Hi @albertodebortoli-je. The new version 6.0.0 includes support for 32-bit modules. Could you please elaborate on the specifics that are currently blocking you from using the new SDK? Looking forward to your reply

**Comment by albertodebortoli-je** [comment]
Version 6.0.1 solved the issue! Thanks team for the quick turnaround!

**Comment by michel-moreau** [comment]
nice. CC/ @JuLink
