### ISSUE TITLE
Carthage update failed for v6.0.1

### ISSUE THREAD

**Issue by VValiente** [usabilla/usabilla-u4a-ios-swift-sdk#124]
Added this to our Cartfile:
`github "usabilla/usabilla-u4a-ios-swift-sdk" "v6.0.1"`

And did a `carthage update` but got this:

```
*** Skipped building usabilla-u4a-ios-swift-sdk due to the error:
Dependency "usabilla-u4a-ios-swift-sdk" has no shared framework schemes
```

Did I miss something? Also tried `carthage bootstrap` but also failed.

**Comment by VValiente** [comment]
Seems like it's a Carthage caching issue.

**Comment by torkvell** [comment]
Hi @VValiente. We will update the Carthage settings in the next release, which should remove this error message.

**Comment by torkvell** [comment]
@VValiente,

Pardon for some back and forth on this. There is not much we can do from our end to fix this as it's related to Carthage itself. After some searching, I found these tickets that might be related: https://github.com/Carthage/Carthage/issues/1109
https://github.com/Carthage/Carthage/issues/2380

I hope this helps. Please let me know if there is anything else.
