### ISSUE TITLE
Typo in usa_screnshot_placeholder string key

### ISSUE THREAD

**Issue by davidmigloz** [usabilla/usabilla-u4a-ios-swift-sdk#126]
There is a typo in the string key `usa_screnshot_placeholder`.
`screnshot` should be `screenshot` 😄

**Comment by davidmigloz** [comment]
Thanks Toralf

**Comment by Yozine** [comment]
What is the correct string to replace? I have tried both:
"usa_screnshot_placeholder" = "Screenshot toevoegen";
"usa_screenshot_placeholder" = "Screenshot toevoegen";

Yes I'm Dutch ;)
but neither of them seem to be replaced

**Comment by torkvell** [comment]
Hi @yozine, 

Thanks for reaching out to support on this. 

The string is still "usa_screnshot_placeholder" in our SDK. If you want to use your custom .string file, you also have to call Usabilla.localizedStringFile = "your_localization_file_name". Have you made sure this has been done?

Looking forward to your reply.

**Comment by Yozine** [comment]
Hey @torkvell 

Thank you for your reply! I feel a little silly, because I did forget to add the custom translated localisation file to Usabilla. Once I had however, I found that "usa_screnshot_placeholder" worked. "usa_screenshot_placeholder" did not replace.

Kind regards

**Comment by torkvell** [comment]
Hi @Yozine and @davidmigloz  ,

I would like to inform you that this ticket has been fixed as part of our new release v6.1.0.

I would like to thank you for reporting on this and please let us know if there is anything else we can help out with in the future.
