### ISSUE TITLE
Usabilla passing in app CFBundleVersion rather than app CFBundleShortVersionString for "app_version"

### ISSUE THREAD

**Issue by DavidAdade** [usabilla/usabilla-u4a-ios-swift-sdk#127]
On the Usabilla Portal, the version shows as "{App Name} 1" under the app version. I just noticed the app_version parameter is taking the app build rather than version. Here is an example I tested out with changing the build number in the application to 23. I guess in our application our CFBundleShortVersionString is for example: 4.20 and we use CFBundleVersion to increment the build, if any hotfixes for example and our internal CI process

`{"v":1,"type":"app_feedback","done":true,"data":{"app_id":"removed","reachability":"WiFi","orientation":"Portrait","system":"ios","app_name":"removed","timestamp":"1548694047","app_version":"23","version":18,"custom_variables":{removed},"SDK_version":"5.0.2","battery":1,"screensize":"375 x 812","rooted":false,"total_space":62438516,"data":{"nps":10,"Comments":"Gooddd","Other":null,"Regarding":["App"],"mood":5},"lang":"en","os_version":"12.1","device":"iPhone10,6","free_space":48657756},"subtype":"form"}`

The above is what I got from looking at the header response. My question is, is there anyway to map the "app_version" parameter to CFBundleShortVersionString rather than CFBundleVersion?

**Comment by torkvell** [comment]
Hi @DavidAdade, 

Thanks for reaching out to support. 

We give the feedback item an "App Name - version" which are extracted from the app build as you say. Another variable is used to reflect the version of the device. This can be seen as "Android Version" or "iOS Version" in your Usabilla portal. 

We won't be able to change the mapping on our end, but I would like to thank you for reporting on this so we can keep track of it. I don't know of any workarounds for this, but if you're able to interfere with the mapping from our SDK and then change the string on your end, then feel free to do so. 

I hope this clarifies. If you have any other questions please let me know.

**Comment by DavidAdade** [comment]
Thanks for the update @torkvell.

**Comment by GoranLilja** [comment]
@torkvell, would you consider changing this, as the current solution isn't very user friendly. See, the build number isn't unique, but the version name is.

For example, we have a customer who sent a complaint about a bug that has already been fixed. We used the same build number (`CFBundleVersion`) for the current version and the last (build number `2`), but different version strings (`CFBundleShortVersionString`) – `2.36.2` vs. `3.0.0`.

![image (1)](https://user-images.githubusercontent.com/6507270/56890966-39843c80-6a7b-11e9-8de2-e56902481081.png)

A solution would to use `CFBundleShortVersionString` as app version instead, as that's the public facing version string, like so:
`{ … "app_version":"3.0.0" … }` rather than `{ … "app_version":"2" … }`

**Comment by torkvell** [comment]
Hi @GoranLilja ,

Thanks for adding your feedback to this feature request and for taking the time to consider how we could improve our product. I will make sure our internal ticket is updated with your information.

If there is anything else I can help with, please don’t hesitate to get back in touch.

**Comment by GoranLilja** [comment]
Thanks, @torkvell! Any updates on this? It seems like this issue is still closed. Is there another way for me to track the progress on this?

**Comment by torkvell** [comment]
Hi @GoranLilja ,

Thanks for coming back on this. This should already be fixed by our SDK team. If you still experience this issue, then please let me know.

**Comment by GoranLilja** [comment]
Hi @torkvell,

I didn't realise that this was fixed in 6.2.0. Seems to work as expected after we updated to that version. Thanks again!
