### ISSUE TITLE
Warning in debug console

### ISSUE THREAD

**Issue by kernandreas** [usabilla/usabilla-u4a-ios-swift-sdk#128]
Hello.

We have integrated the Usabilla SDK 6.0.1 as a pod in our project. During development, when the debugger runs into a breakpoint this warning is displayed in the console:
```
warning: Swift error in module Usabilla: error: cannot load underlying module for 'Usabilla'
.
Debug info from this module will be unavailable in the debugger.
```

I am just curios about the reasons for this. And I do not like warnings :)

**Comment by torkvell** [comment]
Hi @kernandreas,

If you build your project it should resolve this warning message. It seems to be a bug in Xcode: https://stackoverflow.com/questions/32673866/cocoapods-cannot-load-underlying-module-for-x

Let me know if you have any further questions

**Comment by kernandreas** [comment]
Hi @torkvell 
Did not see your initial response. The situation you described in the linked SO post does not reflect mine. I am getting warnings inside the console when running into the first breakpoint of the run session:
<img width="868" alt="bildschirmfoto 2019-02-19 um 13 08 56" src="https://user-images.githubusercontent.com/2734858/53014056-95ad5d80-3447-11e9-9ca1-fd4fa92395dd.png">

**Comment by torkvell** [comment]
Hi @kernandreas , 

Have you tried to build the project to see if the warning message disappears then?

**Comment by torkvell** [comment]
Hi @kernandreas,

Please let me know if you still need support on this matter, otherwise, we will close this ticket

**Comment by kernandreas** [comment]
I think this is more a CocoaPods or Swift issue.
Can be closed.
