### ISSUE TITLE
UsabillaFeedbackFormDelegate does not conform to protocol error in Xcode8 Swift 2.3

### ISSUE THREAD

**Issue by mkeremkeskin** [usabilla/usabilla-u4a-ios-swift-sdk#13]
Hi;

After migrating to Swift 2.3 to use Xcode 8. We're having the error below.

**does not conform to protocol "UsabillaFeedbackFormDelegate**

The methods are shown in the wiki page are put being used. 

```
    func feedbackFromLoadedIncorreclty(backupForm: UINavigationController) {
     
    }

    func feedbackFromLoadedCorreclty(form: UINavigationController, active: Bool) {

    }
```

So we couldn't figure out what is missing to conform protocol?

**Comment by gPinato** [comment]
There were two typos in the protocol, From instead of Form and Correclty instead of Correctly.

Fix those two typos in both methods and it will work.

**Comment by mkeremkeskin** [comment]
So typos have been fixed, also my problem.

Thanks for the quick answer.

**Comment by gPinato** [comment]
I just updated the wiki, I forgot to do that yesterday.
You're welcome.
