### ISSUE TITLE
Missing localisation for feedback form

### ISSUE THREAD

**Issue by kkodev** [usabilla/usabilla-u4a-ios-swift-sdk#133]
Feedback form is missing localisation for following strings:
- `Feedback`
- `Cancel`
- `Submit`

README.md as well as usa_localizable.strings are both missing keys for those.

See attached screenshot.

![Simulator Screen Shot - iPhone XR - 2019-04-05 at 11 14 11](https://user-images.githubusercontent.com/1828596/55620892-f5f82480-5793-11e9-91b0-328bddca8ea1.png)

**Comment by torkvell** [comment]
Hi @kkodev ,

You can change these strings in the Usabilla account under "Advanced Settings":
![2019-04-05 at 13 09](https://user-images.githubusercontent.com/40064170/55623712-19c36680-57a4-11e9-8b90-f4a50e0b1625.png)

![2019-04-05 at 13 07](https://user-images.githubusercontent.com/40064170/55623619-e385e700-57a3-11e9-894c-d0df5eab0875.png)

I hope this helps. Please let me know if there is anything else I can help out with.

**Comment by kkodev** [comment]
@torkvell thanks! I wasn't aware it's part of the form
