### ISSUE TITLE
Podspec version mismatch

### ISSUE THREAD

**Issue by adamprice** [usabilla/usabilla-u4a-ios-swift-sdk#134]
The supported iOS versions in the podspec on the [main Cocoapods specs repo](https://github.com/CocoaPods/Specs/blob/master/Specs/0/2/3/Usabilla/6.1.0/Usabilla.podspec.json) and the podspec in [this repo](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/blob/master/Usabilla.podspec) are different.

The main repo podspec specifies:
```json
"platforms": {
    "ios": "9.4"
},
"swift_version": "3.9"
```
but this repo specifies:
```ruby
s.platform      = :ios, "9.0"
s.swift_version = "4.0"
```

Is there a reason for this? I assume it's an error as neither iOS 9.4 or Swift 3.9 exist.

**Comment by torkvell** [comment]
Hi @adamprice,

Thank you so much for letting us know! I'll bring this further to our SDK team and make sure this gets updated if needed. I'll keep you posted.

**Comment by torkvell** [comment]
Hi @adamprice, we will update the cocoa pods so it can reflect the actual ios and swift version.  In the meantime, you can use this line in your podfile:

`pod ‘Usabilla’, :git => ’https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git', :tag => ‘v6.1.0’`

**Comment by torkvell** [comment]
Hi @adamprice,

Cocoa pods have been updated. The issue is resolved and the ticket will thereby be closed. Thank you for reporting on this and please let us know if there is anything else you encounter.
