### ISSUE TITLE
Auto Fill Forms

### ISSUE THREAD

**Issue by hyunj0** [usabilla/usabilla-u4a-ios-swift-sdk#136]
Hello,
One of the form fields we use is to collect the user's email address but given that our app already collects this info, was wondering if we could autofill that field.

**Comment by torkvell** [comment]
Hi @hyunj0,

Thanks for reaching out to support on this. I'm more than happy to clarify this for you.

We don't have any methods to prefill the form elements with values. However, you shall still be able to append this information as a custom variable. You can read more about it here: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#custom-variables

I hope this helps. Please let me know if you have any further questions.

**Comment by hyunj0** [comment]
Hi @torkvell,
Thank you for replying and letting me know about custom variables which I actually found out after opening my issue. Discussed with my team and they were good with using custom variables though it would be a neat feature to auto fill the forms...maybe in the future 🤞

**Comment by torkvell** [comment]
Hi @hyunj0 ,

Definitely a nice feature request! Thank you for taking the time to consider how we could improve our product. If you have any further questions don't hesitate to reach out!
