### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by Igor-Palaguta** [usabilla/usabilla-u4a-ios-swift-sdk#138]
carthage build fails with

```
Dependency "usabilla-u4a-ios-swift-sdk" has no shared framework schemes for any of the platforms: iOS
If you believe this to be an error, please file an issue with the maintainers at https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/new
```

Please have a look at https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/pull/137
To support prebuilt frameworks json with version mapping should be provided

**Comment by torkvell** [comment]
Hi @Igor-Palaguta,

Thank you so much for reporting on this and for also providing a pull request with your ticket. I'll discuss this with our developers and have a look at it.

I'll come back to you on this once I have any news on this.

**Comment by torkvell** [comment]
Feedback is taken as a feature/enhancement request. Ticket will now be closed. Ref: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/140
