### ISSUE TITLE
Suuport for Xcode 11 / Swift 5.1 compiler

### ISSUE THREAD

**Issue by teameh** [usabilla/usabilla-u4a-ios-swift-sdk#139]
The Xcode 11 beta that uses the Swift 5.1 compiler was released yesterday. Could you release a new version compiled with the the 5.1 compiler so we can start testing our apps with iOS 13?

Currently Usabilla is causing the following error when building with Xcode 11:

```
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler:
Pods/Usabilla/Usabilla.framework/Modules/Usabilla.swiftmodule/x86_64.swiftmodule
```

**Comment by keshcreations** [comment]
Hi @teameh,

Our iOS team made sure you can go ahead and test your apps with iOS 13:

https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.2.0-Xcode-11-beta1

Have a great day!

**Comment by teameh** [comment]
Thanks!

**Comment by Igor-Palaguta** [comment]
Can you push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks

**Comment by Igor-Palaguta** [comment]
Can you push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks

**Comment by Igor-Palaguta** [comment]
Can you push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks

**Comment by Igor-Palaguta** [comment]
Can you push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks

**Comment by Igor-Palaguta** [comment]
Can you push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks

**Comment by Igor-Palaguta** [comment]
Can you push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks

**Comment by Igor-Palaguta** [comment]
Can you push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks

**Comment by Igor-Palaguta** [comment]
Can you push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks
