### ISSUE TITLE
the view controller takes AGES to appear.. even on subsequent runs 

### ISSUE THREAD

**Issue by Daij-Djan** [usabilla/usabilla-u4a-ios-swift-sdk#14]
the view controller takes AGES to appear.. even on subsequent runs 

ages = ~ 1 second on subsequent runs, much longer depending on network for 1st run

**Comment by gPinato** [comment]
Noted.
There is some optimisation working going on to reduce loading times and memory footprint.

**Comment by gPinato** [comment]
The SDK now should be much faster, let me know if you still have performance issues.
