### ISSUE TITLE
Xcode 11 beta 2

### ISSUE THREAD

**Issue by Igor-Palaguta** [usabilla/usabilla-u4a-ios-swift-sdk#140]
Can you please push new release for Xcode 11 beta 2

Now Carthage fails with:

`
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14) and the local version is 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3).
`

Thanks

**Comment by torkvell** [comment]
Hi @Igor-Palaguta ,

Thanks for reaching out on this. We will have a look into this for you. I'll let you know once the release is ready for you.

**Comment by torkvell** [comment]
Hi @Igor-Palaguta ,

Thank you for your patience. 

You can find the release here: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

If there is anything else, please let us know.

**Comment by Igor-Palaguta** [comment]
Thank you @torkvell it was super fast

**Comment by Igor-Palaguta** [comment]
Probably you can also check this https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/138

**Comment by torkvell** [comment]
Hi again @Igor-Palaguta ,

Regarding the #138 issue: You provided a pull request for a raw GitHub link to be used instead. This has been taken as an enhancement request which will be considered in future development efforts. I'll close the ticket and would like to thank you for your valuable feedback.
