### ISSUE TITLE
Pre-populate the email address in the feedback form

### ISSUE THREAD

**Issue by cosminstirbu** [usabilla/usabilla-u4a-ios-swift-sdk#141]
Hello,

One customer of ours provided feedback to us (via Usabilla) if we could pre-populate the email address field in the feedback form.

Is there a way this can be done?

Thank you,
Cosmin

**Comment by torkvell** [comment]
Hi @cosminstirbu , 

You won't be able to pre-populate the email field, but you will be able to append the email address to the feedback programmatically by using custom variables. You can read more about this here: 
[Usabilla Custom Variable](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#custom-variables)

I hope this helps. Please let me know if you need anything else.
