### ISSUE TITLE
Xcode 11 beta 3

### ISSUE THREAD

**Issue by Igor-Palaguta** [usabilla/usabilla-u4a-ios-swift-sdk#142]
Please can you provide build for new beta Xcode 11 beta 3

**Comment by torkvell** [comment]
Hi @Igor-Palaguta ,

Thanks for reaching out on this. We currently have a build for Xcode 11 beta 1: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

I'll bring your request further to our product team for consideration.

In the interim, please let me know if there is anything else.

**Comment by Igor-Palaguta** [comment]
Unfortunately Carthage fails with same issue like here: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/140

**Comment by torkvell** [comment]
Hi @Igor-Palaguta ,

You can find the new release for Xcode 11 beta 3 here: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

I hope this helps. Please let us know if there is anything else we can assist you with.

**Comment by Igor-Palaguta** [comment]
Thank you
