### ISSUE TITLE
Xcode 10.2.1 compatability

### ISSUE THREAD

**Issue by esteluk** [usabilla/usabilla-u4a-ios-swift-sdk#143]
Hi, is there a version of the library that supports Xcode 10.2.1 / Swift 5.0.1?

**Comment by torkvell** [comment]
Hi @esteluk ,

Our latest main release v6.2.0 supports Swift 5.0.1. You can see this in the Usabilla.Framework header file:

![2019-07-17 at 17 09](https://user-images.githubusercontent.com/40064170/61387063-ac03fc00-a8b5-11e9-82d7-c737660c6dce.png)

If there is anything else you need, please let me know
