### ISSUE TITLE
Usabilla for Xcode 11 beta 4

### ISSUE THREAD

**Issue by Igor-Palaguta** [usabilla/usabilla-u4a-ios-swift-sdk#144]
Hello,

Please can you provide Usabilla for beta 4

Thanks

**Comment by muxor81** [comment]
Yes, please let us know when we can expect a new version.

**Comment by torkvell** [comment]
Hi all,

Thank you for your requests. We will look into this and try to provide a beta release that you can test with. Please give it some time. I'll let you know once it's released.

If there is anything else, please let us know.

**Comment by torkvell** [comment]
Hi @Igor-Palaguta & @muxor81,

The release for Xcode 11 beta 4 is now ready: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

Please let us know if there is anything else you need.
