### ISSUE TITLE
Usabilla for Xcode 11 Beta 5

### ISSUE THREAD

**Issue by Igor-Palaguta** [usabilla/usabilla-u4a-ios-swift-sdk#145]
Hello,

Please can you provide Usabilla for beta 5

Thanks

**Comment by torkvell** [comment]
Hi all,

Thank you for your request. We will look into this and try to provide a beta release that you can test with. Please give it some time as we have iOS developers on holiday at the moment. I'll let you know once it's released.

If there is anything else, please let us know.

**Comment by torkvell** [comment]
@Igor-Palaguta ,

The release is already done!

Let us know if you need anything else.

**Comment by Igor-Palaguta** [comment]
Thank you
