### ISSUE TITLE
App crashes when not all orientations supported

### ISSUE THREAD

**Issue by muxor81** [usabilla/usabilla-u4a-ios-swift-sdk#146]
Our app supports, when running on iPad) only both landscape modes, but no portrait mode. 
Since the change to show the camera when adding a screenshot, the app crashes when trying to add a screenshot.
Error in Xcode is: 

Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [Usabilla.UBNavigationController shouldAutorotate] is returning YES'

**Comment by andreaiori** [comment]
Hi @muxor81 , 

Thank you for reporting this issue to our attention. We are already working on it, and we expect a fix in the next release. We'll let you know as soon as we have an update. 

Don’t hesitate to let us know if you have additional questions

**Comment by keshcreations** [comment]
Hi @muxor81,

Thank you for your patience. Our new SDK containing the fix for the issue you ran into has been released. Please find the new version of our SDK here:
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

Have a great day!
