### ISSUE TITLE
Usabilla for Xcode 11 Beta 6

### ISSUE THREAD

**Issue by pabclsn** [usabilla/usabilla-u4a-ios-swift-sdk#147]
Hi guys, can we get Usabilla for Xcode 11 beta 6 please 😄

**Comment by keshcreations** [comment]
Hi @pabclsn,

Usabilla for XCode 11 Beta 6 has been released:
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.0-Xcode-11-beta6

Have a great day!
