### ISSUE TITLE
How to change font for the Feedback title in its navigation bar?

### ISSUE THREAD

**Issue by dpakthakur** [usabilla/usabilla-u4a-ios-swift-sdk#149]
Usabilla.theme.fonts.regular = UIFont(name: "Helvetica-LightOblique", size: 20)
Usabilla.theme.fonts.bold = UIFont(name: "Helvetica-Bold", size: 20)

This does not change the title font. How to change the font?

**Comment by torkvell** [comment]
Hi @dpakthakur ,

Thank you for reaching out on this. I can confirm that the title doesn't get updated (please see picture). A ticket has been created for this so we can include a fix for this in one of our next releases.

I would like to thank you for your feedback and please let us know if there is anything else.
![2019-09-06 at 17 04](https://user-images.githubusercontent.com/40064170/64438479-7961cd00-d0c8-11e9-8289-a4f9e8070c32.png)

**Comment by dpakthakur** [comment]
@torkvell Its been almost a month and there is no update on this. When will this enhancement be released?

**Comment by torkvell** [comment]
Hi @dpakthakur ,

Thank you for your patience on this. We're currently working on a fix for this. I'll keep you updated as soon as we've released a fix for this. 

If there is anything else, please let me know.

**Comment by torkvell** [comment]
Hi @dpakthakur ,

I'm happy to tell you that this issue is now fixed in our latest release: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

If there is anything else we can assist with, please let us know.

**Comment by dpakthakur** [comment]
@torkvell Unable to change font for Close and Submit button. Wanted different font for the navigation bar title and different font for Close and Submit button. Can you make this fix as well?
