### ISSUE TITLE
Please use WAY less dependencies.. aka none. the sdks and its dependencies is _huge_

### ISSUE THREAD

**Issue by Daij-Djan** [usabilla/usabilla-u4a-ios-swift-sdk#15]
Hi,
apart from the SDK itself being huge, I saw it also pulls in 3 other frameworks:
- UsabillaFeedbackForm (2.1.1):
  - Alamofire (= 3.5.0)
  - PromiseKit/CorePromise (= 3.5.1)
  - PromiseKit/UIKit (= 3.5.1)

this makes the sdk and therefore the resulting app: huge! :)

please reconsider.. 

oh and because it is all dylibs, it slows down starting noticable

**Comment by gPinato** [comment]
I understand it would be better not to have those dependencies, however those two frameworks are used extensively troughout the SDK and at the moment I don't have the resources to remove them and do their work myself.
I am already reducing the number of dependencies in the SDK (a few months ago there were 5), but these last two are too big.
I will keep in mind your request and leave this issue open, but I'm afraid it will have to stay as it is for the moment.
As soon as I get more resources it will be done.

p.s. Keep in mind that the SDK also contain full bitcode, so the the App Store should be able to shrink it's size during the publishing process. It might not be much but the size of the raw SDK is not really representative

**Comment by Daij-Djan** [comment]
thanks for the explanation and for keeping it in mind - :)

**Comment by mxcl** [comment]
Just for information: PromiseKit comes to 4MB before bitcode removal, Alamofire 9MB. Seemingly because of Swift since if you look at the sources for these things they are pretty small.

For comparison FBSDKCore is 6MB.

**Comment by gPinato** [comment]
@Daij-Djan From version 3.2.0 the SDK has no external dependencies.
