### ISSUE TITLE
Usabilla for Xcode 11 GM

### ISSUE THREAD

**Issue by teameh** [usabilla/usabilla-u4a-ios-swift-sdk#150]
Probably not necessary to file this issue, but can we get a GM release please 😄  ?

**Comment by torkvell** [comment]
Hi all,

You can find the GM release here: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

If there is anything else, please let us know.

**Comment by teameh** [comment]
Thanks!

When can we expect a production-ready release?
