### ISSUE TITLE
Getting error while updating usabilla from cart file

### ISSUE THREAD

**Issue by sreecharans** [usabilla/usabilla-u4a-ios-swift-sdk#153]
This is the error shown on terminal, please fix this ASAP
Downloading usabilla-u4a-ios-swift-sdk.framework binary at "v6.4.0"
***  Skipped installing usabilla-u4a-ios-swift-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)."

    Falling back to building from the source
*** Skipped building usabilla-u4a-ios-swift-sdk due to the error:
Dependency "usabilla-u4a-ios-swift-sdk" has no shared framework schemes for any of the platforms: iOS

**Comment by torkvell** [comment]
Hi @sreecharans ,

Does the latest release fix your problem? 

[https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases)

**Comment by sreecharans** [comment]
6.4.0 is has not fixed my problem but 6.4.1 has fixed my problem. I think there is still some problem with the stable release

**Comment by torkvell** [comment]
Hi @sreecharans,

We don't have a 6.4.1 release yet. We have included a new updated Carthage file in our latest release. I hope that fixed your build. If not, please let me know.

**Comment by torkvell** [comment]
Hi @sreecharans ,

Follow [these instructions](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application) to add carthage to your project. And add this line to your `Cartfile`: 
```yaml binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/Xcode-11/Usabilla.json"```

I hope this helps. Please let me know if there is anything else
