### ISSUE TITLE
 No shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by khalilmejjaouel** [usabilla/usabilla-u4a-ios-swift-sdk#154]
When running Chartage update i had this issue : 

Dependency "usabilla-u4a-ios-swift-sdk" has no shared framework schemes for any of the platforms: iOS

**Comment by RayAnd** [comment]
Looks like they now switch to `binary` way of distribution for Carthage.

**Comment by torkvell** [comment]
Hi @khalilmejjaouel ,

You need to link the SDK in the linked frameworks and libraries:
![2019-10-01 at 16 55](https://user-images.githubusercontent.com/40064170/65973860-4b27a100-e46c-11e9-9700-4c8d7d78486b.png)
