### ISSUE TITLE
Issue with Carthage Support in v6.4.0

### ISSUE THREAD

**Issue by RayAnd** [usabilla/usabilla-u4a-ios-swift-sdk#156]
There is a missing commas in `Usabila.json` file for Carthage support.

Please merge PR - https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/pull/155 that fixes that.

**Comment by RayAnd** [comment]
I believe that another release needed for Carthage to be able to work with this change

**Comment by RayAnd** [comment]
Would really appreciate if you guys can make patch release for this. Thanks.

**Comment by andlie** [comment]
Which branch are You using?

**Comment by RayAnd** [comment]
branch? As far as I know with Carthage and `binary` way of distributing you can't specify branch.

**Comment by RayAnd** [comment]
Error message is following:

```
Unable to parse binary-only framework JSON at https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/Usabilla.json due to error: unable to parse semantic version: expected version in line: error
```

Hope this helps

**Comment by donnywdavis** [comment]
I see this error message as well when changing our `cartfile` to use `binary "https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/Usabilla.json"`

**Comment by torkvell** [comment]
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/153

**Comment by torkvell** [comment]
Hi all,

Please follow the steps here to fix the issue with building with Carthage:
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#carthage

I hope this helps. Let me know if there is anything else.

**Comment by torkvell** [comment]
Hi everyone,

Thank you all for your patience on this. We have now released a new version which is built with Xcode 11.1: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases. Cocoapods now point to Xcode 11.1 and the Carthage link is also updated.

I would like to apologize for any inconvenience in relation to this. If there is anything else we can assist with, please let us know.
