### ISSUE TITLE
Required Compiler Version Not Properly Documented

### ISSUE THREAD

**Issue by lla01** [usabilla/usabilla-u4a-ios-swift-sdk#158]
I was unable to find in the documents what compiler version was used to create the `swiftmodule` files in your framework. This is unfortunate, because the very same compiler must be used to compile the project that intends to incorporate the framework. If the compiler versions don't match, an error like `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler` will prevent the project from building.
I don't want to guess here, so the documentation should clearly state the compiler version (e.g. by naming the Xcode verison) that is required for integrating the respective framework version.

**Comment by torkvell** [comment]
Hi @lla01 ,

Thank you for your feedback on this. I think you make a great case with your suggestion. I'll discuss this with the team to see if we can be even more clear on this. However, we always build the solution with the latest version of Xcode, meaning our latest release: v6.4.0-Xcode-11 was built with Xcode 11. 

What might be the case is that you're pointing to the incorrect version in your podfile. Please make sure it points to the latest version in this repo:
`pod 'Usabilla', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk', :tag => 'v6.4.0-Xcode-11'`

If you're using Carthage then make sure you're using this link:
[https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabailla.json](https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabailla.json)

We have also included an update Carthage framework file in the latest release.

I hope this helps. If there is anything else, please let me know.

**Comment by torkvell** [comment]
Hi @lla01 ,

To know which Swift version our SDK is built with you can inspect the Swift header file in our framework:
![2019-10-10 at 11 33](https://user-images.githubusercontent.com/40064170/66557277-e4804280-eb51-11e9-850d-f12b294ff25e.png)

We also just made a new release which is compiled with Xcode 11.1, the cocoapods and Carthage link are also updated. 

If there is anything else, please let me know.

**Comment by lla01** [comment]
> Hi @lla01 ,
> 
> To know which Swift version our SDK is built with you can inspect the Swift header file in our framework:

Ok. That's something. Thank you.
