### ISSUE TITLE
Carthage Binary for swift 5.1

### ISSUE THREAD

**Issue by cpvbruno** [usabilla/usabilla-u4a-ios-swift-sdk#159]
The current Carthage binary available was built for swift 5.0.1, when the 5.1 will be available? Also the Usabilla.json name in the repo has a type, it's written as "Usabailla"

**Comment by waqassultancheema** [comment]
I am using cocoapods. I am facing same problem.

**Comment by DaVaMa1** [comment]
in addition to the above issue, there is no actual json hosted at the url specified at the Carthage instructions:

![image](https://user-images.githubusercontent.com/34522578/65858826-2f86a280-e367-11e9-8a61-82041ae8f58d.png)

[This link is broken/does not work](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/Usabilla.json)

putting : https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabailla.json in your cartfile gets you a bit further along.

**Comment by cpvbruno** [comment]
> I am using cocoapods. I am facing same problem.

If you specify the latest release tag in Cocoapods then it works

**Comment by torkvell** [comment]
Hi all,

If you're using cocoapods please specify this in your pod file for the latest release:
`pod 'Usabilla', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk', :tag => 'v6.4.0-Xcode-11'`.

For Carthage we have a typo, workaround for now is to use:
[https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabailla.json](https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabailla.json)

We have also included an update Carthage framework file in the latest release.

I hope this helps for now. Please let us know if there is anything else.

**Comment by cpvbruno** [comment]
> Hi all,
> 
> If you're using cocoapods please specify this in your pod file for the latest release:
> `pod 'Usabilla', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk', :tag => 'v6.4.0-Xcode-11'`.
> 
> For Carthage we have a typo, workaround for now is to use:
> https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabailla.json
> 
> We have also included an update Carthage framework file in the latest release.
> 
> I hope this helps for now. Please let us know if there is anything else.

Thanks @torkvell, but why the default tag to Cocoapods is not the Xcode-11 yet?

**Comment by itsthejb** [comment]
[Latest release](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.0-Xcode-11) is _still not Xcode 11/Swift 5.1_:

```
[15:01:06]: ▸ "Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)."
[15:01:06]: ▸ Falling back to building from the source
```

**Comment by cpvbruno** [comment]
What about the Carthage for swift 5.1? @torkvell

**Comment by torkvell** [comment]
Hi @cpvbruno ,

For now, please follow the instructions here to build with Carthage:
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#carthage

I hope this helps. Please let me know if there is anything else.

**Comment by cpvbruno** [comment]
The usage of Carthage is very clear, but the current binary was made for Swift 5.0.1 not 5.1

**Comment by torkvell** [comment]
Hi @cpvbruno ,

Have you tried with this link? `binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/Xcode-11/Usabilla.json"`

Hope this helps.

**Comment by cpvbruno** [comment]
Nope, I didn't heard about any update, I'll try it asap

**Comment by joamafer** [comment]
Hi @torkvell any update on the support for CocoaPods with Swift 5.1? thanks!

**Comment by torkvell** [comment]
Hi @joamafer ,

Nothing new on this: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/159#issuecomment-537077179

**Comment by waqassultancheema** [comment]
> specify

Thank you so much. It work.

**Comment by cpvbruno** [comment]
@torkvell I have the same issue saying that the binary was built for Swift 5.0.1

**Comment by joamafer** [comment]
Hi, is there any estimation on when this will get fixed? It's the only pod affecting our app and forcing us to stay on iOS 12! We know about the workaround but we need a proper fix. Thanks.

**Comment by itsthejb** [comment]
@torkvell there appears to be some confusion about the exact issue that people are trying to communicate here. Here are complete recreation steps:

1. Install latest Xcode 11, for example from AppStore (https://apps.apple.com/us/app/xcode/id497799835?mt=12)
2. Ensure this is `xcode-select`ed: `sudo xcode-select -s /Applications/Xcode.app`
3. Verify active Swift compiler with `swift --version`:

```
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
Target: x86_64-apple-darwin18.7.0
```

3. Create a sample `Cartfile`. Either definition points to the binary release https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/download/v6.4.0-Xcode-11/Carthage.framework.zip:

```
binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/Xcode-11/Usabilla.json"
```

or:

```
github "https://github.com/usabilla/usabilla-u4a-ios-swift-sdk" "v6.4.0-Xcode-11"
```

4. Pull the framework with (for example) `carthage bootstrap --platform ios`. It will fail with:

```
*** xcodebuild output can be found in /var/folders/l1/lfsdnsf50lnf50fy75wkmcchc6dv5p/T/carthage-xcodebuild.ZuXJYW.log
*** Downloading binary-only framework Usabilla at "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/Xcode-11/Usabilla.json"
Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7).
```

If you download the binary release https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/download/v6.4.0-Xcode-11/Carthage.framework.zip directly you can inspect the header `Carthage/Build/iOS/Usabilla.framework/Headers/Usabilla-Swift.h`:

```
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.1 effective-4.1.50 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
```

This appears to report that the framework _was_ built with `Apple Swift version 5.1`. However, Carthage appears to disagree. Perhaps this is a Carthage issue instead? Alternatively, https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/download/v6.4.0-Xcode-11/Carthage.framework.zip just needs to be rebuilt with the latest compiler version.

**Comment by michaelclearscore** [comment]
Every single release we are blocked from upgrading by Usabilla. How hard is it to recompile with 5.1. Better yet open source it so this issue goes away. I cant wait till my company abandons Usabilla entirely

**Comment by joamafer** [comment]
@torkvell any update please?

**Comment by torkvell** [comment]
Hi everyone,

Thank you all for your patience on this. We have now released a new version which is built with Xcode 11.1: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases. Cocoapods now point to Xcode 11.1 and the Carthage link is also updated. 

I would like to apologize for any inconvenience in relation to this. If there is anything else, please let us know.
