### ISSUE TITLE
Missing .string keys in documentation

### ISSUE THREAD

**Issue by kernandreas** [usabilla/usabilla-u4a-ios-swift-sdk#165]
We were forced into updating to the current Usabilla Version (see https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/164) and supporting the custom implementation of an `UIImagePickerController`. There we ran into the issue that none of the custom strings are localised. Checking the current state of the documentation did not show the missing string keys.

![IMG_3378](https://user-images.githubusercontent.com/2734858/66755398-2e419380-ee98-11e9-9f2b-6483036d5181.png)

**Comment by kernandreas** [comment]
Until the problem is resolved running `plutil -p` on https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/blob/master/Usabilla.framework/usa_localizable.strings prints all the included strings.

```
plutil -p usa_localizable.strings
{
  "usa_accessibility_button_label_continue" => "Continue"
  "usa_accessibility_field_required" => "This field is required"
  "usa_accessibility_slider_value_over" => "over"
  "usa_add_button_title" => "Add"
  "usa_add_title" => "Add photo"
  "usa_back_button_library_title" => "Library"
  "usa_back_button_title" => "Back"
  "usa_camera_error_description" => "Allowing access lets you take photos to add to your feedback."
  "usa_camera_error_title" => "No access to camera"
  "usa_camera_navbar_left_button" => "Cancel"
  "usa_camera_settings_title" => "Allow access to camera"
  "usa_choose_from_options" => "Choose from %d options"
  "usa_delete_screenshot" => "delete screenshot"
  "usa_done_button_title" => "Done"
  "usa_edit_screenshot" => "change screenshot"
  "usa_edit_title" => "Edit"
  "usa_form_close_button" => "Close"
  "usa_form_continue_button" => "Next"
  "usa_form_required_field_error" => "Please check this field"
  "usa_library_error_description" => "Allowing access lets you select a photo to add to your feedback."
  "usa_library_error_title" => "No access to library"
  "usa_library_settings_title" => "Allow access to library"
  "usa_library_title" => "Library"
  "usa_mood_dislike" => "I don't like it"
  "usa_mood_five_star" => "5 stars"
  "usa_mood_four_star" => "4 stars"
  "usa_mood_hate" => "I really don't like it"
  "usa_mood_like" => "I like it"
  "usa_mood_love" => "I love it"
  "usa_mood_neutral" => "I feel neutral"
  "usa_mood_one_star" => "1 star"
  "usa_mood_select_a_rating_out_of" => "select a rating out of"
  "usa_mood_three_star" => "3 stars"
  "usa_mood_two_star" => "2 stars"
  "usa_multiple_options_possible" => "Multiple options possible"
  "usa_one_option_possible" => "One option possible"
  "usa_powered_by_usabilla" => "powered by usabilla"
  "usa_retake_button_title" => "Retake"
  "usa_screenshot_placeholder" => "Add a photo"
  "usa_selected" => "selected"
  "usa_tap_to_visit_usabilla" => "tap to visit usabilla.com"
  "usa_unselected" => "unselected"
}
```

**Comment by andreaiori** [comment]
Hi @kernandreas, thank you for reaching out. The issue is related to the Localization string file. Since the strings you mentioned are not defined in our SDK, you're facing an error. 

Are you able to share with us how you have implemented those strings?

**Comment by kernandreas** [comment]
I am not sure what you mean with
`Since the strings you mentioned are not defined in our SDK, you're facing an error.`

This strings are part of the Usabilla SDK. They are also part of the `usa_localizable.strings` But they are missing in the documentation https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#string-file-contents

**Comment by davidmigloz** [comment]
It would be nice if you align the keys between Android and iOS SDKs...
https://github.com/usabilla/usabilla-u4a-android-sdk#localization

**Comment by torkvell** [comment]
Hi all,

We've now done an update to our documentation on this. Thank you for reporting and please let us know if there is anything else you need.

**Comment by Goseong** [comment]
It would help us if the naming of the strings are aligned between both platforms. 

Since the 6.0 release on Android it states in the release notes that the app naming has become uniform but across platforms it is now inconsistent.

**Comment by torkvell** [comment]
Hi @Goseong ,

We'll map out the discrepancies between the localization strings and make sure they're aligned between the platforms. 

I hope this helps. If there is anything else, please let me know.
