### ISSUE TITLE
CRASH: Calling static UsabillaService.set(customValue:forKey:) causes crash

### ISSUE THREAD

**Issue by farhad-ris** [usabilla/usabilla-u4a-ios-swift-sdk#166]
This library causes crash on: 
```
9   Usabilla                       	 0x0000000101d5c40c _hidden#12159_ (__hidden#12193_:0)
10  Usabilla                       	 0x0000000101d5af48 static Usabilla.customVariables.setter (__hidden#835_:0)
```

**Comment by classyklaas** [comment]
Hi @farhad-ris, thank you for contacting us and bringing this to our attention.

I had an internal meeting about this and I've got good news: we're working on a fix as we speak. I'll contact you again as soon as I have news.

**Comment by classyklaas** [comment]
Hi @farhad-ris, would you mind sharing the specific example that causes the crash? So, basically, what are you trying to set on the custom variables? And which Xcode-version and which SDK-version are you using?

I hope to hear from you.  If you have any other questions, feel free to contact us.

**Comment by torkvell** [comment]
Hi @farhad-ris ,

Please let us know if this is still an issue on your end so we can assist further.
