### ISSUE TITLE
SDK does not support Module Stability

### ISSUE THREAD

**Issue by kernandreas** [usabilla/usabilla-u4a-ios-swift-sdk#167]
When using the current Xcode 11.2 beta we are not able to compile our project because of following error
> Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.1 compiler
> /Pods/Usabilla/Usabilla.framework/Modules/Usabilla.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

Since Swift 5.1 finally supports Module Stability this should not be the case if all binary frameworks are compiled correctly. This seems not to be the case for Usabilla.

Please make sure to set the `BUILD_LIBRARY_FOR_DISTRIBUTION` in the build settings as described in https://developer.apple.com/videos/play/wwdc2019/416/

**Comment by torkvell** [comment]
Hi @kernandreas ,

Thank you for reporting on this. We'll have a look into this Module Stability too see if this is something our customers could benefit from. We also just released a build for you, for Xcode 11.2 beta: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

If there is anything else, please let me know.

**Comment by kernandreas** [comment]
Thank you for the answer.
I think a lot of your customers would welcome to have binary framework with module stability in their app project. So not all of the team members need to jump at the same moment to the same Swift compiler version
