### ISSUE TITLE
Unable to present form as .fullscreen

### ISSUE THREAD

**Issue by geoffclifton** [usabilla/usabilla-u4a-ios-swift-sdk#168]
Hello,

We have started using Usabilla 6.4.2 with Xcode 11.1.

We would like to present the form in a `.fullscreen` manner, but using our previous approach which matches the approach shown in the readme results in the form being displayed as a `.formsheet`.

```swift
public func formDidLoad(form: UINavigationController) {
        form.modalPresentationStyle = .fullScreen
        present(form, animated: true, completion: nil)
}
```

Currently, the only way I have found to present it in `.fullscreen` style, is to create a new UINavigationController with the content of the one passed by the Usabilla delegate method.
```swift
public func formDidLoad(form: UINavigationController) {        
        let nav = UINavigationController(rootViewController: form.absoluteTopViewController)
        nav.modalPresentationStyle = .fullScreen
        present(nav, animated: true, completion: nil)
}
```

I'm wondering if there is something about the UINavigationController passed by the delegate method which prevents it form being displayed as `.fullscreen`?

**Comment by geoffclifton** [comment]
Hi Usabilla team.
Any updates on this issue or initial thoughts?

**Comment by torkvell** [comment]
Hi @geoffclifton ,

It's a design choice to have the forms shown as a popup on iPad and fullscreen on iPhone. Unfortunately, there is no way to circumvent that in code. While I can't make any promises, I'm going to share your thoughts with our product/design team for consideration in future developments. Given that iOS 13 has provided a lot of changes to UI, we could discuss whether it should he customers choice to have iPad fullscreen or not. 

If there is anything else, please let us know.

**Comment by geoffclifton** [comment]
@torkvell - I don't think this is a feature request. The readme for Usabilla actually includes instructions on how to present the form in `.fullscreen` mode on iPad. Following these instructions using v6.4.2 does not work. I think this is a bug.

<img width="929" alt="Screen Shot 2019-11-04 at 7 04 19 AM" src="https://user-images.githubusercontent.com/6059255/68119778-96046080-fed1-11e9-8e1c-886a3271f6cd.png">

**Comment by geoffclifton** [comment]
@torkvell - Any follow up on this?
This is not a new feature request and is in fact a bug.

You outline how to present this as fullscreen on iPad in your readme and those steps no longer work on iOS 13.

**Comment by torkvell** [comment]
Hi @geoffclifton ,

Thanks for clarifying on this. I've created a ticket for this so our SDK team can investigate further on it. You're totally right in that this is documented in the readme. However, given that iOS 13 has provided a lot of changes to UI, we could discuss whether it should be customers choice to have iPad fullscreen or not. In the interim, please let me know if there is anything else.

**Comment by keshcreations** [comment]
Hi @geoffclifton,

Thanks again for bringing this up. After further investigation, I can confirm that this is a bug on our end. We've also tested the solution provided by you and it works like a charm. Thanks for providing a fix as well. We are going to dive into this to investigate what is causing the implementation as we have intended to fail. Also, we'll be looking into a solution where no additional UINavigationController is required.

I'll post updates in this ticket as our investigation progresses.

**Comment by keshcreations** [comment]
Hi @geoffclifton,

We have released a [new version of our iOS SDK](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases) where we have addressed the issue you brought up. Please try it out and share any feedback you might have on it.

Have a great day!
