### ISSUE TITLE
Please use the  optimistic operator in the requirements

### ISSUE THREAD

**Issue by bnjamin** [usabilla/usabilla-u4a-ios-swift-sdk#17]
As the title says please use the optimistic operator for the podspec requirements.

So instead of:
 
`s.dependency 'Alamofire', '3.5.0'`

it would be:

`s.dependency 'Alamofire', '~> 3.5.0'`

This way you can depend on bugfixes to the dependencies and aren't forced to use the exact pod versions, that is in the requirements.

At the moment AlamoFire has been updated to the 3.5.1, which fixes a memory leak issue.

Thanks.

**Comment by gPinato** [comment]
It's a legit request. Will be done from next release
