### ISSUE TITLE
CRASH: Usabilla causes an app crash when two campaigns are triggered at once. 

### ISSUE THREAD

**Issue by eebart** [usabilla/usabilla-u4a-ios-swift-sdk#170]
UBInfo: Event "[EventA]" sent!
UBInfo: Event "[EventB]" sent!
UBInfo: Campaign [CampaignID1] has been triggered!
UBInfo: Campaign [CampaignID2] has been triggered!

```
Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)
#8	0x00000001a6db1e84 in -[UIView(Hierarchy) removeFromSuperview] ()
#9	0x0000000102fd6e28 in closure #1 in RatingControl.reload() [inlined] at /Users/aliebl/Usabilla/usabilla-u4a-ios-internal-testing/usabilla-u4a-ios-swift/Usabilla/Views/Components/RatingControl.swift:153
#10	0x0000000102fd6e1c in thunk for @callee_guaranteed (@guaranteed UIView) -> (@error @owned Error) [inlined] ()
#11	0x0000000102fd6e1c in specialized Sequence.forEach(_:) [inlined] ()
#12	0x0000000102fd6e18 in RatingControl.reload() at /Users/aliebl/Usabilla/usabilla-u4a-ios-internal-testing/usabilla-u4a-ios-swift/Usabilla/Views/Components/RatingControl.swift:153
#13	0x0000000102fd6b74 in RatingControl.layoutSubviews() [inlined] at /Users/aliebl/Usabilla/usabilla-u4a-ios-internal-testing/usabilla-u4a-ios-swift/Usabilla/Views/Components/RatingControl.swift:141
#14	0x0000000102fd6b3c in @objc RatingControl.layoutSubviews() at /Users/aliebl/Usabilla/usabilla-u4a-ios-internal-testing/usabilla-u4a-ios-swift/<compiler-generated>:139
#15	0x0000000102f4d244 in MoodComponent.layoutSubviews() [inlined] at /Users/aliebl/Usabilla/usabilla-u4a-ios-internal-testing/usabilla-u4a-ios-swift/Usabilla/Views/Components/MoodComponent.swift:54
#16	0x0000000102f4d200 in @objc MoodComponent.layoutSubviews() at /Users/aliebl/Usabilla/usabilla-u4a-ios-internal-testing/usabilla-u4a-ios-swift/<compiler-generated>:52
#17	0x00000001a6dc9270 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
```

**Comment by andreaiori** [comment]
Hi @eebart, 

Thank you for your message and for bringing the issue regarding trigger 2 campaigns at once to our attention.

I have reported this bug to our Product team on a ticket. My apologies for any inconvenience caused, but as soon as I have an update I'll make sure to get in touch.

Before continuing with the investigation, may I ask you on which specific case you would trigger 2 campaigns at the same time? This would help us understand the use case.

If you have any other questions in the meantime, feel free to contact us.

**Comment by keshcreations** [comment]
Hi @eebart,

I'm getting back to you to let you know that the issue you were running into has been fixed in the [latest release of our SDK](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases). If you haven't already, please update to the latest version so you can enjoy the fixes we have implemented.

Have a great day!
