### ISSUE TITLE
Support for Dark mode

### ISSUE THREAD

**Issue by TukkerAtKLM** [usabilla/usabilla-u4a-ios-swift-sdk#171]
Since iOS 13 dark mode is available for apps. Please add dark mode support for usabilla.

**Comment by torkvell** [comment]
Hi @TukkerAtKLM ,

Thanks for reaching out to us and for taking the time to consider how we could improve our product. I think you make a great case with your suggestion.

We might look into implementing this, but it's not on our top priority list. What you can do for now is creating two different forms with two different color schemes. Then based on the color mode the user is on, you can then trigger the corresponding form. 

If there is anything else I can help with, please don’t hesitate to get back in touch.
