### ISSUE TITLE
Duplicated dsym file

### ISSUE THREAD

**Issue by joamafer** [usabilla/usabilla-u4a-ios-swift-sdk#173]
We are having an issue with the Usabilla 6.4.3 version:

error: Multiple commands produce '/Users/vagrant/Library/Developer/Xcode/DerivedData/.../PlugIns/Usabilla.framework.dSYM':
    duplicate output file '/Users/vagrant/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/....app/PlugIns/Usabilla.framework.dSYM' on task: PhaseScriptExecution [CP] Embed Pods Frameworks /Users/vagrant/Library/Developer/Xcode/DerivedData/.../Build/Intermediates.noindex/.../Debug-iphonesimulator/....build/Script-3962D1B4D9634D65047F3499.sh (in target '...' from project '...')

After looking into it, we believe the Usabilla pod adds these two lines to the Pods-xxx-frameworks.sh

install_dsym "${PODS_ROOT}/Usabilla/Usabilla.framework.dSYM"

So it generates a duplicated file.

**Comment by michaelclearscore** [comment]
Im having to same issue. Out of 15 dependencies, there is only one framework that breaks on every Xcode. Truly outstanding display of incompetence 👏 👏 👏

**Comment by torkvell** [comment]
Hi @joamafer and @michaelclearscore ,

I'm very sorry to hear you're experiencing this issue. I've done some tests on my end and I had no issues in updating the pod file and to build and run my project. Feedback is also successfully sent to the Usabilla Dashboard. You can find a working example here: [https://drive.google.com/file/d/1dUxsjvt1B_b7PJnF8jQQGGzPaIl_0Dgu/view?usp=sharing](https://drive.google.com/file/d/1dUxsjvt1B_b7PJnF8jQQGGzPaIl_0Dgu/view?usp=sharing)

It's a very basic app, as I'm not an iOS developer. However, I hope this enables you in moving forward and fixing the issue you have on your end. 

Let me know if you need any further assistance.

**Comment by keshcreations** [comment]
Hi @joamafer,

I'm getting back in touch with you because I'd like to know whether you have the opportunity to check the sample app provided by my colleague and whether it has helped you?

**Comment by lennardtastic** [comment]
Closing this issue due to it being stale
