### ISSUE TITLE
Label for radio button component cut off 

### ISSUE THREAD

**Issue by Goseong** [usabilla/usabilla-u4a-ios-swift-sdk#176]
Hi, we are running a survey with radio buttons, unfortunately the 5th item on the list only displays the label of the first line. 

{"id":"612b99c1-e424-41d0-9472-66b9463b0920","name":"[iOS][Android] Pricing questionnaire"}

Seen on iPhone 7 iOS 13.1.3

![IMG_7947](https://user-images.githubusercontent.com/25725559/70058003-6afb5280-15de-11ea-8877-466b2e8d10b5.PNG)

**Comment by torkvell** [comment]
Hi @Goseong ,

Thanks for reaching out on this. I've now done some tests on this and I'm not able to reproduce this on my end. I've tested with your form **[iOS][Android] Pricing questionnaire** on an iPhone 7 iOS 13.2.2 (17B102):
![2019-12-04 at 17 09](https://user-images.githubusercontent.com/40064170/70159224-dca7cf00-16b8-11ea-934c-5672dc742a5f.png)

I've also done some tests on other devices ranging from iPhone 5 to X and haven't been able to reproduce it on them either. If you have any insight on how to reproduce this, then please let us know.

**Comment by Goseong** [comment]
Hi Toralf, thanks for checking.

We changed the order of the questionnaire to work around the issue. I will
create a duplicate survey for you to reproduce.

**Comment by Goseong** [comment]
I can confirm that is seems to be specifically OS related. Thanks for your help!
