### ISSUE TITLE
Strange behaviour on Usabilla preview app

### ISSUE THREAD

**Issue by Goseong** [usabilla/usabilla-u4a-ios-swift-sdk#177]
We noticed that the preview app often displays the campaign as shown in the screenshot, when return the app from the background.

Seen on iPhone 7, iPhone 7 Plus - iOS 13.2.3

![IMG_8614](https://user-images.githubusercontent.com/25725559/70057381-55d1f400-15dd-11ea-8957-661f80dc5bd7.PNG)

**Comment by torkvell** [comment]
Hi @Goseong ,

We won't spend development efforts on the preview app in this case. The functionality works across almost all devices and the use-case is very specific here. However, thank you for reporting. If there is anything else we can assist with, please let us know.

**Comment by Goseong** [comment]
I understand, if it’s not coming from the SDK. Thanks for checking.
