### ISSUE TITLE
6.4.4 missing from Usabilla.json

### ISSUE THREAD

**Issue by itsthejb** [usabilla/usabilla-u4a-ios-swift-sdk#178]
Hi there,

https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/commit/64f3c105deb280edad7a50f4f0f74e97ae23b3b6 does not update https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/blob/master/Usabilla.json with an entry for 6.4.4, even though the target zip exists at https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/download/v6.4.4/Carthage.framework.zip

Please could you add this

Many thanks

**Comment by torkvell** [comment]
Hi @itsthejb ,

Thanks for letting us know. We'll have a look into this today.

**Comment by keshcreations** [comment]
Hi @itsthejb,

Just a heads up here, the JSON has been updated a couple of weeks ago and this should have fixed the issue you were running into.

Have a great day!
