### ISSUE TITLE
Trouble updating to version 6.4.4

### ISSUE THREAD

**Issue by donnywdavis** [usabilla/usabilla-u4a-ios-swift-sdk#179]
We currently have version 6.4.3 and are running Xcode 11.3. I am trying to update to version 6.4.4, however, I am getting an error with Carthage regarding the swift version.

`Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).`

I thought this was not an issue anymore after version 6.4.3.

I have tried to completely remove Usabilla from our project to see if a fresh install of it would work and have also tried to delete the local Carthage cache. Neither of those helped and I still get the error.

Am I missing something super obvious here? 🤔

**Comment by michel-moreau** [comment]
same here.

**Comment by JuLink** [comment]
Same

**Comment by waxym** [comment]
Same issue here, can't move to latest Xcode as required by dev team :(

**Comment by keshcreations** [comment]
Hi @donnywdavis @michel-moreau @JuLink @waxym,

You all aren't missing something obvious. Upon further investigation, we've come to the conclusion that this specific issue does require a new version of our SDK. Our team is working on this as we speak and I will be back with an update once it's ready for use.

**Comment by leatherTramp** [comment]
Same here

**Comment by Tubalcaan** [comment]
same here

**Comment by elisabelgenereux** [comment]
same for us

**Comment by keshcreations** [comment]
Hi all,

I'm happy to share with you all that a new version of our SDK has been released. This version is compatible with XCode 11.3.1 and can be found [here](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.4-Xcode-11.3.1).

Have a great day!

**Comment by hyunj0** [comment]
@keshcreations, still getting `Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).` when running `carthage update`.

This is what I have in my Cartfile `binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/v6.4.4-Xcode-11.3.1/Usabilla.json"`

Did I miss something?

**Comment by keshcreations** [comment]
Hi @hyunj0,

Could you run a quick test for us so we can understand what is happening? Could you delete the `org.carthage.CarthageKit`file? This file is located in the `Caches` folder.

After deleting the file, could you please run:
`carthage update --platform iOS`

Please let us know what the outcome of this is for you.

**Comment by hyunj0** [comment]
Hi @keshcreations,

After deleting the `org.carthage.CarthageKit` file, it appears to download the framework. But I get two issues: 

1. Subsequent frameworks don't get downloaded getting `Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).` These frameworks were being downloaded before though.
2. When I try to build, I get `No such module 'Usabilla'`.

**Comment by keshcreations** [comment]
Hi @hyunj0,

Thanks for following the steps provided and getting back to me.

Can you do the following now:
- Download [this](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/download/v6.4.4-Xcode-11.3.1/Carthage.framework.zip) `.zip` file
- Replace `Usabilla.framework` with the 6.4.4 version of our SDK that is built on XCode 11.3.1

Please let us know whether this helps you.

**Comment by hyunj0** [comment]
Hi @keshcreations,

Adding the zip works, successfully building the project on my local development machine.

But, we have a build service that would automate building the dependencies via Carthage. Hence, we don't manually add frameworks or check in `Carthage/` changes into git. We only update our `Cartfile` and `Cartfile.resolved` and let the build service take care of the rest.

For now, I am using `Xcode 11.0` to build the framework, using:
```
Cartfile
binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/Xcode-11/Usabilla.json"
```
```
Cartfile.resolved
binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/Xcode-11/Usabilla.json" "6.4.0"
```

Given that the latest Usabilla version is `v6.4.4`. and latest Xcode is `11.3.1`, I would like to build and distribute on the latest. Hence, would appreciate if you could look into the Carthage error and resolve:
```
Error
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).
```

**Comment by keshcreations** [comment]
Hi @hyunj0,

Thank you for the additional information.

We are currently working on a new version of our SDK and in this new version, we will make sure that this error will be resolved. Please keep an eye on our release page to be notified of the new release.
