### ISSUE TITLE
Not all localization keys are documented

### ISSUE THREAD

**Issue by bnjamin** [usabilla/usabilla-u4a-ios-swift-sdk#18]
I've with success used my own localization file as documented here: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/wiki/Localization

However I haven't been able to find the key for the "Submit" string in the top right corner of the feedback screen nor the key for "Please check the fields marked with *".

Thanks

**Comment by gPinato** [comment]
Those fields are set in the web interface, the same place where you build the form, in the advanced settings panel.

It's a little bit inconsistent, but we're trying to fix it by moving all the copy settings in the web interface.
