### ISSUE TITLE
formDidLoad gives no indication of which form was loaded.

### ISSUE THREAD

**Issue by lukecharman** [usabilla/usabilla-u4a-ios-swift-sdk#180]
I'm coming to add my second Usabilla survey form to my app, presented in a different place to the first one.

I call `Usabilla.loadFeedbackForm` with the right form ID, which then calls back to the delegate `formDidLoad(form: UINavigationController)` – trouble is, I now have no idea which form was loaded or any context with which to continue my journey.

I have a single `UsabillaService` in my app which is the delegate of the Usabilla SDK (to prevent Usabilla bleeding out into the rest of my app). Without an ugly solution like using a temporary variable to store the requested ID, what formal approach is recommended by the Usabilla team here?

For clarity, I am requesting the form ID be included in the delegate callback alongside `formDidLoad` and `formDidFailLoading`.

**Comment by keshcreations** [comment]
Hi @lukecharman,

To check what Form was triggered, I'd recommend using our [formDidClose method](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#feedback-submission-callback). This method will return the FormID of the Form when it is closed. This should help you identify what Form is being triggered.

I hope this helps. If you have any other questions, feel free to get back in touch.
