### ISSUE TITLE
Carthage - Dependency "usabilla-u4a-ios-swift-sdk" has no shared framework schemes for any of the platforms: iOS, watchOS

### ISSUE THREAD

**Issue by soledue** [usabilla/usabilla-u4a-ios-swift-sdk#181]

**Comment by keshcreations** [comment]
Hi @soledue,

Our team is currently working on a new version of the iOS SDK that contains the fix for the issue you're running into. We also have a more immediate solution that is more of a work-around that is explained in [this ticket](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/179). Once the new version of the SDK has been released, I'll get back to you all with an update.

**Comment by keshcreations** [comment]
Hi @soledue,

Please disregard my earlier message (which I've deleted just now). It was incorrect and not related to the issue you're experiencing. I will discuss this issue with our team and provide you with an update on this.

**Comment by keshcreations** [comment]
Hi @soledue,

Could you try linking the SDK in the linked frameworks and libraries:
![github](https://user-images.githubusercontent.com/20249226/74150021-67510100-4c09-11ea-8cfa-0fc8d2a4770e.png)

Please let me know if this helps.

**Comment by keshcreations** [comment]
Hi @soledue,

Were you able to follow the steps provided and if so, could you share the outcome of it?

I'm looking forward to your response.

**Comment by soledue** [comment]
hi, sorry for late answer. I'm not use pod but Carthage 
<img width="1042" alt="Schermata 2020-02-26 alle 17 42 21" src="https://user-images.githubusercontent.com/5681077/75366685-6aade300-58bf-11ea-9250-4f94ee8c0f07.png">

**Comment by lennardtastic** [comment]
Hi @soledue 

Thank you for your message.

My apologies for the delayed response. Could you maybe try clearing your Carthage cache and use our latest build? Let me know how it goes.

Kind regard,

Lennard

**Comment by lennardtastic** [comment]
Closing this issue due to it being stale.

Sidenote: If you're using Carthage make sure to update using the lastest Carthage specific SDK build found on https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.7-Xcode-11.4.1
