### ISSUE TITLE
Considering an update anytime soon? Current version release last year still does not support current Xcode 11.3.1 with carthage

### ISSUE THREAD

**Issue by Nonnus** [usabilla/usabilla-u4a-ios-swift-sdk#184]
For years you keep not supporting new Xcode releases in timeline manner, but this is getting ridiculous now...

Your last release was over 2 months ago in December 18! 
It does not even support the current version of Xcode (11.3.1) also released one month ago! for some unknown reason you have a pre release version to support Xcode 11.3.1 but decided to never release it (not to mention it does not really support Xcode 11.3.1 with Carthage...)

Is there really no one around that finds this totally unacceptable other than the client devs that need to deal with your incredibly poorly supported sdk until they convince their companies to just drop your (paid) service for good?

I am sorry if I sound rude but me and many others have suffered / mentioned / complained about the same issue several times and you dont seem to care at all, in all honesty you are knowingdly making our work much harder than it should be by providing such a poor level of support

Needless to say this issue will also be reported thru my company official support channels

```
*** Downloading binary-only framework Usabilla at "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabilla.json"
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).
```

```
*** Downloading binary-only framework Usabilla at "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/Xcode-11.3.1/Usabilla.json"
Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).
```

**Comment by keshcreations** [comment]
Hi @Nonnus,

Our team was actually in the process of releasing the latest version of our SDK and the release was finalized yesterday. Please find the latest version of our iOS SDK [here](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases).

Have a great day!
