### ISSUE TITLE
where is the Xcode 11.4 support?

### ISSUE THREAD

**Issue by Nonnus** [usabilla/usabilla-u4a-ios-swift-sdk#187]
this keeps happening with every single release, it is truly unbelievable

**Comment by lennardtastic** [comment]
Hi @Nonnus,

Thank you for reaching out. 

I'm very sorry for the delay in the release. As you can probably imagine we are, just like most businesses in the Netherlands, affected by the new measures imposed by the Dutch government to battle the COVID-19 virus. We're working as fast as we can on getting a new release out while also getting used to having a fully remote team. 

Thank you for your understanding.

Kind regard,

Lennard

**Comment by Nonnus** [comment]
@lennardtastic while I can understand the current global situation, you are not alone, we are also remote and dealing with the new reality...
However this problem of your is not new at all as you systematically fail to support new versions of Xcode on *every single release*
I dont want to make your life harder than it needs to be but you sure keep making mine harder than it should be, especially as a paying customer of your paid service

And once again, despite my report, despite your response, the final version of Xcode was release 19 hours ago and once again you are not ready to support it...
<img width="1213" alt="Screenshot 2020-03-24 at 20 17 29" src="https://user-images.githubusercontent.com/54864/77467842-f5c1c080-6e0c-11ea-8d0d-996b0925d226.png">

**Comment by lennardtastic** [comment]
Hi @Nonnus,

Thank you for reaching out.

I've asked our team to create a build and I've asked your Usabilla Customer Success Manager to get in touch to see if we can schedule a quick call. During the call, I would like to discuss how we can improve the process.
The majority of our users do not use the pre-releases and generally take some time before updating. So I would really like to understand your specific build process and your expectations when it comes down to new releases.

Based on the outcomes of the call we can adjust our release process to better hopefully better accommodate your specific needs.

Kind regards,
Lennard

**Comment by Nonnus** [comment]
@lennardtastic hey, I am happy to provide any feedback you need
your team can reach me internally at any time, I work for hellofresh and I am the iOS team lead (Nuno Pereira) so I am quite easy to reach ;)

Just to be clear: I am reporting about lack of support for a released Xcode version, not a pre-release one, notice how the new version is already available on the App Store

**Comment by Nonnus** [comment]
thanks for https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.6

in any case feel free to reach me if I can help in way to avoid the problem

**Comment by lennardtastic** [comment]
@Nonnus 

Will do, I'm having our CSM reach out to discuss how we can avoid the problem in the future.

Kind regards

Lennard

**Comment by Nonnus** [comment]
@lennardtastic fyi, I was never contacted by anyone
once again, new Xcode version is out (11.5)and Usabilla is the only 3rd party tool that does not support it...
I can also see that despite 11.5 being in beta for quite some time there is no `Xcode-11.5` branch to provide support to it, it makes no sense how u keep repeating the same issue over and over again on every new release
