### ISSUE TITLE
Framework with support for Module Stability 

### ISSUE THREAD

**Issue by lammertw** [usabilla/usabilla-u4a-ios-swift-sdk#188]
The framework really should support Module Stability se we don't need to update (and wait) for a new release with each new version of Swift/Xcode.

See https://www.donnywals.com/what-is-module-stability-in-swift-and-why-should-you-care/

**Comment by lennardtastic** [comment]
Hi @lammertw 

Thank you for reaching out.

Our framework does support Module Stability. If you, for example, use CocoaPods you'll get full Module Stability and you don't need to wait for a new release with each new version of Swift/Xcode.

Could you maybe elaborate a bit more around the setup that you're using and the problem your experiencing?

Kind regards,
Lennard

**Comment by lammertw** [comment]
Thanks for your reply. I was under the impression it didn't have it yet by looking at an older issue there it was asked for which was closed without adding it and I also couldn't find it in the release notes. But good to hear that the latest version has it.
