### ISSUE TITLE
Missing Carthage release version for xCode 11.4.1

### ISSUE THREAD

**Issue by emilianoalvarez91** [usabilla/usabilla-u4a-ios-swift-sdk#191]
Incompatible Swift version - framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51).

**Comment by lennardtastic** [comment]
Hi @emilianoalvarez91 

The Development Team is working on creating a new release that will also add support for the latest Xcode build in combination with Carthage.

Kind regards,
Lennard

**Comment by ggupta4-harman** [comment]
hi @lennardtastic is the release planned soon for this issue resolution? Eagerly waiting as our build pipleline's for several products are continuously failing on Nevercode 😞

**Comment by lennardtastic** [comment]
@ggupta4-harman 

We're aiming to have a new release ready today.

Kind regards,
Lennard

**Comment by lennardtastic** [comment]
Hi All,

Please see the following release for Xcode 11.4.1 with Carthage support.
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.7-Xcode-11.4.1

Do keep in mind that you need this specific release for Xcode 11.4.1 when updating with Carthage.

Kind regards,
Lennard
