### ISSUE TITLE
FeedbackResult .rating = nil

### ISSUE THREAD

**Issue by lanouari-Mar1** [usabilla/usabilla-u4a-ios-swift-sdk#193]
campaignDidClose is called in the delegate method but result.rating is nil. And for passive compaigns the formDidClose and willClose are not called.

**Comment by lennardtastic** [comment]
Hi @lanouari-Mar1 

Thank for reaching out.

The result you'll get back from the campaignDidClose is dependent on the availability of a rating form-element within your Usabilla form. If you do not have a rating form-element present in your Usabilla form a nil will be returned.

For the formDidClose and formWillClose part of your question. I suspect you chose to handle the dismissal of the form yourself. If you handle the dismissal of the form yourself the delegate method formDidClose will not be called and you'll need to call the formWillClose yourself. See our README.md for more information about this. https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#handle-manual-dismiss

I hope this helps. I'll close the ticket for now.

Kind regards,
Lennard
