### ISSUE TITLE
Labels overlapping in Picture Preview

### ISSUE THREAD

**Issue by nihilias** [usabilla/usabilla-u4a-ios-swift-sdk#194]
Hello 👋 

we recently discovered that when opening a feedback form and after adding a picture with the camera, the labels on the preview screen are overlapping (see picture).

### Steps to reproduce

1. Open a feedback form
2. Use option "add picture"
3. Take a picture
4. See preview

### Technical information

Device: Apple iPhone 5C (iOS 10.3.3)
Reproducible: always (on real devices)

### Example

![2020-02-18 14 36 42](https://user-images.githubusercontent.com/11645567/82297247-a930d680-99b2-11ea-8c2c-d4c12a1d7f50.png)
oh

**Comment by lennardtastic** [comment]
Hi There,

Thank you for reaching out. 

The labels within the SDK are set either via the form-setup found on app.usabilla.com or via de localization file which can be initialized in the SDK (see https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#string-file-contents).

For the label that you are referring to (see down below). There is only space for 1 line of text, which is anchored to the left. There are various reasons why we keep this on 1 line. Regardless it's recommended to keep the amount of character limited to ensure the best compatibility with the different devices and font-sizes.

I'm not native in German, but I would recommend changing the copy slightly to make it work within the set UI constraints. Depending on the length of the other strings and the font-size you should have around 10 to 15 characters available. Changing `erneut aufnehmen` to something like `wiederholen` might solve the problem that you're experiencing (I might have this wrong though 😅 my German is not that great ). 

You can change the string via the localization file, you will want to change the string found down below.
`// Screenshot annotation`
`"usa_retake_button_title" = "Retake";`

I hope this helps.

Best Regards,
Lennard
