### ISSUE TITLE
Xcode 11.5 carthage support?

### ISSUE THREAD

**Issue by Nonnus** [usabilla/usabilla-u4a-ios-swift-sdk#196]
its just me, again... 
days after a Xcode release, asking for you to support it so we can update our app...

edit: apparently now we have "support" for carthage, but it is not working...
screenshot on my last comment

**Comment by Nonnus** [comment]
wow, you dont even care to reply anymore, great work, really professional!

**Comment by lennardtastic** [comment]
@Nonnus Thanks for reaching out.

I think your issue got lost somewhere in our support ticketing system which likely caused no one to respond yet. My apologies for that, I'll check with our Support Team what exactly went wrong. 

With regard to the Xcode 11.5 support. We released a new version of our SDK with some fixes and support for Xcode 11.5 on the 22nd of May. You can find the release on https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.7-Xcode-11.5 
If I remember correctly you're using Carthage, in that case you'll need to make sure to use the correct link mentioned in the release notes to fetch the SDK. 

I hope this helps.

Best Regards 
Lennard

**Comment by Nonnus** [comment]
thanks @lennardtastic 
I was missing our usual exchange and though u did not love me anymore ;)
I did notice the new release (hence why I closed the issue) and already updated our app, sadly not in time to be included on next release which is what I was trying to ensure...

**Comment by Nonnus** [comment]
actually I spoke too soon....
<img width="1281" alt="Screenshot 2020-05-27 at 23 04 27" src="https://user-images.githubusercontent.com/54864/83072122-7fd91000-a06e-11ea-928f-7ffd122c3017.png">
I have no words...

**Comment by lennardtastic** [comment]
Hi @Nonnus,

Try to delete local cache folder ```org.carthage.CarthageKit``` and then do a new ```carthage update --platform iOS```.

go to the folder and find a path - ```~/Library/Caches/org.carthage.CarthageKit```

I hope this helps,

Best Regards,
Lennard

**Comment by lennardtastic** [comment]
@Nonnus On a side-note. The issue might be related to Carthage, which they already fixed but have not released yet: https://github.com/Carthage/Carthage/issues/2887

**Comment by Nonnus** [comment]
@lennardtastic to be honest I though the much anticipated abi stability would provide both of us some relax about these "incompatibilities"

**Comment by lennardtastic** [comment]
@Nonnus So it actually does save a lot of time when it can be used (e.g. when you use Cocoapods for dependency management or manually add it you'll have module stability). 

It's just a matter of waiting for Carthage to support module stability for binary frameworks. I'm not sure what is blocking their release. 

btw did the earlier mentioned ```delete local cache``` help with the issue you were having?

**Comment by Nonnus** [comment]
> Hi @Nonnus,
> 
> Try to delete local cache folder `org.carthage.CarthageKit` and then do a new `carthage update --platform iOS`.
> 
> go to the folder and find a path - `~/Library/Caches/org.carthage.CarthageKit`
> 
> I hope this helps,
> 
> Best Regards,
> Lennard

apparently this fixed the problem and I was able to please the compiler gods of cupertino,
thanks a lot for your support

**Comment by Nonnus** [comment]
> @Nonnus So it actually does save a lot of time when it can be used (e.g. when you use Cocoapods for dependency management or manually add it you'll have module stability).
> 
> It's just a matter of waiting for Carthage to support module stability for binary frameworks. I'm not sure what is blocking their release.
> 
> btw did the earlier mentioned `delete local cache` help with the issue you were having?

yeah, they seem to be running in circles ever since SPM was announced (but can't still be used in lots of situations...)
