### ISSUE TITLE
Confusing Release mechanics

### ISSUE THREAD

**Issue by ggupta4harman** [usabilla/usabilla-u4a-ios-swift-sdk#197]
I am quite confused how the usabilla link for carthage changes with per xcode version. I thought that post 11.3.1 on master, master would always point to latest while for beta's or so or previous versions would be maintained as a separate url. Why is this approach taken up? This does impact consuming the SDK and need to check back again and again for the apt url. Any insights?

**Comment by eduakaszas** [comment]
Hi Gaurav, 

Thank you for your message and feedback. 

Whenever we release a new SDK version, we do that on the latest xCode. We name these after the version name, such as ‘v6.4.7’.   

When xCode comes out with a new stable release after this (before a new SDK version is ready) eg. xCode-11.5, we do a new release named ‘v6.4.7-xCode-11.5’.   When we'll release the new SDK version v6.4.8, it'll - again- point to the latest stable xCode version (which is currently 11.5 but may change by that point). 

I hope this helps but let me know if you have further questions. 

  Best regards,  Edua

**Comment by lennardtastic** [comment]
Closing this issue.

To add on to Edua's comment. We add several releases due too the previous issues that Carthage has with updating binary frameworks and it not support module stability. 
With the latest release Carthage, this should no longer be an issue.
