### ISSUE TITLE
Incompatible Swift Version

### ISSUE THREAD

**Issue by cpvbruno** [usabilla/usabilla-u4a-ios-swift-sdk#198]
I'm using the latest release for Xcode 11.5 via Carthage and I get this message after all:

`*** Downloading binary-only framework Usabilla at "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/v6.4.7-Xcode-11.5/Usabilla.json"
Incompatible Swift version - framework was built with 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53).`

**Comment by eduakaszas** [comment]
Hi Bruno, 

Thank you for reporting this. 

Could you try deleting the local cache folder `org.carthage.CarthageKit` and then run a new `carthage update --platform iOS` command?

Go to the folder and find a path `~/Library/Caches/org.carthage.CarthageKit`

I hope this helps but let me know if you're still facing the issue. 

Best regards, 
Édua

**Comment by lennardtastic** [comment]
Closing this.
