### ISSUE TITLE
Lacking support for Xcode 12 and Swift 5.3 

### ISSUE THREAD

**Issue by kandelvijaya** [usabilla/usabilla-u4a-ios-swift-sdk#199]
Is it possible to leverage module stability and not fixate on the particular swift version moving forward? If not; can you outline why? 

Please also check https://stackoverflow.com/a/58656323

**Comment by lennardtastic** [comment]
Hi @kandelvijaya 

We're planning on doing an Xcode 12 specific pre-release build for this Friday. 

Our SDK already supports module stability. We do the specific releases of our SDK for specific swift version releases for our customers that use Carthage (that until 1 week ago was not able to handle module stability). 

So if you're running into the issue I would recommend updating Carthage if you haven't already. Alternatively, you can use Cocoapods that already has our SDK working with Module Stability

Best Regards,
Lennard
