### ISSUE TITLE
Crash while calling without internet access

### ISSUE THREAD

**Issue by bbrflores** [usabilla/usabilla-u4a-ios-swift-sdk#2]
When trying to call the UsabillaFeedbackForm.initSDKWithScreenshot, I was expecting to receive a call on the delegate
feedbackFromLoadedIncorreclty
and then react to the fact that Usabilla server is not reachable or that the form cannot be shown.

Instead I get a crash:

> 0	UsabillaFeedbackForm	
> _TFFZFC20UsabillaFeedbackForm14NetworkManager13getFromFromIDFSSGC10PromiseKit7PromiseVS_4JSON_U_FTFS3_T_FPs9ErrorType_T__T_U_FTGSqCSo12NSURLRequest_GSqCSo17NSHTTPURLResponse_GSqCSo6NSData_GSqCSo7NSError__T_ + 732
> 1	Alamofire	
> ResponseSerialization.swift line 0
> Request.(response(queue : OS_dispatch_queue?, completionHandler : (NSURLRequest?, NSHTTPURLResponse?, NSData?, NSError?) -> ()) -> Self).(closure #1).(closure #1)
> 2
> libdispatch.dylib	
> _dispatch_call_block_and_release + 24
> 3	libdispatch.dylib	
> _dispatch_client_callout + 16
> 4	libdispatch.dylib	
> _dispatch_main_queue_callback_4CF + 1844
> 5	CoreFoundation	
> __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
> 6	CoreFoundation	
> __CFRunLoopRun + 1628
> 7	CoreFoundation	
> CFRunLoopRunSpecific + 384
> 8	GraphicsServices	
> GSEventRunModal + 180
> 9
> UIKit	
> UIApplicationMain + 204
> 

Should I avoid calling it when no connection is available? Should we handle reachability?

**Comment by gPinato** [comment]
This should have been fixed with the latest release. 

Can you let me know if you still experience the error?
