### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by MauMau97** [usabilla/usabilla-u4a-ios-swift-sdk#200]
Hi,

I'm currently optimizing an iOS app for Dark Mode and noticed that the latest version (6.4.7) doesn't support it.
When will support for Dark Mode be added? 

Regards,

Maurice

**Comment by lennardtastic** [comment]
Hi @MauMau97,

Currently, Dark Mode support can only be achieved by setting up a dark theme within the form-settings (see https://support.usabilla.com/hc/en-us/articles/360022053831-Customization-in-Usabilla-for-Apps). 

We do have native Dark Mode support on our radar, but we don't have an ETA yet.

Best Regards,
Lennard

**Comment by mthormann-dhi** [comment]
Any update on Dark Mode suppport?

**Comment by dbell-survey** [comment]
Hi mthormann-dhi, 

Yes! We are expecting to release Dark Mode support next week. If any changes in this timeline changes, we will definitely keep you updated.

**Comment by xanderwernecke** [comment]
Hi @mthormann-dhi , Dark mode support is available in v6.10.0. I'll close this ticket but if you have any more questions, please don't hesitate to reach out!

Kind Regards,
Xander
