### ISSUE TITLE
Incorrect documentation for setting custom variables

### ISSUE THREAD

**Issue by cjwhitsitt** [usabilla/usabilla-u4a-ios-swift-sdk#206]
The documentation at https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#custom-variables mentions the class function
``` swift
Usabilla.setCustomVariable(value: Any?, forKey: String)
```
However, this function doesn't exist. The only way to add custom variables is the second example in that section:
``` swift
Usabilla.customVariables["key"] = "value"
```

**Comment by dan11218** [comment]
Hi @cjwhitsitt thanks for bringing this to our attention! We will review the documentation and update it accordingly!
