### ISSUE TITLE
I don't know what has changed, but Usabilla SDK has been causing us fewer and fewer problems

### ISSUE THREAD

**Issue by jeroenleenarts** [usabilla/usabilla-u4a-ios-swift-sdk#208]
I have been critical about the Usabilla SDK in the past. Just wanted to log an issue of no issue today.

Thank you for the improvements made in the past year, your work has helped a lot.

**Comment by jeroenleenarts** [comment]
Obviously this issue can be closed at your convenience. But only if you agree. ;)

**Comment by eduakaszas** [comment]
Hi @jeroenleenarts , 

Thanks for the lovely feedback! :) 

Kind regards, 
Édua
