### ISSUE TITLE
Cannot perform app install on actual device on Xcode 12 with SPM Usabilla SDK

### ISSUE THREAD

**Issue by mthormann-dhi** [usabilla/usabilla-u4a-ios-swift-sdk#209]
Repro steps:

1. Installed Usabilla SDK with Swift Package Manager version (replaced pod install)
2. Cleaned out derived data, project build folder
3. Tried to deploy the app from Xcode to existing actual device (not simulator)

Received "Unable to Install" dialog with "No code signature" as the root cause.  Same issue as https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953 and in Swift backlog as [SR-13343](https://bugs.swift.org/browse/SR-13343) so i suspect that's what's going on.

Installing to simulator had no issues.  Removing the SPM package and going back to pods fixed the issue.

I'm not sure that there's anything that Usabilla can do on this one but wanted to raise the issue in case there was something to be done(e.g. other than not deploying frameworks through SPM maybe).

I'll also note that adding the SPM Usabilla probably slowed our deployment build automation by 1-2 minutes every cycle because the large source pull required (we clean and fetch every time).  Is there some way the size of the SPM package can be reduced?

**Comment by eduakaszas** [comment]
Hi @mthormann-dhi, 

Thank you for reporting this. 

Our developers have thoroughly tested this and they believe this issue doesn't have anything to do with Usabilla. Instead, it indeed seems to be related to the bug reported on Swift's end. 

As for the SPM issue, the download indeed takes around 1 minute the first time you do it and therefore the same will also happen if you clean and fetch every time. Our developers will looking into improving this in the future as SPM support for binaries grows. 

Let me know if you have any questions. 

Kind regards, 
Édua

Our developers have thoroughly tested this on their end and they believe it's not related to Usabilla. Instead, it indeed seems to be connected to the issu
