### ISSUE TITLE
Usabilla Swift Framework in Obj-C Project

### ISSUE THREAD

**Issue by mfromage** [usabilla/usabilla-u4a-ios-swift-sdk#21]
Sorry for asking dumb question.
I've install the sdk in my project, and i've tried to import.
But the class still not recognized.

![screenshot 2017-02-02 16 11 56](https://cloud.githubusercontent.com/assets/6586299/22543245/62841d54-e962-11e6-8fbd-e5d32083f3f5.png)

![screenshot 2017-02-02 16 12 09](https://cloud.githubusercontent.com/assets/6586299/22543247/641d0eb4-e962-11e6-99d6-5198fa49f519.png)

**Comment by gPinato** [comment]
The current SDK cannot be used directly in Obj-C code.
If you want to integrate the Swift SDK in an Obj-C app, the best way to do it is using a swift file that extends the Obj-C viewcontroller and call the SDK from there.

Take a look at [this](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#integration-with-obj-c-application) guide for more specific instruction.

Let me know if you have any problem with this solution.
