### ISSUE TITLE
Swift Packages Binary Framework is breaking uploading to App Store

### ISSUE THREAD

**Issue by tomasharkema** [usabilla/usabilla-u4a-ios-swift-sdk#210]
When using Swift Package Manager in Xcode to embed Usabilla, Xcode will embed the framework in every folder possible. If where is a PlugIns folder, for an appex, Usabilla is moved there as well. Same goes for the Watch folder. Xcode should only move it to the Frameworks folder.

An approach to fix this, could be to remove the framework from those folders in a separate script phase. But this is actually a bit ugly.

Local, Adhoc or Enterprise builds will build and run fine, but when uploading to AppStore Connect, Apple will actually start to complain about this. See logs below.

I think we need to investigate why Xcode does this. Maybe the Usabilla framework needs to be shipped (marked) as a dynamic framework in the Package.swift file. 

Any help with this would be highly appreciated.

```
Package Summary:
1 package(s) were not uploaded because they had problems:
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/843A76EC-CB02-477E-AD17-A1F7E804728F/[REDACTED].itmsp - Error Messages:
		ERROR ITMS-90680: "Invalid directory. The bundle Payload/x.app/PlugIns/Usabilla.framework is not contained in a correctly named directory. It should be under "Frameworks"."
		ERROR ITMS-90680: "Invalid directory. The bundle Payload/x.app/Watch/Usabilla.framework is not contained in a correctly named directory. It should be under "Frameworks"."
		ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.usabilla.Usabilla' under the iOS application 'x.app'."
```

**Comment by eduakaszas** [comment]
Hi @tomasharkema , 

Thank you for your message & apologies for the belated response. 

This is an xCode/Swift package issue. We have already tried the dynamic framework, however it's not a solution for this issue in particular. 

We're hoping this will get resolved in upcoming xCode versions.

Kind regards, 
Édua
