### ISSUE TITLE
Custom Emoticons Rating not working correctly with VoiceOver

### ISSUE THREAD

**Issue by aderussell** [usabilla/usabilla-u4a-ios-swift-sdk#213]
The Custom Emoticons Rating view isn't working correctly with VoiceOver enabled on a device.

When swiping up/down to adjust the value on the control it does not go through the order of the items correctly and also skips item four. It will go up 'one-three-two-five' and back down again 'five-two-three-one' four is not a selectable option.

I've attached a zipped archive of a short video showing the issue on version '6.4.7', although the same occurs on '6.5.0'

[Usabilla VoiceOver Rating.mp4.zip](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/files/5523740/Usabilla.VoiceOver.Rating.mp4.zip)

Kind regards.

**Comment by eduakaszas** [comment]
Hi @aderussell , 

Thank you for your message & for the information provided. 

Our developers are planning on releasing a fix for this issue next week. We'll let you know once it's released.

Kind regards, 
Édua

**Comment by aderussell** [comment]
Hi @eduakaszas.

Just checking how progress is going with this ticket.

Kind regards,
- Adrian

**Comment by eduakaszas** [comment]
Hi @aderussell , 

Thank you for your response. 

Our developers are still working on fixing this issue, we sincerely apologise for the delay. We'll let you know once the fix is released. 

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @aderussell,

This issue has been fixed recently - feel free to reopen the case if you're still encountering issues. 

Kind regards, 
Édua
