### ISSUE TITLE
Module 'Usabilla' was created for incompatible target arm64-apple-ios9.0

### ISSUE THREAD

**Issue by DKalachniuk** [usabilla/usabilla-u4a-ios-swift-sdk#216]
Hello, 
When I'm trying to build Release scheme on the simulator i receive this error

Module 'Usabilla' was created for incompatible target arm64-apple-ios9.0

I'm using Xcode 12.2. I'm using 6.5.0 version. Tried with 6.6.0 and still the issue is there.

Could you please take a look?
Thank you

**Comment by eduakaszas** [comment]
Hi @DKalachniuk, 

Thank you for your message. 

To resolve this, could you please try setting up the Build Settings in the following way:

Excluded Architectures
 Debug -> Any iOS Simulator SDK: arm64
 Release -> Any iOS Simulator SDK: arm64

Let me know how that goes!

Kind regards, 
Édua

**Comment by DKalachniuk** [comment]
Hello @eduakaszas,

Yes, that worked. But i did one more thing:

I set Build Active architectures Only to YES for release scheme.


Only after that (2 things) it started to work. Thank you!
