### ISSUE TITLE
Error when building on M1 hardware.

### ISSUE THREAD

**Issue by jeroenleenarts** [usabilla/usabilla-u4a-ios-swift-sdk#217]
`Module 'Usabilla' was created for incompatible target arm64-apple-ios9.0`

Again... open source the SDK... Most of your package and compilation problems will be gone.

**Comment by eduakaszas** [comment]
Hi @jeroenleenarts , 

Thank you for your message. 

Could you please try setting up the Build Settings in the following way:

Excluded Architectures
Debug -> Any iOS Simulator SDK: arm64
Release -> Any iOS Simulator SDK: arm64

Let me know how that goes!

Additionally, thank you for your suggestion regarding open sourcing the SDK. Our developers are constantly evaluating this option, however, they don't have clear plans on this and have different priorities at this time. We'll let you know in case this will change in the future. 

Kind regards, 
Édua

**Comment by jeroenleenarts** [comment]
We are targeting Apple Silicon as well. So excluding arm64 would be a bit against what we are trying to achieve.

**Comment by eduakaszas** [comment]
Hi @jeroenleenarts , 

Thank you for your response. 

I understand your concerns, however, currently our SDK doesn't support arm64 for simulators. Therefore, we'd recommend trying the workaround for now. 

We apologise for the inconvenience. 

Kind regards, 
Édua

**Comment by emiellensink** [comment]
Basically, this means that developers on new Apple Silicon Macs are not able to build and run software that includes the usabilla SDK. Given that Apple has been quite forward with this and even offered test hardware and software almost half a year before release of the final hardware, this is surprising. 
All of the other SDKs we use have already been updated or at least have beta versions for this new architecture.

**Comment by epologee** [comment]
There haven't been any updates about this in two months, it seems, and the number of colleagues that work on M1 Macs is steadily rising. Can you give your (paying) customers some insights into the status of arm64 support?

**Comment by acebolla** [comment]
Hi @epologee,

Thank you for your input.

Surveymonkey is running test with Big Sur (next OS for mac’s). Until it has been approved we can’t use the M1 computer in the company. The timeline for this is unknown.

We do however plan to release a non-production ready version of the SDK beginning on next week, that our customers can test on.

I hope this helps, but please let us know if you have any other questions.

Best regards, 
Ana

**Comment by haafiz-io** [comment]
> We do however plan to release a non-production ready version of the SDK beginning on next week, that our customers can test on.

Where can I find this?

**Comment by OleksiiShvachenko** [comment]
Any chance that it will be fixed?

**Comment by eduakaszas** [comment]
Hi @OleksiiShvachenko & @haafiz-io , 

Thank you for your response. 

Our developers will create a non-production version later this week and conduct tests on a M1 device - I'll get back to you then with an update. However, please note, that we currently do not support the latest MacOS version, therefore we won't be able to officially release for M1 hardwares yet. 

Let us know if you have any questions in the meantime., 

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @OleksiiShvachenko , @haafiz-io , @jeroenleenarts, @emiellensink & @epologee , 

Thank you for your patience. 

Our team has released a pre-release with a native build for M1, which should allow you to test on M1 hardware. For this, you'll need to use this branch:
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/tree/Xcode-12.5-m1-pre

I'll close this case for now, however, if any of you have any questions, please let us know. 

Kind regards, 
Édua

**Comment by Michael-Wheeler** [comment]
Hi all,

I'm coming to this later on, and I'm looking to build our app for arm64. Has there been any progress on a production ready version of the M1 release. Thank you for the help.
