### ISSUE TITLE
Crash when Usabilla.initialize(appId:) is not invoked on main thread

### ISSUE THREAD

**Issue by kimar** [usabilla/usabilla-u4a-ios-swift-sdk#218]
Similar to what's been observed in #186 we've also observed a crash when `Usabilla.initialize(appId:)` was invoked from another thread than the main thread.

We've mitigated this in the same way as described in https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/186#issuecomment-735682922

Now my question is: If `Usabilla.initialize` is not thread-safe, could you please document this so the next people implementing the SDK won't run into this issue?

Thank you!

**Comment by eduakaszas** [comment]
Hi @kimar, 

Thank you for your message. 

This is a good suggestion. I've discussed it with our developers and they're planning on updating the documentation with the next SDK release. 

Let us know if you have any questions. 

Kind regards, 
Édua
