### ISSUE TITLE
CocoaPods: Can't merge user_target_xcconfig for pod targets: [...] Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

### ISSUE THREAD

**Issue by bonkey** [usabilla/usabilla-u4a-ios-swift-sdk#219]
We're facing multiple warnings in CocoaPods (1.10.1) integration with the latest SDK (6.6.1):

```
[!] Can't merge user_target_xcconfig for pod targets: ["Dynamic", "Usabilla", "Adyen", "Card", "Core", "DropIn", "Adyen3DS2"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.
```

I see it was added on purpose (#211), but as https://github.com/mopub/mopub-ios-sdk/pull/345 states that `user_target_xcconfig` should not be used, but only `pod_target_xcconfig`:

> The podspec syntax reference says this attribute is "not recommended" and discourages its use.
>
> https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig

Would it be possible to remove it?

**Comment by dbell-survey** [comment]
Hi @bonkey, 

Thanks for reaching out. 

I have spoken to our developers and they have informed me that this will be removed in our next release. If you have any additional questions, please do not hesitate to reach out.

**Comment by bonkey** [comment]
Hi @dbell-survey, the issue still exist and wasn't fixed in last 2 releases. Could you please give an update on it?

**Comment by eduakaszas** [comment]
Hi @bonkey, 

Thank you for your response and we apologise for the delay. 

Our developers are still investigating this and are aiming to include this in the next release. 

Let us know if you have any questions in the meantime. 

Kind regards, 
Édua

**Comment by mvandervelden** [comment]
We're having the same issue, when using this together with GoogleTagManager. Would love to see this resolved in next release.
I gathered some details in [this demo project](https://github.com/mvandervelden/GTMPodIssueTest) illustrating the issue, but it's basically the same as reported above.

**Comment by eduakaszas** [comment]
Hi @mvandervelden @bonkey, 

Thank you for the additional information & your patience.

Our developers have fixed this issue in the latest release by removing these properties from the podspec file. 

I'll close this case for now, but feel free to reach out again in case you're experiencing any issues. 

Kind regards, 
Édua
