### ISSUE TITLE
UsabillaFeedbackForm.loadFeedbackForm freeze the current UIViewController

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#22]
Hi guys, after fetching the new version, 3.2.0, the form is showed properly but after dismiss Usabilla controller, the previous View is frozen.

Even commented the follow code the view is frozen:
```
func formLoadedCorrectly(_ form: UINavigationController, active: Bool) {
//    present(form, animated: true, completion: nil)
}
```

Here the code when we load Usabilla:
```
private func setupUsabilla() {
    // config the them form
    let themeConfig = UsabillaThemeConfigurator()
    themeConfig.customFont = Font.avenirLight.big
    // set the form
    UsabillaFeedbackForm.delegate = self
    UsabillaFeedbackForm.showCancelButton = true
    UsabillaFeedbackForm.loadFeedbackForm("xxxxxxxxxxxxxxxxxxxxxxx", themeConfig: themeConfig)
}
```

[UPDATE]
Seems there is a UITransitionView which stay alive on top:
![screen shot 2017-02-06 at 3 46 08 pm](https://cloud.githubusercontent.com/assets/895478/22651528/9f491856-ec83-11e6-83c2-b8c6a3586121.png)

**Comment by grimabe** [comment]
Hi @cikpis

I tried to reproduce it but I couldn't: can you make a sample app that reproduces it ? 

Thanks

**Comment by cikpis** [comment]
Update the main comment.

**Comment by grimabe** [comment]
Does the screenshot has been taken with the **present** method commented ? 

so it happened after calling the line : `UsabillaFeedbackForm.loadFeedbackForm("xxxxxxxxxxxxxxxxxxxxxxx", themeConfig: themeConfig)`?

I reiterate my request about having a sample app able to reproduce it.

Thank you

**Comment by cikpis** [comment]
"Does the screenshot has been taken with the present method commented ?"
I tried with this commented and uncommented

"so it happened after calling the line : UsabillaFeedbackForm.loadFeedbackForm("xxxxxxxxxxxxxxxxxxxxxxx", themeConfig: themeConfig)?" 
Yes

"I reiterate my request about having a sample app able to reproduce it."
I cannot share the project. We could schedule a call.

**Comment by cikpis** [comment]
maybe this can help:
http://stackoverflow.com/questions/36142576/view-being-blocked-by-uitransitionview-after-being-presented

**Comment by cikpis** [comment]
Hey @grimabe . Hi might found the problem. Is it possible to have a delegate when Usabilla form is dismissed? 

We need that in order to dismiss the UIViewController where the Usabilla form is loaded. That was the view on top that was blocking the app. I thought Usabilla removes the parents as well. So, we need a delegate so we can remove the container were it was showed.

Thanks in advance.

**Comment by gPinato** [comment]
Hey @cikpis,

We understand the problem now. Could you tell me why are you wrapping the form inside your own UIViewController?

We are willing to help you solve this but first I want to make sure adding a feature on the fly is really the only solution.

**Comment by cikpis** [comment]
Hi @gPinato, because of the example code here https://github.com/usabilla/usabilla-u4a-ios-swift-sdk I thought that was the way. I've already changed our side and now should work. Need to test and I'll update you guys.

**Comment by gPinato** [comment]
@cikpis Indeed it was just an example. We will update the docs to be more clear.
The behaviour now should be the expected one. I'll close the issue, reopen it if you have more problems.

**Comment by cikpis** [comment]
@gPinato I just test it and it's working like expected. Would be nice to let devs handle the dismiss part because like us we have a custom NavigationManager.

Anyway, sorry for the misunderstanding that I have created and thanks for your effort.

**Comment by gPinato** [comment]
@cikpis No problem, it's our job. 
We will eventually introduce a delegate method to let you know when the form needs to be dismissed.

One last thing: while digging to find your issue we also found another one that might freeze the dismissing of the form. An hotfix is coming this afternoon, be sure to update to that before going live.

**Comment by cikpis** [comment]
@gPinato sure I will! Thanks for letting me know and I'm glad that at least you solve an issue thanks this other one :)

**Comment by gPinato** [comment]
@cikpis v3.2.1 has just been published

**Comment by cikpis** [comment]
@gPinato thanks for the tip 👍
