### ISSUE TITLE
Required field error message label gets partially displayed when submitting form with missing required fields

### ISSUE THREAD

**Issue by chirayupatel** [usabilla/usabilla-u4a-ios-swift-sdk#224]
- Create campaign or passive form with start, page 2 and end pages with required fields in page 2
- Open passive form or continue from campaign start page to see page 2
- Click Submit without adding required fields responses

Result :- Page auto scrolls up and hides the Required field error message label displayed at the top of the page
Expected :- Page should not auto scroll and partially hide the error message label

**Comment by eduakaszas** [comment]
Hi @chirayupatel , 

Thank you for your message & all the information. 

We'll look into this on our end and get back to you with more information as soon as possible.

Let me know if you have any questions in the meantime. 

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @chirayupatel , 

Thank you for your patience. 

Our developers have fixed this issue in the latest release. 

I'll close this case for now, however, feel free to reach out in case you have any questions!

Kind regards, 
Édua

**Comment by chirayupatel** [comment]
Hi @eduakaszas,

We tried using latest SDK build 6.8.0 (using SPM) and are still noticing the same issue. 
Let me know if you need any additional details.

Thank you,
Chirayu

**Comment by eduakaszas** [comment]
Hi @chirayupatel, 

Thank you for your response & I'm sorry to hear you're still experiencing this issue!

Would it be possible for you to provide us with the appID and event of the Campaign you're using in your staging environment so we can test and reproduce it on our end? If you'd prefer not to share it here, you can also send it to support@usabilla.com (linking this Github ticket) and we'll take it from there. 

Additionally, can you also provide a screenshot or short video of this issue?

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @chirayupatel, 

Just to add to the above, could you please also provide the device type and the iOS version you reproduced this issue on?

Thank you!

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @chirayupatel , 

Thank you for your patience & for sharing additional details via email. 

After investigating this further, our developers have found that what you're experiencing is actually expected behaviour. When an element is not present in the viewport, scroll is added to have the element appear in the viewport. 

That being said, they're now working on changing this behaviour so the autoscroll is not applied in these cases - we'll let you know once this is released. 

Let me know if you have any questions. 

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @chirayupatel , 

Thank you for your patience. 

A fix for this issue was included in the latest SDK release from a few days ago. 

We'll close this case for now, however, feel free to reopen it if the issue still persists. 

Kind regards, 
Édua
