### ISSUE TITLE
Return input field result in FeedbackResult

### ISSUE THREAD

**Issue by JackoPlane** [usabilla/usabilla-u4a-ios-swift-sdk#226]
We have a use case where, once a form has been submitted we need the ability to access the message a user may of entered. Can this be added to the `FeedbackResult` ?

**Comment by eduakaszas** [comment]
Hi @JackoPlane, 

Thank you for your message. 

Could you provide us more information on this use-case, why would you like to access the answers the users entered when the form is submitted?

We'll then discuss with our developers whether this would be a possibility. 

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by JackoPlane** [comment]
Our use case is that we would need to also have this feedback captured into our analytics package(s) for the data analytics team

**Comment by eduakaszas** [comment]
Hi @JackoPlane,

Thank you for your response. 

For that purpose, we recommend utilising our public API. Through this, you can push the collected responses (both campaigns and forms) to your analytics solution. You can find more information about this here: https://developers.usabilla.com/#usabilla-for-apps

Let me know if you have any questions. 

Kind regards, 
Édua
