### ISSUE TITLE
v6.8.5-Xcode-12.4 only supports Swift 5.5

### ISSUE THREAD

**Issue by danlages** [usabilla/usabilla-u4a-ios-swift-sdk#229]
Hey all, just a heads up that you're latest version of the framework only supports the latest version of Swift (5.5).

If you plan to support 12.4 as the title suggests with this version you will need to support this version.

**Comment by eduakaszas** [comment]
Hi @danlages , 

Thank you for reaching out!

We recommend upgrading to the latest SDK version (v6.8.6) - let us know if you continue experiencing any issues. 

Kind regards, 
Edua

**Comment by danlages** [comment]
Hi @eduakaszas I updated to this version but now the nav bar is broken again on the simulator
