### ISSUE TITLE
Custom callback on UINavigationController

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#23]
Hi guys, is it possible to have a custom callback for the UINavigationItem? 

We need them because an example in our last project we are using a custom NavigatioManager and we cannot call the follow code directly:
```
present(, animated:, completion:)
dismiss(animated: , completion:)
```

**Comment by grimabe** [comment]
Hi @cikpis 

If you can be more explicit in what you want to achieve ?
the delegate method ** formLoadedCorrectly ** is sending back  a UINavigationController.
Are you not able to present it ?

how your custom NavigationManager works ?

**Comment by cikpis** [comment]
I can present it but when I tap on close button the Usabilla view is gone and my view is frozen.

**Comment by cikpis** [comment]
@grimabe I think we wrote on the wrong issue :)

**Comment by grimabe** [comment]
Closing as it is a duplicate of #22
