### ISSUE TITLE
Missing xcframework support for Carthage distribution

### ISSUE THREAD

**Issue by RajaveluC** [usabilla/usabilla-u4a-ios-swift-sdk#231]
Although XCFramework support has been made for Usabilla for CocoaPods and manual installation, the support seems to be still missing for Carthage distribution. When can we expect this support to be available for Xcode 12.5.1 and above?

**Comment by lennardtastic** [comment]
Closing ticket. Fixed in release https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.9.0
