### ISSUE TITLE
Campaign malfunction with Title & text UI component

### ISSUE THREAD

**Issue by Goseong** [usabilla/usabilla-u4a-ios-swift-sdk#232]
When using the Title & text component in the campaign banner, and you leave the optional text field empty, then it breaks the entire campaign. This is occurring on all recent iOS builds.

### The intro page and all follow-up pages are displayed like this:

![IMG_7970300794D5-1](https://user-images.githubusercontent.com/25725559/144824676-5fe6c890-8c79-4d2e-a636-2a85e3ecd39f.jpeg)

### Example of the console here:

![Screenshot 2021-12-06 at 10 37 22](https://user-images.githubusercontent.com/25725559/144822793-f8644ce3-0191-4ee3-88a0-3df0b1330cfa.png)

**Comment by xanderwernecke** [comment]
Hi @Goseong .

Thank you for reaching out. Our Developers have mentioned that this issue has been fixed and will be available in the upcoming release. 
If you have any additional questions, please don't hesitate to ask!

Best Regards,
Xander

**Comment by xanderwernecke** [comment]
Hi @Goseong . This issue has been fixed in v6.10.0. If you have any additional questions, please don't hesitate to reach out!

Kind Regards,
Xander
