### ISSUE TITLE
Memory leaks when presenting Feedback Form

### ISSUE THREAD

**Issue by weedmapsmike** [usabilla/usabilla-u4a-ios-swift-sdk#233]
Following the instructions in the setup guide, after presenting and dismissing several feedback forms we noticed none of the objects associated w/the feedback forms were deallocated.

**Comment by eduakaszas** [comment]
Hi @weedmapsmike , 

Thank you for reaching out!

To help us be able to reproduce this, could you please share more details, including:

- logs
- screenshots
- formID
- appID
- event (to trigger the Campaign)

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by xanderwernecke** [comment]
Hi @weedmapsmike 
Please let me know if this is still an issue you are facing and if so, please could you send the following:

- logs
- screenshots
- formID
- appID
- event (to trigger the Campaign)

to support@usabilla.com.

Kind Regards,
Xander
