### ISSUE TITLE
Header background color on iOS <=14

### ISSUE THREAD

**Issue by WRiferreiro** [usabilla/usabilla-u4a-ios-swift-sdk#234]
We are using the latest version of the SDK (v6.11.0) and there still seems to be an issue with the header, that might have been introduced while fixing it for iOS 15.

As you can see on the picture below, the same camping looks different on iOS 15 and iOS 14. Is this something you are aware off?

![image](https://user-images.githubusercontent.com/97174115/151995953-d6a042a2-36a4-4637-8279-8b0f4f79b3dd.png)

_Originally posted by @WRiferreiro in https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/227#issuecomment-1026957717_

**Comment by stodorovicc** [comment]
Hi @WRiferreiro ,

Thank you for reaching out.

Could you please let us know which version of xcode are you using? Our SDK developer could not replicate this issue on iOS 13/14/15 with xcode 13.2.1.

Looking forward to hearing from you.

Kind regards,
Slobodan

**Comment by WRiferreiro** [comment]
Hi @stodorovicc, also using xcode 13.2.1

**Comment by stodorovicc** [comment]
Hi @WRiferreiro , thank you for your response.

Can you please provide us with App ID/Form ID, Campaign event name and steps to reproduce this issue?

Thanks in advance,
Slobodan

**Comment by WRiferreiro** [comment]
Hey @stodorovicc, is there an email I could send you this info to?

**Comment by stodorovicc** [comment]
Hi @WRiferreiro yes, you could send it to support@usabilla.com.

Looking forward to your email.

Kind regards,
Slobodan
