### ISSUE TITLE
Custom checkbox implementation to create consent view

### ISSUE THREAD

**Issue by rdhuri7** [usabilla/usabilla-u4a-ios-swift-sdk#237]
Hi Team,

Can you please guide me to some docs which provide way to create custom checkbox as displayed in the screenshot attached below.

<img width="83" alt="Screenshot 2022-06-27 at 4 38 08 PM" src="https://user-images.githubusercontent.com/45159702/175927926-295779db-bbca-45f0-bf8a-421b87a96014.png">
 
 TIA

**Comment by emulroy9** [comment]
Hi @rdhuri7 , this will work if you add a paragraph element and add HTML to it (you will need to select "enable HTML" in the control options below where you insert the actual HTML)
