### ISSUE TITLE
[happend in iOS 16]Show the Usabilla, tap cancel on Usabilla.Then,the App current entire page is not interactive.

### ISSUE THREAD

**Issue by helenWN** [usabilla/usabilla-u4a-ios-swift-sdk#243]

**Comment by HaiqaK** [comment]
Hi @helenWN,

Could you please try updating to the latest version of our sdk. v6.12.3 helps fix the app freezing after a campaign is finished/cancelled https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.12.3

Thanks,
Haiqa

**Comment by helenWN** [comment]
thanks, it works
