### ISSUE TITLE
Campaign banner not displaying properly with empty description

### ISSUE THREAD

**Issue by Goseong** [usabilla/usabilla-u4a-ios-swift-sdk#244]
Hi there,

We have been experiencing an issue when leaving out the optional description on the intro banner.

![Screenshot 2022-09-26 at 16 17 52](https://user-images.githubusercontent.com/25725559/192301198-e1ef1a89-0aba-4b62-a085-ef8479895ef2.png)

It only displays the buttons and the rest of the survey stops working as well. When providing a description the issue doesn't occur. 

![IMG_2651](https://user-images.githubusercontent.com/25725559/192301361-fd02a2cd-6cf1-45db-b1d4-9c6bbea98dde.PNG)

**Comment by HaiqaK** [comment]
Hi @Goseong,

Could you please try updating to the latest version of our iOS SDK? We recently set a fix for the _text (optional)_. 

Thanks,
Haiqa
