### ISSUE TITLE
SPM fetching Usabilla SDK never ends

### ISSUE THREAD

**Issue by tscholze** [usabilla/usabilla-u4a-ios-swift-sdk#245]
Fetching the exact version 6.12.3 does not finish. Also if I use a range of versions, the dialog will not disappear or progress.

**Screenshot**
<img width="1153" alt="Bildschirmfoto 2022-10-05 um 12 16 45" src="https://user-images.githubusercontent.com/5583469/194038200-e2752269-c208-4c7a-a91a-6615517a066c.png">

**Comment by tscholze** [comment]
**Update**

After the 10th try, it worked but only specifying the latest version directly.

**Comment by nehagfb** [comment]
Hi @tscholze,

Thanks for letting us know. I will close this issue here for now but if the issue persists please feel free to reopen it again. 

Many thanks,
Neha

**Comment by jeangael-domine** [comment]
Hi,

I confirm I had the exact same issue and I also had to specify the latest version as a workaround.
