### ISSUE TITLE
NavigationBar textAttributes and tint color

### ISSUE THREAD

**Issue by JakubMazur** [usabilla/usabilla-u4a-ios-swift-sdk#247]
SDK version: **6.12.3**

According to documentation:
Navigation bar color can be changed by setting theme: 

```Usabilla.theme.colors.header = UIColor.yellow```

Is there a way to change header text color along with it? If I will set light background to match my app style seems like I will not be able to customize title `textAttributes` that will make a text unreadable.

<img width="479" alt="image (4)" src="https://user-images.githubusercontent.com/1788063/203988945-b3d9d3c1-09b0-4944-be31-e056be181465.png">

Of course there is an option to set tint color on navigation bar, but seems hacky and also `titleTextAttributes` has no effect 

```swift
func formDidLoad(form: UINavigationController) {
    self.present(form, animated: false, completion: {
        form.navigationBar.tintColor = .purple
        form.navigationBar.titleTextAttributes = [.foregroundColor: UIColor.black] // this has no effect
    })
}
```

<img width="462" alt="image (5)" src="https://user-images.githubusercontent.com/1788063/203989848-b661ffd2-a2ba-47ca-a5a2-daaad317c0c4.png">

**Comment by HaiqaK** [comment]
Hi @JakubMazur, please refer to our support article https://help.surveymonkey.com/en/getfeedback/builder/app-theme/ for using themes.

**Comment by HaiqaK** [comment]
Hi @JakubMazur, please refer to our support article https://help.surveymonkey.com/en/getfeedback/builder/app-theme/ for using themes.
