### ISSUE TITLE
.theme.statusBarStyle has no effect in FeedbackForm ViewController

### ISSUE THREAD

**Issue by JakubMazur** [usabilla/usabilla-u4a-ios-swift-sdk#249]
SDK version: **6.12.3**

I'm trying to customize FeedbackForm screen in my app. Using this variable:
 
```swift
Ustabilla.theme.statusBarStyle = .lightContent
```

In my .plist file I have:
`Status bar style`: `Dark Content` 
`View controller-based status bar appearance`: `YES`

<img width="479" alt="image (4)" src="https://user-images.githubusercontent.com/1788063/203991848-190dd242-412b-4dbb-a5fe-bfbeadb63904.png">

**Comment by HaiqaK** [comment]
Hi @JakubMazur thanks for reaching out. Please refer to this article https://help.surveymonkey.com/en/getfeedback/builder/app-theme/ for using themes.

**Comment by emulroy9** [comment]
Hi @JakubMazur please refer to [this article](https://help.surveymonkey.com/en/getfeedback/builder/app-theme/)
