### ISSUE TITLE
Wrong camera orientation if opening "add a photo" with an iPad face up

### ISSUE THREAD

**Issue by iNono22** [usabilla/usabilla-u4a-ios-swift-sdk#250]
- On iPad
- Place your iPad face up (like on a table) in portrait mode
- Open GetFeedback form
- Tap on "Add a photo" in the screenshot section
- Raise your iPad in front of you keeping it in portrait mode

Actual:
- The camera has 90º (or -90º) orientation.

Expected:
- Camera should have correct orientation.

Note: if rotate iPad in landscape and come back to portrait mode, it rotate good

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
