### ISSUE TITLE
Issue generating library for Mac Catalyst

### ISSUE THREAD

**Issue by rdhuri** [usabilla/usabilla-u4a-ios-swift-sdk#253]
Hi,

I'm trying to make an iPhone application compatible to MAC Catalyst which uses Usabilla internally to capture user feedbacks.
I'm using Swift Package Manager to add the dependency inn my project.
But I keep getting below error :- 
`
While building for Mac Catalyst, no library for this platform was found in '/Users/TestApp/Usabilla.xcframework'.
`

Am I missing something or is Usabilla not compatible with MAC Catalyst?

TIA

**Comment by nehagfb** [comment]
Hi Rahul,

Thank you for reaching out.

MAC Catalyst is unfortunately not officially supported by Usabilla at this time.

Please let me know if you have any questions.

Kind regards,
Neha
