### ISSUE TITLE
Repo size is 1.40Gb when integrating Usabilla with SPM

### ISSUE THREAD

**Issue by victor-sarda** [usabilla/usabilla-u4a-ios-swift-sdk#258]
Unfortunately, SPM downloads the whole repo history, and this behavior cannot be tweaked at the moment.
This is an issue when using SPM to integrate Usabilla into a project. The repo is around 1.40Gb:

<img width="713" alt="image" src="https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/assets/6460866/46d0991d-8979-47a5-a44a-087f70a94dc9">

---

In my company, we decided to use the `xcframework` from the release assets at the moment, but one solution could be to follow what Airbnb did with Lottie and publish the package to a different repo (https://github.com/airbnb/lottie-spm). 
Their repo only contains a Package with a binary target, linking to the `xcframework`:

```swift
let package = Package(
  name: "Lottie",
  platforms: [.iOS("11.0"), .macOS("10.11"), .tvOS("11.0")],
  products: [.library(name: "Lottie", targets: ["Lottie", "_LottieStub"])],
  targets: [
    .binaryTarget(
      name: "Lottie",
      url: "https://github.com/airbnb/lottie-ios/releases/download/4.2.0/Lottie.xcframework.zip",
      checksum: "4db3dee208f6213e5c1681f2314c7ed96d466d9b9adfe5cd0030309515075443"),
    
    // Without at least one regular (non-binary) target, this package doesn't show up
    // in Xcode under "Frameworks, Libraries, and Embedded Content". That prevents
    // Lottie from being embedded in the app product, causing the app to crash when
    // ran on a physical device. As a workaround, we can include a stub target
    // with at least one source file.
    .target(name: "_LottieStub"),
    
    .testTarget(
      name: "LottieTests",
      dependencies: ["Lottie"],
      path: "Tests")
  ])
```

**Comment by idrougge** [comment]
Please fix this now. Our CI times out because it cannot check out the repository in due time.

**Comment by lennardtastic** [comment]
Might be related to https://github.com/apple/swift-package-manager/issues/6062 

We're looking into possible ways to fix this.

**Comment by lennardtastic** [comment]
Hi All, 

Our apologies for the delay, it took a bit longer to get this work planned. Unfortunately, there was no fix on the related SPM issue. We'll keep an eye out on the related issue to see if a fix is in the works. 

To address the issue for the time being we've created a fork of the repo with a smaller footprint for SPM. You can find the repo by following the link [https://github.com/usabilla/usabilla-u4a-ios-sp](https://github.com/usabilla/usabilla-u4a-ios-sp). 

Please let us know if this addresses the CI timeouts that you were having. 

I'll close the issue for now, but if the issue still persists please let us know and I'll reopen this issue.
