### ISSUE TITLE
`loadFeedbackForm` does not work

### ISSUE THREAD

**Issue by IsaiahvH** [usabilla/usabilla-u4a-ios-swift-sdk#259]
The documentation states that you can use `Usabilla.loadFeedbackForm(formId)` "to fetch and display the form inside your app", e.g. not event-based. However, when we call this method following [the documentation](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#loading-a-form), no form is loaded. Instead, a generic `UBError` is passed to the delegate. This is for us a serious blocker, as we would like to have programmatic control when to show a feedback form.

Additionally, when we call this method, we can see the SDK performs a GET requesting the background to "https://sdk.out.usbla.net/app/forms/{formId}". This SDK request fails with a "400 Bad Request", **indicating the SDK does not perform the correct API request** to Usabilla. 
_SDK API Error_
![sdk_api_error](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/assets/1858814/beb70b7d-df6e-47df-bd72-a19298544f48)

Can this malformed request by the SDK be fixed, or am I not using it correctly?

---

For your information, I use the form id obtained from the response from Usabilla when the SDK performs a GET request to "https://sdk.out.usbla.net/campaigns?app_id={appId}" during its initialisation. Furthermore, campaigns display correctly when triggered by events.
_Form ID used_
![form_id_used](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/assets/1858814/7ac9e988-bd48-41f1-999d-d53590623a98)

**Comment by stodorovicc** [comment]
Hi @IsaiahvH ,

Thanks for reaching out, I am happy to help.

One of our SDK developers has checked this and found no issues, it was working perfectly fine for him as you can see in attached screenshot. There is a possibility that it was just a server error at the time of your request, however would you be able to check if you are calling Usabilla.init before loadForm? 

Looking forward to your response.
Kind regards,
Slobodan

**Comment by IsaiahvH** [comment]
Hi @stodorovicc!
Thanks for the quick reply. So strange, I thought I already replied to you 2 days ago, but apparently didn't hit 'Sent' 😅 

Firstly, I do not see an attached screenshot to your comment. Secondly, this "400 Bad Request" occurs for me every time, even now. Would this not indicate a malformed request? Lastly, I do call `Usabilla.initialize(appId:)` before I call `loadFeedbackForm`, yes.

What could be the next step in debugging this?

**Comment by IsaiahvH** [comment]
@stodorovicc is there any more information I could provide you with, or tests I could run?

**Comment by lennardtastic** [comment]
The conversation moved to Support Email. Closing this issue. Please reach out to support@usabilla.com if you have any questions.
