### ISSUE TITLE
Crash in Usabilla.initialize(appID:completion:) 

### ISSUE THREAD

**Issue by jilouc** [usabilla/usabilla-u4a-ios-swift-sdk#260]
We're observing crashes when initializing the Usabilla SDK (which is quite problematic because it happens when the app launches)

Stack trace for the crashing thread:

```
Thread 7 name:
Thread 7 Crashed:
0   libswiftCore.dylib            	0x00000001a59e4dbc swift_isUniquelyReferenced_nonNull_native + 0 (SwiftObject.mm:1367)
1   Usabilla                      	0x000000010a50143c specialized Dictionary._Variant.isUniquelyReferenced() + 8 (<compiler-generated>:0)
2   Usabilla                      	0x000000010a50143c specialized Dictionary._Variant.setValue(_:forKey:) + 52
3   Usabilla                      	0x000000010a5b248c specialized UBTelemetrics.logStart(method:logLevel:) + 332
4   Usabilla                      	0x000000010a5928fc UBTelemetrics.logStart(method:logLevel:) + 12 (UBTelemetricResponse.swift:0)
5   Usabilla                      	0x000000010a5928fc static UsabillaInternal.initialize(appID:completion:) + 276 (UsabillaInternal.swift:146)
6   Usabilla                      	0x000000010a5b1a64 static Usabilla.initialize(appID:completion:) + 116 (Usabilla.swift:133)
[...]
```

This is not limited to a specific iOS version or device (seen on iOS 15, 16, 17 and a variety of devices, recent or not)

**Comment by lennardtastic** [comment]
Hi @jilouc ,

Could you please provide us with some additional information about the implementation (e.g. how are you calling our SDK). Because it seems that it's a threading issue.
You can send the information in a comment here or send them to our Support team via support@usabilla.com.

**Comment by lennardtastic** [comment]
Closing issue on GitHub. If you're still experiencing the issue please reach out to our Support team via [support@usabilla.com](mailto:support@usabilla.com).
