### ISSUE TITLE
[Crash] EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by nrakshith** [usabilla/usabilla-u4a-ios-swift-sdk#264]
Hi Team, 

We are facing this crash in production and not reprodicible in our lower environments. The occurrence of the crash is random and not happening every time. The app is trying to log an analytic event to Usabilla before the crash. Any Insights will be helpful.

SDK version: 6.12.1
iOS versions crash observed: iOS 14, iOS 15, iOS 16 (Also min supported versions by App)

Crash Report :

**Crash** 

Crashed: com.apple.root.default-qos
0  libswiftCore.dylib             0x343d8c swift_isUniquelyReferenced_nonNull_native + 34
1  Usabilla                       0xd247c block_destroy_helper + 41488
2  Usabilla                       0x98b30 block_destroy_helper.33 + 15060
3  App-ios                        0x1e15b4 specialized static Analytics.log<A>(event:) + 4305212852
4  App-ios                        0x135da8 partial apply for closure #3 in closure #1 in closure #1 in closure #1 in Uploader.init(session:) + 57 (Uploader.swift:57)

**Related Threads:** 

com.apple.main-thread
0  libsystem_kernel.dylib         0x4644 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x3a48 mach_msg + 72
2  CoreFoundation                 0x9a0fc __CFRunLoopServiceMachPort + 376
3  CoreFoundation                 0x94570 __CFRunLoopRun + 1176
4  CoreFoundation                 0x93ba0 CFRunLoopRunSpecific + 572
5  GraphicsServices               0x3598 GSEventRunModal + 160
6  UIKitCore                      0xb2e3d8 -[UIApplication _run] + 1052
7  UIKitCore                      0xb33958 UIApplicationMain + 164
8  dlk-ios                        0x76c4 main + 12 (AppDelegate.swift:12)
9  libdyld.dylib                  0x1568 start + 4

Thread
0  libsystem_kernel.dylib         0x2848c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xb5f0 _pthread_wqthread + 348
2  libsystem_pthread.dylib        0xe874 start_wqthread + 8

com.usabilla.u4a.storage
0  libsystem_kernel.dylib         0x29cc4 read + 8
1  Foundation                     0x1294e0 _NSReadFromFileDescriptorWithProgress + 232
2  Foundation                     0x129dec _NSReadBytesFromFileWithExtendedAttributes + 752
3  Foundation                     0x301b4 -[NSData(NSData) initWithContentsOfFile:] + 96
4  Foundation                     0x647b4 -[NSFileManager contentsAtPath:] + 44
5  Usabilla                       0x76208 block_destroy_helper.5 + 9332
6  Usabilla                       0xbc688 block_destroy_helper.17 + 5040
7  Usabilla                       0xbc6a8 block_destroy_helper.17 + 5072
8  libdispatch.dylib              0x61280 _dispatch_client_callout + 16
9  libdispatch.dylib              0x440ec _dispatch_lane_barrier_sync_invoke_and_complete + 56
10 Usabilla                       0xd091c block_destroy_helper + 34480
11 Usabilla                       0xd4c74 block_destroy_helper + 51720
12 Usabilla                       0x98cb0 block_destroy_helper.33 + 15444
13 App-ios                        0x1e15b4 specialized static Analytics.log<A>(event:) + 4305212852
14 App-ios                        0x135da8 partial apply for closure #3 in closure #1 in closure #1 in closure #1 in Uploader.swift(session:) + 57 (Uploader.swift:57)

**Comment by lennardtastic** [comment]
See [v6.13.2](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.13.2) for `released` fix
