### ISSUE TITLE
Update Usabilla SDK to include privacy manifest if needed

### ISSUE THREAD

**Issue by CloudosaurusRex** [usabilla/usabilla-u4a-ios-swift-sdk#265]
Hi there!

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs (e.g. `UserDefaults`) will need to provide a privacy manifest.

Is this update on the roadmap for the team? I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our own app releases to take this into account.

For more info, see:

- [Describing data use in privacy manifests | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
- [Describing use of required reason API | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
- [Get started with privacy manifests - WWDC23 - Videos - Apple Developer](https://developer.apple.com/videos/play/wwdc2023/10060/)

Thanks!

**Comment by lennardtastic** [comment]
Hi @CloudosaurusRex ,

I'm working with our privacy team to get the text for the manifest so that we can include it in the repo.

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
