### ISSUE TITLE
Localization doesn't work when SDK embedded inside of a SPM package

### ISSUE THREAD

**Issue by bkunat** [usabilla/usabilla-u4a-ios-swift-sdk#266]
I've embedded the Usabilla SDK inside a local SPM package (see the project structure below). I need to wrap it inside a package, because I use it in multiple projects. With this setup, the localization does not seem to work: all strings are in English no matter what language is selected on the device.

I'm currently using `Usabilla 6.13.2`.

Some things I've tried:
- Explicitly setting `Usabilla.localizedStringFile`
- Exporting `GetFeedback` (my Usabilla wrapper) into a remote package
- Adding localization keys described [here](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#string-file-contents) to the app's `Localizable.strings` file

I've created a sample project where the Usabilla SDK is located directly inside the app. With this setup, the localization works as expected.
 
![project_structure](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/assets/79861311/dea5fd77-66f8-4d66-a7a8-70c0119138c8)

Is that setup supported?

**Comment by lennardtastic** [comment]
Hi @bkunat , we currently don't support that type of setup. But we're exploring if we can maybe add support for this. We'll keep you posted.
