### ISSUE TITLE
Request to Add Initialization Flag

### ISSUE THREAD

**Issue by bkunat** [usabilla/usabilla-u4a-ios-swift-sdk#267]
## Problem
In our application, only a small subset of users will provide feedback. Consequently, we aim to initialize the Usabilla SDK right before presenting a feedback form. There might be a case where a user submits two feedback forms. Presently, there is no straightforward way to determine if the Usabilla SDK has already been initialized.

The documentation mentions the following:
> This method should be called **once**, inside the AppDelegate's didFinishLaunchingWithOptions method.

## Request
Is it safe to call this initialization method multiple times? Could you consider adding a flag or a mechanism for checking whether the SDK has already been initialized?

Thanks!

**Comment by bkunat** [comment]
Example: 
```
if Usabilla.isInitialized {
  // Present a form
} else {
  Usabilla.initalize() {
  // Present a form
  }
}
```

**Comment by emulroy9** [comment]
Hey @bkunat, if you do this campaigns won’t work unfortunately.
Regarding adding a flag on the SDK, this wouldn't make sense as you control the initialize, you could just keep track of the status in a variable in your app.

**Comment by bkunat** [comment]
We're not using campaigns, so that won't be a problem.
Thanks for the prompt response and clarification!
