### ISSUE TITLE
Data race in Usabilla.customVariables setter leading to crashes

### ISSUE THREAD

**Issue by dyang** [usabilla/usabilla-u4a-ios-swift-sdk#268]
Greetings,

I have encountered a recurring issue with the `Usabilla.customVariables` setter when it is accessed concurrently across multiple threads. This has resulted in an increased number of application crashes. An example crash log is provided below for your reference:

```
Crashed: com.apple.root.user-initiated-qos.cooperative
0  libswiftCore.dylib             0x3bd600 _swift_release_dealloc + 32
1  libswiftCore.dylib             0x3be43c bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 132
2  Usabilla                       0xb56f0 specialized static UsabillaInternal.customVariables.didset + 89 (UsabillaInternal.swift:89)
3  <App Name>                     0x2711c0 Util.loadData(_:) + 202 (Analytics.swift:202)
4  libswift_Concurrency.dylib     0x41948 swift::runJobInEstablishedExecutorContext(swift::Job*) + 416
5  libswift_Concurrency.dylib     0x42868 swift_job_runImpl(swift::Job*, swift::ExecutorRef) + 72
6  libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
7  libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
8  libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
9  libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

The crash can be consistently reproduced using the following test case:

```
func testSetUserProperty() async throws {
    await withTaskGroup(of: Void.self) { group in
        for i in 0..<500 {
            group.addTask {
                Analytics.setUserProperty(String(i), forName: "Test")
            }
        }

        for await _ in group { }
    }
}
```

As a temporary measure, I have implemented a DispatchQueue to serialize all accesses to the `Usabilla.customVariables` setter. While this workaround mitigates the crashes, I kindly request an investigation into the underlying concurrency issue within the SDK.

I'm currently using Usabilla SDK version 6.13.2.

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
