### ISSUE TITLE
Usabilla repo is 1,5 GB in size. Please provide instructions on how to implement a Usabilla binary instead of the whole repo using cocoapods

### ISSUE THREAD

**Issue by tychop** [usabilla/usabilla-u4a-ios-swift-sdk#269]
Usabilla repo is 1,5 GB in size. That is a LOT of data to wait for during pod install...

Can you add instructions on how to implement a binary version of Usabilla?
For example how to use the binary framework from https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/download/v6.13.2/UsabillaXCFramework.zip in my Podfile or (preferably) my Podspec.

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
