### ISSUE TITLE
Trying configure localization

### ISSUE THREAD

**Issue by bbrflores** [usabilla/usabilla-u4a-ios-swift-sdk#3]
While trying to configure localization to normalize the buttons titles (Close button has init uppercase and the submit button as a lower case S).

UsabillaFeedbackForm.localizedStringFile = "Localizable"
UsabillaFeedbackForm.localizedStringFile = "Localizable.strings"

I only get the keys instead of the text from the strings file. Is the format wrong?

**Comment by gPinato** [comment]
Hi, that was a bug on out part.
It should have been fixed with the latest release, v2.0.5.

Could you try that and let me know if it works for you?

The correct form is `UsabillaFeedbackForm.localizedStringFile = "Localizable"`
