### ISSUE TITLE
cannot load underlying module for 'UsabillaFeedbackForm'

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#30]
@gPinato Since v3.3.0 I got the error ```cannot load underlying module for 'UsabillaFeedbackForm'```. I restored the v3.2.0 and all is working like expected.

**Comment by cikpis** [comment]
Seems that using the framework directly all is working like expected. The problem is when I integrate it with Carthage ```carthage update --platform ios --no-use-binaries```

**Comment by grimabe** [comment]
Hi @cikpis 

This issue has been fixed in v3.3.1

**Comment by cikpis** [comment]
Hi @grimabe, thanks!
