### ISSUE TITLE
func formDidClose(_:, _:) does not return the form.

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#33]
As title, we need the form in order to dismiss it. Right now we are forced to save it in a separated  variable.

**Comment by gPinato** [comment]
Hey @cikpis ,
I understand your request, we missed this detail in the last planning.

We will look into adding the form into the delegate callback but it won't be available before the end of the current sprint (about 3 weeks from now).

In the mean time you can use a separate variable to hold a reference to it, it might not be optimal but it will work.

**Comment by cikpis** [comment]
@gPinato 👍

**Comment by gPinato** [comment]
@cikpis v3.3.2 adds the form parameter to the method.

**Comment by cikpis** [comment]
👍
