### ISSUE TITLE
How to use offline mode with the sdk?

### ISSUE THREAD

**Issue by Daij-Djan** [usabilla/usabilla-u4a-ios-swift-sdk#35]
Hi,
on the Isabella webpage you mention offline mode. How can I incorporate this into my apps?

AND related:

how to pre-ship and cache a form?

**Comment by grimabe** [comment]
Hi @Daij-Djan 

The SDK is currently saving the feedback if the user submit it and if the device has no internet connection.
Once the device has a connection back then the SDK sends those feedback automatically.

You should use the [load](`https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#initialization`) in your **AppDelegate** to enable this feature.

However, loading and showing a form when the device has not internet connection is not possible on iOS. This is a feature that is on our roadmap. If this is the feature you were looking for then feel free to leave this issue open and we will notify you when it will be available.

Thanks

**Comment by Daij-Djan** [comment]
Thank you. yes the caching of a form so I can use it later is a feature I was looking for 

thanks for you answer and please do inform me when this is impplemented :)

**Comment by grimabe** [comment]
Hi @Daij-Djan,

As I told you we will keep you updated, here is the latest news regarding caching:

We have been working on the form caching: loading a form in offline mode if it has previously been loaded.
This feature should be shipped in our next release (1-2 weeks from now).
However, it does not concerns pre-shipped forms.

I'll notify you again when it's released.

**Comment by Daij-Djan** [comment]
@grimabe nice!

when online itll query the server as usual though and ill always get the latest changes made to the form, right?

**Comment by grimabe** [comment]
Of course :-)

**Comment by grimabe** [comment]
Hi @Daij-Djan 

With [ 3.4.0 ](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v3.4.0) we introduced support form caching.

> Forms loaded from our servers will be now cached locally and will be correctly displayed even when the user is offline.

And since today with [ 3.4.1 ](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v3.4.1) we also support form pre-loading:

https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#preloading-a-form

Let me know if you have any questions.
