### ISSUE TITLE
After sending form: Goto App Store is not working

### ISSUE THREAD

**Issue by Gerrel** [usabilla/usabilla-u4a-ios-swift-sdk#36]
I'm initializing the form as:
        UsabillaFeedbackForm.delegate = self
        UsabillaFeedbackForm.showCancelButton = true
        UsabillaFeedbackForm.appStoreId = TMConstants.appstoreHostingId
        
        let config : UsabillaThemeConfigurator = UsabillaThemeConfigurator()
        config.headerColor = UIColor.white
        
        UsabillaFeedbackForm.loadFeedbackForm(TMConstants.usabillaDefaultForm, screenshot: nil, customVariables: nil, themeConfig: config)

The button is shown after sending, but touch of the button does not seem to do anything!?

**Comment by gPinato** [comment]
Would you mind sharing the `appstoreHostingId` variable?

Keep in mind that you have to remove the `id` string from the app store id, as stated in the documentation:
> You have to specify the app id omitting the initial "id", leaving only the numerical part.

For example:
`UsabillaFeedbackForm.appStoreId = "412984y21"`

**Comment by Gerrel** [comment]
Variable is:
static let appstoreHostingId = "484504034"

**Comment by gPinato** [comment]
Ok I see the problem, it's indeed on our side. 
I will let you know as soon as a fix is available, it won't take long.

**Comment by gPinato** [comment]
A fix will be available on the next release, which is scheduled in a few days.
I will let you know once it's available.

**Comment by Gerrel** [comment]
@gPinato We want to prepare a release this week. Can the update be available in the next few days?

**Comment by gPinato** [comment]
@Gerrel It will be available later today

**Comment by gPinato** [comment]
@Gerrel Due to a slight delay in some other stuff that needs to be deployed we will release the SDK tomorrow, hopefully during the morning.
I will let you know as soon as we do.

**Comment by gPinato** [comment]
@Gerrel issue has been fixed in v3.3.2. Sorry for the delay.
