### ISSUE TITLE
Properties in FeedbackResult 

### ISSUE THREAD

**Issue by KellydeHaan** [usabilla/usabilla-u4a-ios-swift-sdk#37]
The properties of FeedbackResult (rating and abandonedPageIndex) in formDidClose(formId: with feedbackResults:) have protection level internal, making them inaccessible without using a Mirror.

**Comment by gPinato** [comment]
This has been resolved, a fix will be available this afternoon.

**Comment by KellydeHaan** [comment]
Thank you!

**Comment by gPinato** [comment]
The issue has been fixed in v3.3.2, everything should work fine now.
Sorry for the delay.
