### ISSUE TITLE
Feature request: Callbacks for form validation / page change

### ISSUE THREAD

**Issue by KellydeHaan** [usabilla/usabilla-u4a-ios-swift-sdk#38]
A callback when the form changes page and/or when forms do or don't validate would be appreciated

**Comment by gPinato** [comment]
Being a feature request I will have to discuss this with my PO and he will prioritise it.
Could you please explain why you would like such callback and the benefit it would bring you? 
This would make it easier to push it's priority higher.

**Comment by KellydeHaan** [comment]
I would like these callbacks so that I have more granular control in an officially supported manner for the way the form is presented and user-initiated actions are handled inside the app. This way I can create a much more consistent UI and UX experience throughout the app even though I am delegating parts of it to an outside source.
More specifically, I need this form to have control over only part of the screen, and adjust the rest of the screen to it's current state. As you might have guessed from my bug report about feedback results, I am currently extrapolating from the contents of FeedbackResult, but that seems unnecessarily round-about and hack-y.
Thank you in advance

**Comment by gPinato** [comment]
I have forwarded all the information to the product team. I will get back to you with any information as soon as possible.

**Comment by gPinato** [comment]
Could you please forward this request to support@usabilla.com ?
They are in charge of feature request and they will put you in communication with the product team. 

I know this is not a major request but we have to adhere to certain processes.
Thanks

**Comment by KellydeHaan** [comment]
I will, thank you
