### ISSUE TITLE
FormDidClose not called

### ISSUE THREAD

**Issue by KellydeHaan** [usabilla/usabilla-u4a-ios-swift-sdk#39]
With update 3.3.2 the method FormDidClose isn't getting called anymore

**Comment by grimabe** [comment]
Hi @KellydeHaan In 3.3.2 we added a new declaration for the formDidClose delegate method.

**Comment by KellydeHaan** [comment]
I will go check if it works with this method

**Comment by KellydeHaan** [comment]
Thank you!
