### ISSUE TITLE
What SDK do we use?

### ISSUE THREAD

**Issue by liamnichols** [usabilla/usabilla-u4a-ios-swift-sdk#4]
It looks like there are two iOS SDKs:

https://github.com/usabilla/usabilla-u4a-ios-sdk
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk (this one)

It looks like this one is the most up to date version, and digging around the Usabilla Preview app on the App Store, it looks like you are using this SDK however we've just submitted an update using the other SDK.

I previously opened an issue on the other repo but never got a response so assume this is the best place to ask...

I have noticed that the form our client created on the website loads incorrectly using the objc SDK but looks ok in the preview app. Is that because I should be using this SDK? Or should both SDKs render the feedback form in the same way?

**Comment by gPinato** [comment]
The Swift SDK (this one) is a replacement for the Obj-C one, which has now been deprecated and won't receive any new features, only support with bugs.

We are trying to migrate everyone to this new one. 

There are some differences between how the SDK render the feedback, but they ultimately should both be perfectly functional. Which problem are you experiencing with the Obj-C one?

**Comment by liamnichols** [comment]
Ah ok. Might be worth updating the Readme on the ObjC as I found it hard trying to work out what one to use :)

I have an issue where a multi item picker with an "other" option always shows it's "please specify" text field.

I'm just a dev at an agency so don't know how the client configured the form but it looks fine in the Preview app.

Will suggest we upgrade to the Swift SDK.


Thanks,
Liam

**Comment by gPinato** [comment]
Upgrading to the Swift SDK would be the best choice, and it should require very little work.

If, for some reason, they decide to remain with the Obj-C one, feel free to open an issue and I'll see what I can do to fix the bug.
