### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#40]
Hey guys, could you please update your framework to the latest Swift version?

**Comment by cikpis** [comment]
Also I got this error as well: `dyld: Symbol not found: __TMps13IndexableBase`. Not sure though if it could be useful for you guys :)

**Comment by gPinato** [comment]
Hey @Cikpis,

Version 3.4.0 is compatible with swift 3.1.

In case you still have it, can you provide more info on the error you found?

**Comment by cikpis** [comment]
Hi @gPinato, thanks for the update. I'll try it asap.

**Comment by cikpis** [comment]
Hi @gPinato , seems that all is working like expected.

**Comment by Mozahler** [comment]
I removed my older Swift modules, and replaced with new ones using carthage. I receive this error (only in one project so far, at least a dozen others don't have this issue):
dyld: Symbol not found: __TMps13IndexableBase
  Referenced from: /Users/Alex/Library/Developer/CoreSimulator/Devices/743F0FAB-B924-4998-B9C3-6BF441543603/data/Containers/Bundle/Application/67820A31-B2D2-48E2-A3F8-CB3F1E802A77/Status.app/Frameworks/RealmSwift.framework/RealmSwift
  Expected in: /Users/Alex/Library/Developer/CoreSimulator/Devices/743F0FAB-B924-4998-B9C3-6BF441543603/data/Containers/Bundle/Application/67820A31-B2D2-48E2-A3F8-CB3F1E802A77/Status.app/Frameworks/libswiftCore.dylib
 in /Users/Alex/Library/Developer/CoreSimulator/Devices/743F0FAB-B924-4998-B9C3-6BF441543603/data/Containers/Bundle/Application/67820A31-B2D2-48E2-A3F8-CB3F1E802A77/Status.app/Frameworks/RealmSwift.framework/RealmSwift
