### ISSUE TITLE
Checkbox answers are not on multiple lines

### ISSUE THREAD

**Issue by MelleI** [usabilla/usabilla-u4a-ios-swift-sdk#42]
Our client has issues with the Usabilla checkbox option.

If you entered a long answer in the checkbox Q/A the answers are not displayed on multiple lines:

iPhone 6s size:

![usabilla_checkbox_singleline](https://cloud.githubusercontent.com/assets/19833059/25736796/70038fbe-3174-11e7-83d1-4d5be19958ae.png)

So A user is not able to read the full answer.

Can you fix this?

**Comment by grimabe** [comment]
@MelleI Thank you for letting us know.
We will look into this.
Could you provide the version of SDK you are using?
Thank you

**Comment by MelleI** [comment]
@grimabe Thanks

Using the latest one:

`Installing UsabillaFeedbackForm (3.4.2)`

**Comment by grimabe** [comment]
Hi @MelleI

This issue has been fixed and will be available in the next release (next week).
I'll close the issue once it is released so you will get notified.

**Comment by MelleI** [comment]
@grimabe Thanks. Looking forward to the next release.

**Comment by MelleI** [comment]
@grimabe Past week there was no new release. When is the next version available?

**Comment by grimabe** [comment]
Hi @MelleI  

This issue has been fixed in [v3.4.3](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v3.4.3)
