### ISSUE TITLE
Feature request: Add continue/send button on the bottom of the page

### ISSUE THREAD

**Issue by MelleI** [usabilla/usabilla-u4a-ios-swift-sdk#43]
To be sure the form is send I like to have an optional button which I can configure (change button text) in the Usabilla backend

This button is placed in the form the bottom of the page to continue to the next page or submit the form.

**Comment by gPinato** [comment]
I will forward this feature request to our product team so it can be evaluated and prioritised.

Could you perhaps elaborate on why the button on the bottom would be better than the one on the navigation bar?
Would you like to hide that one and have them only on the bottom or display them both?

This way our product team can have a better idea of what you would like.

**Comment by MelleI** [comment]
Thanks.

We like to have multiple buttons to submit the survey. Navigation button bar is always visible and the other one maybe optional? So you can configure it by yourself. If you start develop this button we also like to customize the button color so it is a 'real' button instead of just some text.

The current 'next' button is in our opinion not in the reading direction of a user, off course it is the default design on iOS. But we have multiple questions and users are scrolling down. With that in mind we are a bit afraid that users are not seeing the navigation bar button and don't submit the form.

**Comment by Goseong** [comment]
Hi @MelleI,

We are currently not prioritizing this feature request. I would still like to thank you for your suggestion. 

I advise you to limit the number of questions inside your form, so that your users are not overloaded. If all the questions are critical, please consider spreading them across multiple pages.

Regards,

Tjerk
