### ISSUE TITLE
Control visibility is not working correctly

### ISSUE THREAD

**Issue by MelleI** [usabilla/usabilla-u4a-ios-swift-sdk#44]
For example I have a form like this:

1. Emoticons
2. Slider
3. Checkboxes

In the Usabilla backend I setup the following visibility for:

**The slider:**

- When: Emoticons
- Is: Hate, Dislike, Neutral
- State: Show

**The checkboxes:**

- When: Slider
- Is: 4,5
- State: Show

Now the problems:

User select dislike, slider is showing up, slider value is changed to 4 or 5, checkboxes are showing up. But the users changed the emoticon to like or live, the slider is hidden but the checkboxes are not.

First looks fine:

![start_ok](https://cloud.githubusercontent.com/assets/19833059/25746578/7367348c-31a4-11e7-8eda-e9be49851c57.png)

Changed emoticons: checkboxes are still showed
![changed_emoticon_checkboxes_showed](https://cloud.githubusercontent.com/assets/19833059/25746585/775fc874-31a4-11e7-8271-4de7e55e1d18.png)

After that a user changed back to hate, dislike or neutral: 

- The slider is reset to 1
- Checkboxes are showed... but that is not the visibility control I setup, the checkboxes should only show on slider value 4 or 5

![switch_back](https://cloud.githubusercontent.com/assets/19833059/25746648/c23569f8-31a4-11e7-8dd9-3b57d7713972.png)

I report this issue here under the iOS SDK but the Android SDK has the same behaviour.

**Comment by grimabe** [comment]
@MelleI Thank you for letting us know.
We will look into this.
Could you provide the version of SDK you are using?
Thank you

**Comment by MelleI** [comment]
@grimabe Latest one:

`Installing UsabillaFeedbackForm (3.4.2)`

**Comment by grimabe** [comment]
Hi @MelleI 

This issue has been fixed and will be available in the next release (next week).
I'll close the issue once it is released so you will get notified.

**Comment by MelleI** [comment]
@grimabe Awesome! Thanks for the support.

**Comment by grimabe** [comment]
Hi @MelleI  

This issue has been fixed in [v3.4.3](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v3.4.3)
