### ISSUE TITLE
Scrolling issue on comment field

### ISSUE THREAD

**Issue by maartenaalbers** [usabilla/usabilla-u4a-ios-swift-sdk#46]
Hi Guys,

We added the iOS SDK to our app and load a simple form onto it.
But when we try to add text to a comment field at the bottom of the form, were getting some weird scrolling behaviour. I added a movie (in a zip because GitHub won't allow it) to demonstrate the issue.

[Usabilla iOS Scroll issue.mp4.zip](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/files/1003684/Usabilla.iOS.Scroll.issue.mp4.zip)

(using the 3.4.1 version of the SDK)

**Comment by grimabe** [comment]
Hi @maartenaalbers,

We can indeed observe a bug within the video, however, I did not succeed to reproduce it.
In order to reproduce it, I will need the formId.
Is it possible that you send the formId by email (not on github) at support@usabilla.com with the link of this issue inside ?

Thank you

**Comment by maartenaalbers** [comment]
Mail sent!

**Comment by grimabe** [comment]
Hi @maartenaalbers 

After some testing, we did not succeed to reproduce the bug with the form id you provided.
Could you send us the iOS version and Device model you are using ? does it also happen within the simulator? 

Thanks

**Comment by grimabe** [comment]
Hi @maartenaalbers 

This issue has been fixed in [v3.4.3](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v3.4.3)
