### ISSUE TITLE
"submit" button should be capitalised?

### ISSUE THREAD

**Issue by liamnichols** [usabilla/usabilla-u4a-ios-swift-sdk#5]
In the old ObjC SDK the "submit" button text is capitalised however in this SDK it isn't.
When you then include the "Close" button, it looks inconsistent (see screenshot)

![simulator screen shot 26 aug 2016 12 31 21](https://cloud.githubusercontent.com/assets/482871/18004015/2fa7adf8-6b89-11e6-87c1-39fa553408cf.png)

**Comment by gPinato** [comment]
The submit button text is set in the [web app of Usabilla](https://app.usabilla.com/member/apps), in the advanced panel.    
The SDK only displays what is set there.

You can chance it in the web app and everything will be fine.
