### ISSUE TITLE
Redirect to the AppStore seems not working

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#53]
Hey guys, I'm using the 3.4.4 and we went live yesterday with that. We just tried the redirect feature and seems is not working. 

Should I set some params in the project beside to enable it in the form advance settings?

**Comment by Goseong** [comment]
Hi cikpis, 

For your specific version, you should set the`UsabillaFeedbackForm.appStoreId` attribute as well. Our apologies if this was not apparent enough from the documentation.

However, as this requires you to do an app update, I recommend you to do the following instead. Recently we have released a new mechanism to handle App Store ratings & reviews. We now use Apple's recommended implementation for prompting your users for a review. This approach shows much stronger conversion in comparison to the previous implementation. It also keeps your users inside your app, where previously they would leave your app in order for them to write a review. I recommend you to update to the latest version of our SDK 3.6.0 to utilize the updated implementation.

You can find a detailed article about the implementation on our support page [here](https://support.usabilla.com/hc/en-us/articles/115003995845-Ask-your-users-for-iOS-App-store-reviews-).

**Comment by cikpis** [comment]
Hi @Goseong , thanks for the answer and yes, I didn't found it in the documentation :)

We are not planning to update the SDK right now and for that, I should just set the `UsabillaFeedbackForm.appStoreId` right?

**Comment by Goseong** [comment]
Hi cikpis, yes that is correct if that is your preferred approach.

However, if your customer is eager to have the best conversion, I strongly advise you to update to 3.6.0.

Have a great weekend.
