### ISSUE TITLE
Module compiled with Swift 2.3 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by qasimmajeed** [usabilla/usabilla-u4a-ios-swift-sdk#54]
Deployment target of my application is 8.0 but i cannot build my project with the old usabilla framework .
Please suggest me to how can i resolved the issue  ?

**Comment by Goseong** [comment]
Thank you for your inquiry. I have asked our Customer Representative to contact your account holder directly. We will follow up from there.
