### ISSUE TITLE
Flickering Label

### ISSUE THREAD

**Issue by Werewolve** [usabilla/usabilla-u4a-ios-swift-sdk#58]
See this video: https://www.dropbox.com/s/3bmnioy4gezx4ei/Blinken_bei_Textfeld.MOV?dl=0
Top Label flickering if TextField becomes focused.

**Comment by gPinato** [comment]
Hi @Werewolve ,
We've created a ticket to solve this issue.
I will let you know as soon as there is any progress.

**Comment by torkvell** [comment]
Hi @Werewolve,

I would like to thank you for reporting on this. The ticket for this has been moved into our backlog as a future reference to possible fixes. 

If you have any other questions, please let us know.
