### ISSUE TITLE
Missing german localization

### ISSUE THREAD

**Issue by Werewolve** [usabilla/usabilla-u4a-ios-swift-sdk#59]
"Please check this field" is missing in german localization.
![lokalisierung_falsch](https://user-images.githubusercontent.com/3767530/30069646-986f76f4-9261-11e7-98f9-d130a58afcb4.PNG)

**Comment by gPinato** [comment]
Hi @Werewolve ,

That particular string needs to be localised in the SDK.
There is a [paragraph in our wiki](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/wiki/Localization#string-file-contents) that explains how you can configure it.

This should fix your problem.

**Comment by Werewolve** [comment]
Hi @gPinato,
how can I configure this strings?

> Rate on the App Store
> Return to App

**Comment by gPinato** [comment]
Those must be configured in our web interface, in the Advanced panel of the form editor. It looks like this 

![image](https://user-images.githubusercontent.com/6040180/30266883-0f57da62-96e1-11e7-845a-0915c232b1f4.png)

I guess the strings you want to configure are `App store redirect` and `Cancel button`.
