### ISSUE TITLE
UsabillaFeedbackFormDelegate typos 

### ISSUE THREAD

**Issue by liamnichols** [usabilla/usabilla-u4a-ios-swift-sdk#6]
public protocol UsabillaFeedbackFormDelegate {
        public func feedbackFromLoadedCorreclty(form: UINavigationController, active: Bool)
        public func feedbackFromLoadedIncorreclty(backupForm: UINavigationController)
    }

"From" -> "Form"
"Correclty" -> "Correctly"
"Incorreclty" -> "Incorrectly"

**Comment by gPinato** [comment]
Apparently I have to take 2nd grade again.    
They will be fixed in the next release.
Thanks for pointing them out.

**Comment by liamnichols** [comment]
Haha no worries :)
