### ISSUE TITLE
How to introduce usabilla in projects that support iOS 8

### ISSUE THREAD

**Issue by coder4LYK** [usabilla/usabilla-u4a-ios-swift-sdk#61]
Hello Usabilla,
We want to introduce Usabilla into the project that supports iOS 8.
We tried the SDK v2.3.0, but we are failed to build the project.
How should we solve this problem?
<img width="1388" alt="default" src="https://user-images.githubusercontent.com/12741142/30236330-de3ef66a-9549-11e7-9096-775621eac302.png">

**Comment by Goseong** [comment]
Hi @coder4LYK,

I understand that you are trying to implement an older version of our SDK into your app. In this specific scenario there is a problem with an outdated dependency. I don't see a solution to this.

We would love for you to be able to use the latest version of our SDK. In fact we are about to release a major new feature over the next few weeks which I think our customers will really benefit from. Although it does not offer support for iOS 8.

I suggest discussing the situation with your Usabilla contact person and myself as there are a few different ways we can go about this. Please feel free to have them reach out to tjerk@usabilla.com and support@usabilla.com.
