### ISSUE TITLE
Usabilla Crash on Submit

### ISSUE THREAD

**Issue by Werewolve** [usabilla/usabilla-u4a-ios-swift-sdk#62]
Hi,
since a few days (we don't really know since when exactly) our app crashes if we try to submit Usabilla feedback. The crash log does not give as any information about what is wrong. The android version ist working and the old (not swift) SDK is working too.

See the attached Crash Report. Hope you can help us soon.
Cheers!

[Eurowings  11.09.17, 10-51.crash.txt](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/files/1291937/Eurowings.11.09.17.10-51.crash.txt)

**Comment by Goseong** [comment]
Hi Felix,

Thanks for reaching out. Unfortunately the logs don't provide much reason for this to occur.

Could you provide us with the following information:

- Xcode version
- Form ID
- Does it also happen when you load a different form from the one that let to this scenario?
- Does it occur specifically on this device or are you able to reproduce it on different iOS devices?

Regards,

Tjerk

**Comment by Werewolve** [comment]
Hi Tjerk,

Xcode: Version 8.3.3
FormID's: 573c3255a92db3918b6b29c3 / 56092aae7d57424269f908c1
Error occurs on both forms
Tested on different devices and simulators

Cheers, Felix

**Comment by gPinato** [comment]
Hi @Werewolve ,

It looks like the SDK is crashing while trying to set the title of the left navigation button.
Are you perhaps doing something with it or presenting the form in a particular way?
