### ISSUE TITLE
Xcode 9 and Swift 3.2

### ISSUE THREAD

**Issue by federicocappelli-je** [usabilla/usabilla-u4a-ios-swift-sdk#63]
I'm having a problem migrating to Xcode 9 (Swift 3.2):

`/.../Pods/UsabillaFeedbackForm/JESettingsMasterViewController+Usabilla.swift:10:8: Module compiled with Swift 3.1 cannot be imported in Swift 3.2: /.../Pods/UsabillaFeedbackForm/UsabillaFeedbackForm.framework/Modules/UsabillaFeedbackForm.swiftmodule/x86_64.swiftmodule`

Are you quickly planning a new version with the fix?

**Comment by grimabe** [comment]
@federicocappelli-je I assume you found the issue?

**Comment by federicocappelli-je** [comment]
@grimabe Yes thanks :)

**Comment by tychop** [comment]
What was your fix?

**Comment by federicocappelli-je** [comment]
@tychop update your pod using:
`pod 'UsabillaFeedbackForm', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git', :branch=> 'feature/swift3.2'`

then delete derived data and re-build. should be ok.

**Comment by tychop** [comment]
Figured it out...
In my lib's podspec I needed

> s.dependency "UsabillaFeedbackForm", '3.6.1-swift3.2'

Then in my project's podfile, I needed

> pod 'UsabillaFeedbackForm', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git', :branch=> 'feature/swift3.2'

Thnx
