### ISSUE TITLE
Compatibility with Xcode 9.1 beta 2 and Swift 3.2

### ISSUE THREAD

**Issue by daveanderson** [usabilla/usabilla-u4a-ios-swift-sdk#66]
Similar to #49 https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git feature/swift3.2 is no longer working with Xcode 9.1 beta 2 and is yielding the error

```
Module compiled with Swift 4.0 cannot be imported in Swift 3.2.1
```

**Comment by gPinato** [comment]
Hi @daveanderson ,

I just pushed a new branch with v4.0.0 compiled with Xcode9.1-beta2.

You can fetch it with `pod 'Usabilla', :git => 'git@github.com:usabilla/usabilla-u4a-ios-swift-sdk.git', :branch=> 'Xcode9.1-beta`

**Comment by daveanderson** [comment]
Thanks @gPinato. Unfortunately I'm trying to use it and I'm getting 

```
error: cannot load underlying module for 'Usabilla'
import Usabilla
       ^
```

**Comment by gPinato** [comment]
Hi @daveanderson ,

We've found that, for some reason, the framework only works in the same XCode it was compiled with.
This means that my colleagues are also getting your error if they use mine, and each of them gets that error if they use a framework compiled by someone else.

It only works if you compile the framework and run it in the same XCode.

At this point, it's most likely a bug on XCode. 
We will open a radar and keep you updated.

**Comment by daveanderson** [comment]
@gPinato iOS 9.1 is now released. Do you have a Usabilla build that matches? Thanks!

**Comment by gPinato** [comment]
@daveanderson Yes, a build is coming today

**Comment by gPinato** [comment]
The release has just been published. Let us know if everything works correctly.

**Comment by cikpis** [comment]
Under which tag/branch?

**Comment by grimabe** [comment]
@cikpis you can look at the **Releases** tab on Github: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

![screen shot 2017-11-01 at 17 36 26](https://user-images.githubusercontent.com/1334148/32285662-3de56f26-bf2b-11e7-9bdb-15073f851d68.png)

The little tag icon on the left displays (v4.0.1) of the release. And if you inspect the commit associated with the tag you will see it is part of the **master** branch.

**Comment by cikpis** [comment]
@grimabe I was from mobile and I couldn't inspect it properly. Instead of explain how to check it, which seems a little a joke, you could have answered directly `v4.0.1`.

**Comment by grimabe** [comment]
@cikpis I agree that on mobile, Github user experience is terrible and we can't see the releases page.
Well by reading your question I was not sure whether or not you knew how to see the tags/releases.
Let me know if there is anything else.

**Comment by daveanderson** [comment]
@grimabe Unfortunately the release notes do not specifically mention which Xcode version this could/should be used with.

**Comment by grimabe** [comment]
@daveanderson we are thinking about releasing a table with release version / Xcode compatibility to make it more clear and we also gonna update the changelog now that you mention it indeed.
In this case, this release (v4.0.1) is only compatible with XCode 9.1. We have another one coming for Xcode 8.3.3.

**Comment by daveanderson** [comment]
Thanks for the release today. It's working here with Xcode 9.1 and iOS 11.1

**Comment by federicocappelli-je** [comment]
I can't find right now version 4.0.1 in cocoapods https://cocoapods.org/pods/UsabillaFeedbackForm

`[!] Unable to satisfy the following requirements:
- `UsabillaFeedbackForm (= 4.0.1)` required by `Podfile``

**Comment by gPinato** [comment]
The pod has been renamed to `Usabilla`.
https://cocoapods.org/pods/Usabilla
