### ISSUE TITLE
Compatibility with Carthage / Xcode 9.0.1

### ISSUE THREAD

**Issue by edwinveger** [usabilla/usabilla-u4a-ios-swift-sdk#67]
When having installed Xcode 9.0.1, Carthage refuses to fetch the binary.

Running `carthage update` has the following result:

> `Skipped installing usabilla-u4a-ios-swift-sdk.framework binary due to the error:
"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65.2 clang-900.0.37)."`

 This is reproducible with a Cartfile containing just `github "usabilla/usabilla-u4a-ios-swift-sdk" "v4.0.0"`.

Although on local machines we can just manually download the binary as a workaround, our CI (BitRise) is running Xcode 9.0.1 and the build fails.

Can you make a branch for Xcode 9.0.1 and release a binary? That way we can complete our Usabilla 4.0 integration.

**Comment by grimabe** [comment]
Hi @edwinveger,

Thanks for reporting this.
A new version of the SDK is about to be released (probably this week).
We will make sure it works with Xcode 9.0.1.
