### ISSUE TITLE
Compatibility with Carthage / Xcode 9.1

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#68]
Hey guys, I just installed the the new Xcode version 9.1 but I got this error.
```Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2```

Could you please update it and let me know which tag/branch should I use?

Thanks

**Comment by cikpis** [comment]
Maybe should I use ```v4.0.0-Xcode9.1-beta2```?

**Comment by grimabe** [comment]
Hi @cikpis 
We are aware of that are gonna release a new version today. Please follow #66 for the updates.
I am closing that one.
