### ISSUE TITLE
[Question] Renaming

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#69]
Hey guys, did you rename `UsabillaFeedbackForm.framework` to `Usabilla.framework`?

If yes, and I guess so, would be nice to add that in the change logs because in my case, I'm using Carthage, I need to specify the name of the file in my script.

Let me know, thanks.

**Comment by grimabe** [comment]
Hi @cikpis 

Yes, UsabillaFeedbackForm (both the framework and the public interface) has been renamed to Usabilla, it was indeed in the changelogs:

https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v4.0.0
https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/blob/master/CHANGELOG.MD#updated

Although it is true the .framework extension was not specified.

**Comment by cikpis** [comment]
Nice thanks!
