### ISSUE TITLE
UsabillaThemeConfigurator - Incorrect enum for statusBarStyle

### ISSUE THREAD

**Issue by liamnichols** [usabilla/usabilla-u4a-ios-swift-sdk#7]
The UsabillaThemeConfigurator class has a property called `statusBarColor` used to set the appropriate status bar style on the navigation controller however it's a `UIBarStyle` enum value.

Is this not the wrong enum for the preferredStatusBarStyle? I have to specify `UIBarStyle.Black` to get a white status bar.

Seems very confusing, could it not be simplified by making it a `UIStatusBarStyle` enum?

**Comment by gPinato** [comment]
I will take a look at this issue and see if I can make it more clear. I'll update you as soon as I have some news.

Sorry for the long wait.

**Comment by gPinato** [comment]
It was indeed a weird way of customising the status bar.
The SDK now uses UIStatusBarStyle.
