### ISSUE TITLE
Compatibility with Xcode 9.1

### ISSUE THREAD

**Issue by edwinveger** [usabilla/usabilla-u4a-ios-swift-sdk#70]
I am running Xcode 9.1 and I manually downloaded the binary from release "v4.0.0-Xcode9.1-beta2".

This gives me the following error: `Cannot load underlying module for 'Usabilla'`. I expect this is related to Xcode 9.1, and the binary having been built with the 9.1-beta2. 

Can you make a branch for Xcode 9.1 and release a binary? That way, I can move to the latest version of Xcode and deploy to devices running iOS 11.1.x.

**Comment by gPinato** [comment]
@edwinveger The release has just been published. Let us know if everything works

**Comment by edwinveger** [comment]
Works like a charm, thanks for the quick reply!
