### ISSUE TITLE
Delegates are not being called on Carthage v4.0.1

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#73]
Hey @grimabe , here I am again. Since I update the version to v4.0.1 with Carthage, the delegates are not being called.

Here the code that I'm using:
```
Usabilla.initialize(appID: appID)
Usabilla.delegate = self
Usabilla.theme.fonts.regular = Font.avenirLight.big
Usabilla.dismissAutomatically = false
Usabilla.loadFeedbackForm(mycode)
```

I never used before `Usabilla.load()` so not sure if I have to use `Usabilla.initialize(appID: appID)`. I added it because I wanted to follow your documentation. Anyway, the appID is the app id of iTunes store, is that correct?

Said so, after `loadFeedbackForm` is called, no delegates are called. Any help here?

Thanks

**Comment by grimabe** [comment]
Hi @cikpis,

You did right in adding the **initialize** method. This method is required to initialize the SDK whether you are using the new active targeting/Campaign feature (that came with **4.0.0**) or not.

**If you are using the Campaign feature** you have to provide the **appID** to enable active targeting. This **appID** is an Id that identifies your app in our system (so it is different to the app store id) and can be created and configured in the [Usabilla Web App](https://app.usabilla.com/member/#/apps/campaigns/overview) .

**If you do not use the campaign feature** you can just use nil as **appID**. The passive feedback will still work.

In [4.0.0](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v4.0.0), we renamed **UsabillaFeedbackFormDelegate** protocol to **UsabillaDelegate** as well as the delegate methods. Could you check if you are indeed implementing **UsabillaDelegate** protocol and correctly implementing the following methods:

```swift
func formDidLoad(form: UINavigationController)
```
```swift
func formDidFailLoading(error: UBError)
```

**Comment by cikpis** [comment]
Yeah. I was using the new delegates already. The problem was that I was using the app store id. Passing nil solved all. 

Thanks!
