### ISSUE TITLE
lipo: -remove's specified would result in an empty fat file

### ISSUE THREAD

**Issue by Gois** [usabilla/usabilla-u4a-ios-swift-sdk#77]
When I try to use Usabilla with CocoaPods and run it on a simulator in Xcode, I get an error: "lipo: -remove's specified would result in an empty fat file"

This issue doesn't occur when I add the framework manually or run the app on a device.

I'm using Xcode 9.1 and version 4.0.1 of the SDK.

**Comment by grimabe** [comment]
Hi @Gois,

Could you provide the line you added to your Podfile?
You mention in the title of the issue lipo -remove: Could you explain more about what you did?
Also, we release 4.0.2 could you check if you still have a problem with this version?

Thank you

**Comment by Gois** [comment]
Hi @grimabe,

I've updated to 4.0.2 and the issue seems to be fixed now, thanks.
