### ISSUE TITLE
Xcode 8 support

### ISSUE THREAD

**Issue by liamnichols** [usabilla/usabilla-u4a-ios-swift-sdk#8]
Do you have any pre-release versions that support Swift 2.3 and Swift 3.0?

I've migrated over to this version of the Swift SDK because the ObjC one is being deprecated however now I can't compile my project in Xcode 8 using Swift 2.3 because Swift dependancies of this library (Alamofire etc) only support Swift 2.2.

Because the framework itself is closed source, I can't fork and fix the issues myself.

**Comment by UsabillaSuccess** [comment]
Hi Liam,

Unfortunately we don't have a version available that supports Swift 2.3 just yet. I'd be happy to see if we can send you any pre-release version. I'd have to check this with my colleague who will be back from vacation coming Monday? Would that be okay?

**Comment by ushafiq** [comment]
Hello,

Is there any update regarding XCode 8? Since it is now available.

**Comment by liamnichols** [comment]
I was just thinking.. due to the design of this framework, there is no way that you can support both swift 2.3 and swift 3. 

Can you take a look at keeping the old objc SDK available please.

Thanks

**Comment by ushafiq** [comment]
Unfortunately not, other pods I have are already migrated to Xcode 8. Can you please made two versions of SDK available? Swift 2.3 and Swift 3.

**Comment by gPinato** [comment]
I'm working on the update right now.
I will first release a version of our SDK 2.3 compatible, then I will migrate it to swift 3.0.

The next release will also contain a bunch of fixes for all the issues that have been reported.

The ETA for the 2.3 update show be 2 to 4 working days. 
I'm sorry for the inconvenience, but I can't rush things and deliver an incomplete or broken product.

**Comment by ushafiq** [comment]
Hi @gPinato ,

Is there any update for Usabilla xcode 8 issue?

**Comment by gPinato** [comment]
SDK v2.1 has been released today and it is Swift 2.3 compatible.
It also solved a bunch of other issues listed in the change log.

Please try it in your application and, if you have any problems, report them and I'll solve them as soon as possible.

A version compatible with Swift 3.0 will be released in the future but there is still not ETA for that one.

**Comment by sgoodwin** [comment]
We also need the 3.0 SDK. Can't use the framework until it's supported.

**Comment by liamnichols** [comment]
I've just gone back to the objc version. It's a better implementation (in comparison) and also the only option despite being technically deprecated.

**Comment by gPinato** [comment]
I understand. The support for Swift 3.0 is scheduled for my next sprint. I will keep you posted with the progress and notify you as soon as it's available.

**Comment by gPinato** [comment]
v3.0.0 has just been released and it supports Swift 3.0.
Sorry for the long wait.

There are minor changes to the implementation, you can find them in the changelog.
