### ISSUE TITLE
[Proposal] Do not change the Navigation Bar Appearance

### ISSUE THREAD

**Issue by federicocappelli-je** [usabilla/usabilla-u4a-ios-swift-sdk#80]
I've noticed that the navigation bar appearance set globally is still overwritten in the Usabilla feedback page even after the 4.0.2 bug fix, is this the intended behaviour?
The navigation bar appearance customization can be really advanced for some apps, with backgrounds, custom fonts, custom colours and more. Usabilla should use the fonts and colours set in the framework configuration only in the form itself and leave the Navigation Bar untouched.

**Comment by gPinato** [comment]
Sorry for the very late answer.

Modifying the hosting application is not an intended behaviour, and we have worked on fixing this bug. Our customisation should be limited to our SDK.

If you still experience any problem related to this, please let me know here.
