### ISSUE TITLE
Event sent with application launch is ignored 

### ISSUE THREAD

**Issue by mohammedDehairy** [usabilla/usabilla-u4a-ios-swift-sdk#84]
Hi I have an event that is sent when the application is launching after the Usabilla initialization but somehow it gets ignored.

This event is sent with ApplicationDidBecomeActive, but when the event is sent with cold boot after Usabilla initialization some how it doesn't get counted, but when its sent with warm boot it gets counted and the questionnaire is triggered but not with cold boot.

but the "Event [event-name] sent!" debug message is logged with both warm and cold boot!

I am using SDK v 4.0.2 on iPad Air iOS 9.0 simulator in swift 4.0 app

**Comment by gPinato** [comment]
Hi @mohammedDehairy ,

When the SDK is initialising for the first time, it needs some time to fetch the latest data from our servers before becoming fully functional. 
Therefore it might happen that an event sent immediately after the app has been opened gets lost.

We are aware this is a shortcoming and a feature that prevents event from being lost at anytime (even while the SDK is initialising) is being worked on already.

I will let you know as soon as this becomes available.

**Comment by mohammedDehairy** [comment]
@gPinato Thanks for the quick reply!
1. when would we expect this new feature to be released ? 
2. and in the meanwhile what do you suggest to do to work around this ? is there for example some completion closure that gets called when initialization is finished ? or maybe a delegate method ? or if not I can postpone the event until later, but not sure for how long should it be postponed it ?

Thank you

**Comment by Goseong** [comment]
Hi @mohammedDehairy,

As part of our current sprint, we will add a callback when the SDK has been successfully initialized. You can use this to target a campaign near the app launch. I will be sure to post here when the release becomes available.

**Comment by Goseong** [comment]
Hi @mohammedDehairy, 

Thank you for your feedback. Using our iOS 4.1.1 release you can now use a callback when the SDK is finished initializing. 

https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#initialization

We think this will help you with submitting events on app launch. If there is anything else feel free to reach out.
