### ISSUE TITLE
The Usabilla campaign form overrides the current visible viewController preferredStatusBarStyle

### ISSUE THREAD

**Issue by mohammedDehairy** [usabilla/usabilla-u4a-ios-swift-sdk#85]
I have some viewControllers in the app which has UIStatusBarStyle.lightContent preferredStatusBarStyle and others UIStatusBarStyle.default, but when the Usabilla campaign form is triggered on top of a .lightContent viewController it turns the statusBarStyle to .default.

I am using Usabilla 4.0.2 version, with iOS 9.x, 10.x, and 11.x

**Comment by gPinato** [comment]
HI @mohammedDehairy ,

sorry for the late answer. To clarify, the usabilla SDK changes the status of your app or is just not aligned with it?

You can change the status bar color of the SDK by setting `Usabilla.theme.statusBarStyle = .lightContent` and `View controller-based status bar appearance` to `NO`.

If this setting leaks into your app it's a bug and it should not happen.
