### ISSUE TITLE
No method signatures in the Header files

### ISSUE THREAD

**Issue by fekberg** [usabilla/usabilla-u4a-ios-swift-sdk#88]
Why are the Header files pretty much empty?

Without definitions for the given methods, I can't bind this project with Xamarin.

**Comment by Goseong** [comment]
Hi Filip, as part of our short-term roadmap we will provide multiple bridges between frameworks such as Xamarin and our Usabilla SDKs. A first release of the ReactNative framework can be found here https://github.com/usabilla/usabilla-u4a-react-native

Regarding Xamarin, I suggest you reach out to our support team via support@usabilla.com and share some insights into the project you are working on and which Usabilla customer it belongs.

**Comment by fekberg** [comment]
@Goseong Nope, Xamarin doesn't support Swift 4.

**Comment by torkvell** [comment]
Hi @fekberg, 

I'm reaching out to you from Usabilla support. I would like to give you an update on this feature request:

We're working towards a Xamarin solution and it's part of our SDK roadmap, moving forward. I'm not able to give any time estimations on this yet. 

I hope this helps. Please let us know if anything else.
