### ISSUE TITLE
Swift 4.1/Xcode 9.3 support

### ISSUE THREAD

**Issue by tJulianB** [usabilla/usabilla-u4a-ios-swift-sdk#89]
Hello,

do you have any plan to support Swift 4.1 (in Xcode 9.3) ? Thanks

**Comment by Goseong** [comment]
Hi @tJulianB, we expect to make a new release soon. Either by the end of this week or early next week. We will also include an Xcode 9.3/Swift 4.1 build.

**Comment by tJulianB** [comment]
Thanks for this quick answer and for your work 👍 Have a nice day :)

**Comment by daveanderson** [comment]
@Goseong Also looking for this. Glad it's on your near-term roadmap.

**Comment by Goseong** [comment]
Hi @tJulianB the build for Xcode 9.3 beta 4 is part of our new sprint. We will be sure to use the latest beta release available at that time. Thank you for your patience.

**Comment by edwinveger** [comment]
Xcode 9.3 was released yesterday. Where can I find a binary for Swift 4.1? Even though @Goseong mentioned building for the beta three weeks ago, I can't find Xcode 9.3 support in any of the releases.

This is blocking us from migrating to Swift 4.1. I am sorry to say this is not the first time the Usabilla SDK is an impediment for Swift migration - is there a possibility of open sourcing the SDK so we needn't bother you guys with this anymore?

**Comment by Goseong** [comment]
I can understand you are impeted by this, which must be frustrating. We are releasing on Tuesday. Apologies for the delay.
