### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by ErikLuimes** [usabilla/usabilla-u4a-ios-swift-sdk#91]
When trying to compile my project (with Usabilla as a cocoapod) I get the following error message: Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

**Comment by hkramer70** [comment]
We have the same problem here. Actually, we have to disable/remove Usabilla because of this showstopper.

**Comment by Goseong** [comment]
We are releasing a new version on Tuesday. We will update you here.

**Comment by Nonnus** [comment]
same problem here, just posting to be notified of solution

**Comment by cyrille-legrand** [comment]
me too

**Comment by patrikolsson75** [comment]
Same here. This worries me, that you need to release a new version when there is a new Swift version. You need to be more flexible.

**Comment by andrey-manov** [comment]
me too

**Comment by edwinveger** [comment]
Guys, if you also have this issue, give the OP a 👍 . If you wish to remain notified of new posts, tap the Subscribe button. 
Please refrain from posting stuff like "me too" or "same here". This dilutes the value of notifications for people who are subscribed.

**Comment by mr-rock** [comment]
@edwinveger Pierre be.

**Comment by Rifinio** [comment]
Hello guys, 
We are sorry for this unfortunate delay releasing this update. The new release [Usabilla v4.1.2](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v4.1.2) is out and it's compatible with Xcode 9.3.

**Comment by gbabucs** [comment]
Thanks

**Comment by Nonnus** [comment]
great news! but sadly still not working here: now i get: `"Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.41 clang-902.0.31) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."`
using carthage here on latest xcode 9.3 (9E145)

**Comment by edwinveger** [comment]
Manually downloading the binary is a workaround, but only for a local machine. This blocks any CI pipeline.

**Comment by Rifinio** [comment]
@Nonnus @edwinveger could you please retry now? we updated the release and the framework is built with `4.1 (swiftlang-902.0.48 clang-902.0.37.1).`

**Comment by Nonnus** [comment]
@Rifinio just retried, and happy to report it worked fine now!

**Comment by Rifinio** [comment]
The reason was that our automation script that is responsible for generating SDK releases for different Xcode versions was using Xcode 9.3 beta 3 instead of the GM which explains the error you were getting @Nonnus.
Thank you for letting us know !
