### ISSUE TITLE
Why is USabilla app SDK distributed as a closed source framework?

### ISSUE THREAD

**Issue by jeroenleenarts** [usabilla/usabilla-u4a-ios-swift-sdk#93]
I think it would be great to allow third party developers to contribute bug fixes to the SDK. Currently, every time Apple provides an update to it's Xcode tool train, Usabilla end-users have to wait for Usabilla to update accordingly.

Also, I think it is best to openly show what Usabilla does on the device... Just like the JS or Python components of which the source code is open to public review.

**Comment by Goseong** [comment]
Hi @jeroenleenarts ,

We can see how that would allow for more flexibility and valuable contribution by developers. We have considered this, however, it is not something we want to pursue at this moment in time. 

Thank you for sharing your insights.

**Comment by jeroenleenarts** [comment]
Why does Usabilla have to be such a headache for iOS developers?

We've are dealing with having to withhold moving forward with adopting new Xcode versions all the time and the only reason Usabilla has is that it's not something worth pursuing.

Fine with me, but then at least stay on top of every single Xcode release posted by Apple. Including all the Beta releases like within a day. Looking at what the Python and JS SDKs do, there's nothing magical happening in the iOS SDK...

I would not recommend Usabilla to anyone strictly due to the slow update adoption.

**Comment by Goseong** [comment]
Hi @jeroenleenarts, we will always push out a new version to support a GM release. 

We don't always have the resources to provide a build for every beta release, especially when they are weekly. 

At this moment we are not considering to open up our code base. We will evaluate whether there are other measures we can take to make your life easier.
