### ISSUE TITLE
How are the campaign forms presented?

### ISSUE THREAD

**Issue by cosminstirbu** [usabilla/usabilla-u4a-ios-swift-sdk#95]
Hello,

Looking at the documentation, it seems that in order to load the passive feedback form, the integrator is passed the UINavigationController that contains the form and he is responsible of presenting it.

However, it's not clear how are the campaign forms presented.

Is this something that Usabilla does automagically, without allowing any delegation to the integrator? If so, does it present it using a separate UIWindow? Or does it present it on using the top most view controller?

I am concerned on how this might impact our application, in case the campaign form is presented while there's another presentation in progress for instance.

Thank you,
Cosmin

**Comment by Rifinio** [comment]
Hello @cosminstirbu,

Indeed, we show the triggered campaigns in a new `UIWindow` which is not supposed to change anything in the hosting app and we are not adding it on the top most view controller.
The interaction is still possible with hosting app while the campaign is triggered and it does not interfere with any presentation in progress.
I hope this answers your concern.

Best regards, 
Adil.

**Comment by cosminstirbu** [comment]
Hi @Rifinio 

Thank you for your answer.

Is there a way to control the supported orientations of that `UIWindow`? 

In our application we use a per UIViewController orientation support approach and we'd like the campaign UI (both the sliding bottom dialog and the pop-over view) to be consistent with the orientation of our view controllers.

Is there any way we can control that?

Is this something you can add on your roadmap?

Thank you,
Cosmin

**Comment by Rifinio** [comment]
Hello @cosminstirbu,
I see your point in making the campaigns look and feel the same way as the rest of your app. 
What i can tell you is  that it's on the roadmap to support also a top down orientation for the sliding dialog (Now only showing from the bottom) But not sure when to be delivered yet! Could you elaborate more on what kind of presentations you are interested for (both sliding banner and pop-over view) and preferably share if you have any examples that we could take a look at.

**Comment by cosminstirbu** [comment]
I'm not referring to a different presentation style (bottom to top vs top to bottom). 

I'm referring to the screen orientation - Landscape vs Portrait and how we would be able to configure this for Usabilla Campaigns.

**Comment by Rifinio** [comment]
@cosminstirbu You don't need to configure anything for Usabilla campaigns. The campaigns views adjust to the screen orientation. If you have any problem with a specific screen and orientation please share it with us.

**Comment by cosminstirbu** [comment]
Yes, they do adjust when they are presented initially.

But if you rotate the screen while the bottom Usabilla view is displayed, and the currently visible view controller has the orientation locked to portrait (programmatically), the Usabilla view will rotate regardless.

**Comment by Goseong** [comment]
Hi @cosminstirbu, we are pretty confident that the scenario you describe will not occur. Can you send us a screenshot?

**Comment by cosminstirbu** [comment]
Here it is.

![simulator screen shot - iphone x - 2018-05-16 at 15 55 13](https://user-images.githubusercontent.com/7135690/40118101-a27fc982-5921-11e8-829a-85ef3a98896a.png)
![simulator screen shot - iphone x - 2018-05-16 at 15 55 06](https://user-images.githubusercontent.com/7135690/40118102-a29dc482-5921-11e8-8a7d-2f4a59a33559.png)

**Comment by Goseong** [comment]
Hi @cosminstirbu, 

Thank you for your quick reply. Can you share the device configuration as we couldn't reproduce this behaviour.

**Comment by cosminstirbu** [comment]
The issue reproduces on any device/simulator using iOS 10+.

You can reproduce this by allowing all supported orientations at the application level (via Info.plist). And then, on the UIViewController where the sliding bottom Usabilla view will be presented, make sure you override https://developer.apple.com/documentation/uikit/uiviewcontroller/1621435-supportedinterfaceorientations and return `portrait`.

Then when the Usabilla view is displayed, and you are holding your device / simulator on portrait, simply rotate the screen and you'll reproduce the behavior.

Hopefully this gives you enough information.

Regards,
Cosmin

**Comment by Goseong** [comment]
Thank you for the additional context @cosminstirbu, we will have a look at that configuration and keep you up to date here.

Regards,

Tjerk

**Comment by torkvell** [comment]
Hi @cosminstirbu ,

I've created a ticket for our backlog so we can look into the possibilities of adding a property that can force a Usabilla campaign to be in either landscape or portrait mode. Please note it's registered as a feature request.  Thank you for reporting on this and please keep us updated on valuable feedback!

Let me know if you need anything else.
