### ISSUE TITLE
No way to know which campaign was submitted

### ISSUE THREAD

**Issue by wumbo** [usabilla/usabilla-u4a-ios-swift-sdk#96]
The campaign submission callback doesn't give any indication of which campaign was submitted, which can cause issues if you have multiple campaigns.

**Comment by Goseong** [comment]
Hi @wumbo, 

Can you explain what you are trying to achieve?

Regards,

Tjerk

**Comment by Goseong** [comment]
Hi @wumbo, 

Let me know if you have some context on what you are trying to achieve.

Regards,

Tjerk

**Comment by gPinato** [comment]
Hello @wumbo,

the information you're looking for is contained in the `FeedbackResult` object returned by the callback.
