### ISSUE TITLE
New release for swift 4.1.2 / XCode 9.4?

### ISSUE THREAD

**Issue by Nonnus** [usabilla/usabilla-u4a-ios-swift-sdk#97]
Xcode 9.4 was just released yesterday and it includes Swift 4.1.2, when do you plan to release a version of the library compiled with latest Xcode

ps: ideally you should not be providing pre built libraries to avoid this problem where everytime there is an update to xcode you need to create new release

**Comment by Rifinio** [comment]
Hi @Nonnus,
Did you experience any problem with the latest release of the SDK 5.0.0 ?

**Comment by rocketnik** [comment]
Yes, I am also experiencing problems with the 5.0.0 version using carthage. The Swift compiler changed from 4.1 to 4.1.2 and the binary from 5.0.0 was compiled with 4.1 is ist not abi compatible.

**Comment by Goseong** [comment]
Hi guys, as this seems to be limited to your app environment, we will make sure that our next iOS release is built with Xcode 9.4. 

We will not make a hotfix for this, but you can expect the new release early next week. Hope that works for you. We will keep you posted here.

Regard,

Tjerk

**Comment by rocketnik** [comment]
Looking forward to the fix.

**Comment by Nonnus** [comment]
same here, any news about this @Goseong ?

**Comment by Rifinio** [comment]
Hi guys @rocketnik @Nonnus,

We have released a new version of the SDK [v5.0.1](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v5.0.1). 
Let us know if it solves your problem.

Best, 
Adil

**Comment by Nonnus** [comment]
will do! thanks a lot!

**Comment by rocketnik** [comment]
Thank you! Already on it!

**Comment by rocketnik** [comment]
Seems to work. Thank you again!

**Comment by Rifinio** [comment]
Great! 
I am closing this issue then!
