### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported in Swift 4.1.50

### ISSUE THREAD

**Issue by iCarambaa** [usabilla/usabilla-u4a-ios-swift-sdk#98]
Please provide a build for the latest beta.

**Comment by koenpunt** [comment]
For example an alpha release of the SDK that is build with the Xcode 10 beta. By tagging it as alpha, users can't accidentally update to this version.

Without such a release we're unable to actually test our app for iOS 12, without removing the Usabilla SDK from the app.

**Comment by Goseong** [comment]
We will get something out this week and notify you here.

**Comment by Rifinio** [comment]
I am closing this issue.

**Comment by jacknewcombe-je** [comment]
I can confirm it worked fine with our testing - thanks!

**Comment by koenpunt** [comment]
It doesn't seem to work for me with "Xcode 10.0 beta (10L176w)". The error I'm getting;

> Module compiled with Swift 4.1.2 cannot be imported in Swift 4.1.50

![image](https://user-images.githubusercontent.com/351038/41526039-37efdf7c-72e3-11e8-9d1e-bb802268c4c2.png)

**Comment by Rifinio** [comment]
@koenpunt what dependency manager are you using? 
Because we tested it for both Cocoapods and Carthage after the release and everything works fine. and external developers confirmed it too!

**Comment by koenpunt** [comment]
Nevermind, I now see there are multiple 5.0.2 tags, I need `v5.0.2-Xcode-10` and install it from git.

For anyone who's wondering how to use it:

```rb
pod 'Usabilla', git: 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk', tag: 'v5.0.2-Xcode-10'
```

**Comment by jeroenleenarts** [comment]
Beta 4 broke it again. Can we get a new release ASAP?

**Comment by kateorlova** [comment]
the problem is acute also for beta 6

**Comment by koenpunt** [comment]
@DavidAdade You need to use v5.1.2

**Comment by 9thstudio** [comment]
I just upgraded to xcode 10 and Mojave and see this error

Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/username/workspace/appname/node_modules/usabilla-react-native/ios/Usabilla.framework/Modules/Usabilla.swiftmodule/x86_64.swiftmodule

**Comment by koenpunt** [comment]
@9thstudio you probably have to clean your build folder and/or deriveddata folder.

**Comment by 9thstudio** [comment]
Still getting the same error after clean build and removing all content of deriveddata
![image](https://user-images.githubusercontent.com/42678120/46909749-4db08400-cf05-11e8-87f0-dc1af5e39141.png)

**Comment by Rifinio** [comment]
@9thstudio it seems like you are using Usabilla for react native!
Please use the last release [v0.6.0](https://github.com/usabilla/usabilla-u4a-react-native/releases/tag/v0.6.0) that supports Swift 4.2 and Xcode 10.

**Comment by 9thstudio** [comment]
Yes, Thanks @Rifinio I have update it and also change to Build to Legacy Build system. Works fine!

**Comment by revsimpson** [comment]
@Rifinio I am trying 
pod 'Usabilla', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git', :tag => 'v5.1.2-Xcode-10'
and 
pod 'Usabilla','~> 5.1.2'

But it cannot find them. I tried everything above but I still get **Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler (and of course I installed the 5.0 version but that is what gives me the error above)
