### ISSUE TITLE
Can’t add screenshots via Usabilla passive feedback form

### ISSUE THREAD

**Issue by sgl0v** [usabilla/usabilla-u4a-ios-swift-sdk#99]
Unfortunately, I can’t add screenshots via Usabilla passive feedback form on iOS. As far as I can see the image picker's (UIImagePickerController) events are not handled correctly for some reason. Just check the next [demo](https://www.dropbox.com/s/oba3vhfaq62e9e4/IMG-5478.TRIM.MOV?dl=0).

**Comment by Rifinio** [comment]
Hello @sgl0v,
Unfortunately we cannot deduct the causes from the video since it seems to happen only in your case.
Could you please provide us with more context (SDK version, iOS version, Xcode version) or even better a simple demo app in which you can reproduce it.
Best,

Adil.

**Comment by sgl0v** [comment]
Hi @Rifinio,

We are using the next environment:
Xcode 9.3 & 9.4 
iPhone 7, 6s Plus
iOS 9.3-11.4

Regards,
Max

**Comment by torkvell** [comment]
Hi @sgl0v, 

I'm from Usabilla support. I'm happy to assist you with this. Is this still an issue at your end? 

You should be able to take a screenshot at any moment by calling: 
`let image = Usabilla.takeScreenshot(self.view)`

To attach the screenshot to the form, pass it as a parameter when calling:
`usabilla.loadFeedbackForm("Form Id", screenshot: image)`

More can be read here: [](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#adding-a-screenshot)

If you have any questions, please let us know

**Comment by sgl0v** [comment]
No, this is not an issue anymore. Thanks for the help!
